#!/usr/bin/env bash
# IS THE BATCHED PENALTY THE RMS CORE'S CHUNK REGENERATION?
#
# docs/DFlashFeasibility.md 3.17: the vocab-only stream costs 7.278 ms at batch
# 1 and 13.800 at batch 8 on identical weights, with no attention, KV, rope or
# GLU in it. PROJ_MM_PROBE already showed the projection arithmetic is 2% of a
# batched layer, so the proj cores are waiting. The unexamined question is WHAT
# FOR -- the doc assumed weights; the other candidate is X.
#
# At batch 1 the rms core normalizes once and refeed() collapses the
# re-broadcast into a lock init: the core is not in the loop at all. At batch >1
# the normalized batch cannot be materialized, so _rms_batched_norm regenerates
# each chunk inside the loop, for all B rows, through a SINGLE staging buffer.
# That is the one thing in this design that goes from ZERO work to B-proportional
# work at exactly the batch boundary where the penalty appears.
#
# XCHUNK_MUL was read as excluding it and does not: it halved the handshake
# COUNT while doubling the bytes per handshake, so it holds regenerated bytes
# constant. It excludes a per-transfer fixed cost. It says nothing about a
# per-byte one.
#
# RMS_CHUNK_PROBE=2 deletes the regeneration outright and leaves y as it was --
# a TRUE deletion (rms_residual.cc is explicit that substituting plain C for an
# intrinsic kernel measures Peano's lack of auto-vectorisation instead, which is
# how probe 1 came out 87 ms SLOWER than the code it replaced). Every handshake,
# lock, descriptor and DMA stays exactly where it was; the bytes are simply
# stale.
#
#   collapses toward the batch-1 time  -> the regeneration IS the penalty
#   moves ~2% like PROJ_MM_PROBE       -> not it either; the penalty is transport
#
# Batch 1 is the control: the regeneration is not in that path, so the probe
# must be inert there. If it is not, the probe is measuring something else.
set -euo pipefail
cd "$(dirname "$0")"
export DECODE_MODEL=qwen3-4b-draft VOCAB_CHUNK_I2=30 W_DUAL_CHAN=1 \
       DECODE_NO_LM_WAVES=0 DECODE_HIDDEN_TAPS=0 DECODE_MASK_BIDIR=1 \
       PROJ_RING_DEPTH=3
unset DECODE_EXTRA_WAVES || true
DST=../llms/qwen3_4b_q4nx
L=${1:-511}
UDEC=5; UALL=15

for B in "${@:2}"; do
  [ "$B" = 8 ] && export DECODE_STACK=6080 || unset DECODE_STACK
  for LL in $L $((L+1)); do
    echo "=== r3_b${B}_L${LL}  (full, waves [0,$UALL)) ==="; date
    rm -f decode_b${B}_L${LL}.xclbin decode_b${B}_L${LL}.insts.bin \
          "$DST/r3_b${B}_L${LL}.xclbin" "$DST/r3_b${B}_L${LL}.insts.bin"
    ./build_template.sh $B $LL
    mv -f decode_b${B}_L${LL}.xclbin    "$DST/r3_b${B}_L${LL}.xclbin"
    mv -f decode_b${B}_L${LL}.insts.bin "$DST/r3_b${B}_L${LL}.insts.bin"
  done
  for s in nolm lmonly; do
    case $s in
      nolm)   LO=0;     HI=$UDEC ;;
      lmonly) LO=$UDEC; HI=$UALL ;;
    esac
    echo "=== _t${s}_b${B}_L${L}.insts.bin  waves [$LO,$HI) ==="; date
    rm -f decode_b${B}_L${L}.xclbin decode_b${B}_L${L}.insts.bin \
          "$DST/_t${s}_b${B}_L${L}.insts.bin"
    UNI_WAVE_LO=$LO UNI_WAVE_HI=$HI ./build_template.sh $B $L
    mv -f decode_b${B}_L${L}.insts.bin "$DST/_t${s}_b${B}_L${L}.insts.bin"
    rm -f decode_b${B}_L${L}.xclbin
  done
done
unset PROJ_RING_DEPTH
./build_template.sh 1 16 >/dev/null
date; echo "PROJ_RING_DEPTH=3 TEMPLATES DONE"
