
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E280, LENGTH = 0x1D80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf47 = .;
. += 0x80;
. = 0x42400;
buf46 = .;
. += 0x80;
. = 0x40400;
buf45 = .;
. += 0x2000;
. = 0x44000;
buf44 = .;
. += 0x2000;
. = 0x48000;
buf43 = .;
. += 0x2000;
. = 0x4C000;
buf42 = .;
. += 0x2000;
. = 0x46000;
buf41 = .;
. += 0x2000;
. = 0x4E080;
buf40 = .;
. += 0x80;
. = 0x42480;
buf39 = .;
. += 0x80;
. = 0x4A000;
buf38 = .;
. += 0x2000;
. = 0x4E100;
buf37 = .;
. += 0x80;
. = 0x42500;
buf36 = .;
. += 0x80;
. = 0x4E180;
buf35 = .;
. += 0x80;
. = 0x42580;
buf34 = .;
. += 0x80;
. = 0x4E200;
buf33 = .;
. += 0x80;
. = 0x42600;
buf32 = .;
. += 0x80;
. = 0x5E000;
buf95 = .;
. += 0x80;
. = 0x52400;
buf94 = .;
. += 0x80;
. = 0x50400;
buf93 = .;
. += 0x2000;
. = 0x54000;
buf92 = .;
. += 0x2000;
. = 0x58000;
buf91 = .;
. += 0x2000;
. = 0x5C000;
buf90 = .;
. += 0x2000;
. = 0x56000;
buf89 = .;
. += 0x2000;
. = 0x5E080;
buf88 = .;
. += 0x80;
. = 0x52480;
buf87 = .;
. += 0x80;
. = 0x5A000;
buf86 = .;
. += 0x2000;
. = 0x5E100;
buf85 = .;
. += 0x80;
. = 0x52500;
buf84 = .;
. += 0x80;
. = 0x5E180;
buf83 = .;
. += 0x80;
. = 0x52580;
buf82 = .;
. += 0x80;
. = 0x5E200;
buf81 = .;
. += 0x80;
. = 0x52600;
buf80 = .;
. += 0x80;
. = 0x6E000;
buf175 = .;
. += 0x80;
. = 0x62400;
buf174 = .;
. += 0x80;
. = 0x60400;
buf173 = .;
. += 0x2000;
. = 0x64000;
buf172 = .;
. += 0x2000;
. = 0x68000;
buf171 = .;
. += 0x2000;
. = 0x6C000;
buf170 = .;
. += 0x2000;
. = 0x66000;
buf169 = .;
. += 0x2000;
. = 0x6E080;
buf168 = .;
. += 0x80;
. = 0x62480;
buf167 = .;
. += 0x80;
. = 0x6A000;
buf166 = .;
. += 0x2000;
. = 0x6E100;
buf165 = .;
. += 0x80;
. = 0x62500;
buf164 = .;
. += 0x80;
. = 0x6E180;
buf163 = .;
. += 0x80;
. = 0x62580;
buf162 = .;
. += 0x80;
. = 0x6E200;
buf161 = .;
. += 0x80;
. = 0x62600;
buf160 = .;
. += 0x80;
. = 0x7E000;
buf111 = .;
. += 0x80;
. = 0x72400;
buf110 = .;
. += 0x80;
. = 0x70400;
buf109 = .;
. += 0x2000;
. = 0x74000;
buf108 = .;
. += 0x2000;
. = 0x78000;
buf107 = .;
. += 0x2000;
. = 0x7C000;
buf106 = .;
. += 0x2000;
. = 0x76000;
buf105 = .;
. += 0x2000;
. = 0x7E080;
buf104 = .;
. += 0x80;
. = 0x72480;
buf103 = .;
. += 0x80;
. = 0x7A000;
buf102 = .;
. += 0x2000;
. = 0x7E100;
buf101 = .;
. += 0x80;
. = 0x72500;
buf100 = .;
. += 0x80;
. = 0x7E180;
buf99 = .;
. += 0x80;
. = 0x72580;
buf98 = .;
. += 0x80;
. = 0x7E200;
buf97 = .;
. += 0x80;
. = 0x72600;
buf96 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_1h_ref/attn.o)
PROVIDE(main = core_2_3);
