
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E280, LENGTH = 0x1D80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x6E000;
buf79 = .;
. += 0x80;
. = 0x62400;
buf78 = .;
. += 0x80;
. = 0x60400;
buf77 = .;
. += 0x2000;
. = 0x64000;
buf76 = .;
. += 0x2000;
. = 0x68000;
buf75 = .;
. += 0x2000;
. = 0x6C000;
buf74 = .;
. += 0x2000;
. = 0x66000;
buf73 = .;
. += 0x2000;
. = 0x6E080;
buf72 = .;
. += 0x80;
. = 0x62480;
buf71 = .;
. += 0x80;
. = 0x6A000;
buf70 = .;
. += 0x2000;
. = 0x6E100;
buf69 = .;
. += 0x80;
. = 0x62500;
buf68 = .;
. += 0x80;
. = 0x6E180;
buf67 = .;
. += 0x80;
. = 0x62580;
buf66 = .;
. += 0x80;
. = 0x6E200;
buf65 = .;
. += 0x80;
. = 0x62600;
buf64 = .;
. += 0x80;
. = 0x7E000;
buf15 = .;
. += 0x80;
. = 0x72400;
buf14 = .;
. += 0x80;
. = 0x70400;
buf13 = .;
. += 0x2000;
. = 0x74000;
buf12 = .;
. += 0x2000;
. = 0x78000;
buf11 = .;
. += 0x2000;
. = 0x7C000;
buf10 = .;
. += 0x2000;
. = 0x76000;
buf9 = .;
. += 0x2000;
. = 0x7E080;
buf8 = .;
. += 0x80;
. = 0x72480;
buf7 = .;
. += 0x80;
. = 0x7A000;
buf6 = .;
. += 0x2000;
. = 0x7E100;
buf5 = .;
. += 0x80;
. = 0x72500;
buf4 = .;
. += 0x80;
. = 0x7E180;
buf3 = .;
. += 0x80;
. = 0x72580;
buf2 = .;
. += 0x80;
. = 0x7E200;
buf1 = .;
. += 0x80;
. = 0x72600;
buf0 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_1h_ref/attn.o)
PROVIDE(main = core_0_2);
