#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_CORTEXA72_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_CORTEXA72_0_CPU_CLK_FREQ_HZ 1349998657
#define XPAR_CIPS_0_PSPMC_0_PSV_CORTEXA72_0_TIMESTAMP_CLK_FREQ 99999901


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_CORTEXA72_0 */
#define XPAR_CPU_CORTEXA72_0_CPU_CLK_FREQ_HZ 1349998657
#define XPAR_CPU_CORTEXA72_0_TIMESTAMP_CLK_FREQ 99999901


/******************************************************************/

 /* Definition for PSS REF CLK FREQUENCY */
#define XPAR_PSU_PSS_REF_CLK_FREQ_HZ 33333000U

#include "xparameters_ps.h"

#define XPS_BOARD_VCK5000


/* Number of Fabric Resets */

#define STDIN_BASEADDRESS 0xFF000000
#define STDOUT_BASEADDRESS 0xFF000000

/******************************************************************/

/* Platform specific definitions */
#ifndef versal
#define versal
#endif

 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver AXICDMA */
#define XPAR_XAXICDMA_NUM_INSTANCES 1

/* Definitions for peripheral AXI_CDMA_0 */
#define XPAR_AXI_CDMA_0_DEVICE_ID 0
#define XPAR_AXI_CDMA_0_BASEADDR 0xA4000000
#define XPAR_AXI_CDMA_0_HIGHADDR 0xA400FFFF
#define XPAR_AXI_CDMA_0_INCLUDE_DRE 0
#define XPAR_AXI_CDMA_0_USE_DATAMOVER_LITE 0
#define XPAR_AXI_CDMA_0_M_AXI_DATA_WIDTH 32
#define XPAR_AXI_CDMA_0_INCLUDE_SG 1
#define XPAR_AXI_CDMA_0_M_AXI_MAX_BURST_LEN 256
#define XPAR_AXI_CDMA_0_ADDR_WIDTH 64


/******************************************************************/

/* Canonical definitions for peripheral AXI_CDMA_0 */
#define XPAR_AXICDMA_0_DEVICE_ID XPAR_AXI_CDMA_0_DEVICE_ID
#define XPAR_AXICDMA_0_BASEADDR 0xA4000000
#define XPAR_AXICDMA_0_HIGHADDR 0xA400FFFF
#define XPAR_AXICDMA_0_INCLUDE_DRE 0
#define XPAR_AXICDMA_0_USE_DATAMOVER_LITE 0
#define XPAR_AXICDMA_0_M_AXI_DATA_WIDTH 32
#define XPAR_AXICDMA_0_INCLUDE_SG 1
#define XPAR_AXICDMA_0_M_AXI_MAX_BURST_LEN 256
#define XPAR_AXICDMA_0_ADDR_WIDTH 64


/******************************************************************/

#define XAXICDMA_MAX_TRANSFER_LEN    0x3FFFFFF
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1U

/* Definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_AXI_BRAM_CTRL_0_DEVICE_ID 0U
#define XPAR_AXI_BRAM_CTRL_0_DATA_WIDTH 256U
#define XPAR_AXI_BRAM_CTRL_0_ECC 0U
#define XPAR_AXI_BRAM_CTRL_0_FAULT_INJECT 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_UE_FAILING_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_STATUS_REGISTERS 0U
#define XPAR_AXI_BRAM_CTRL_0_CE_COUNTER_WIDTH 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_REGISTER 0U
#define XPAR_AXI_BRAM_CTRL_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_AXI_BRAM_CTRL_0_WRITE_ACCESS 0U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR 0x20100000000U
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_HIGHADDR 0x2010001FFFFU
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_AXI_BRAM_CTRL_0_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral AXI_BRAM_CTRL_0 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_AXI_BRAM_CTRL_0_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 256U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0x20100000000U
#define XPAR_BRAM_0_HIGHADDR 0x2010001FFFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver CFRAME */
#define XPAR_XCFRAME_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0_BASEADDR 0xF12D0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0 */
#define XPAR_XCFRAME_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFI_CFRAME_0_DEVICE_ID
#define XPAR_XCFRAME_0_BASEADDR 0xF12D0000
#define XPAR_XCFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Definitions for driver CFUPMC */
#define XPAR_XCFUPMC_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0_BASEADDR 0xF12B0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0 */
#define XPAR_XCFUPMC_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_CFU_APB_0_DEVICE_ID
#define XPAR_XCFUPMC_0_BASEADDR 0xF12B0000
#define XPAR_XCFUPMC_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Definitions for driver CSUDMA */
#define XPAR_XCSUDMA_NUM_INSTANCES 2

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_DMA_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_BASEADDR 0xF11C0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_CSUDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_DMA_1 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_DEVICE_ID 1
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_BASEADDR 0xF11D0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_DMATYPE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_DMATYPE 2
/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_DMA_0 */
#define XPAR_XCSUDMA_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_0_DEVICE_ID
#define XPAR_XCSUDMA_0_BASEADDR 0xF11C0000
#define XPAR_XCSUDMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_XCSUDMA_0_CSUDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_DMA_1 */
#define XPAR_XCSUDMA_1_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_DMA_1_DEVICE_ID
#define XPAR_XCSUDMA_1_BASEADDR 0xF11D0000
#define XPAR_XCSUDMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_XCSUDMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/


/* Definitions for peripheral AXI_NOC_0 */
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_AXI_NOC_0_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_AXI_NOC_0_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_AXI_NOC_1_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_AXI_NOC_1_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_0_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_0_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_1_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_1_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_2_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_2_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_3_BASEADDR 0x00000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW0X4_FPD_CCI_NOC_3_HIGHADDR 0x7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_AXI_NOC_0_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_AXI_NOC_0_HIGHADDR 0xF7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_AXI_NOC_1_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_AXI_NOC_1_HIGHADDR 0xF7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_0_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_0_HIGHADDR 0xF7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_1_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_1_HIGHADDR 0xF7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_2_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_2_HIGHADDR 0xF7FFFFFFF
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_3_BASEADDR 0x800000000
#define XPAR_AXI_NOC_0_C0_DDR_LOW1X4_FPD_CCI_NOC_3_HIGHADDR 0xF7FFFFFFF

/* Canonicals definitions for NOC DDR to be consumed by MMU/MPU tables in BSP*/
#define XPAR_AXI_NOC_DDR_LOW_0_BASEADDR 0x00000000
#define XPAR_AXI_NOC_DDR_LOW_0_HIGHADDR 0x7FFFFFFF

#define XPAR_AXI_NOC_DDR_LOW_1_BASEADDR 0x800000000
#define XPAR_AXI_NOC_DDR_LOW_1_HIGHADDR 0xF7FFFFFFF


/******************************************************************/


/* Peripheral Definitions for peripheral AXI_DBG_HUB_0 */
#define XPAR_AXI_DBG_HUB_0_BASEADDR 0x80000000
#define XPAR_AXI_DBG_HUB_0_HIGHADDR 0x801FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_APU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_APU_0_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_CIPS_0_PSPMC_0_PSV_APU_0_S_AXI_HIGHADDR 0xFD5CFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_STM */
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_STM_S_AXI_BASEADDR 0xF0B70000
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_STM_S_AXI_HIGHADDR 0xF0B7FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_CPM */
#define XPAR_CIPS_0_PSPMC_0_PSV_CPM_S_AXI_BASEADDR 0xFC000000
#define XPAR_CIPS_0_PSPMC_0_PSV_CPM_S_AXI_HIGHADDR 0xFCFFFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRF_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_CRF_0_S_AXI_BASEADDR 0xFD1A0000
#define XPAR_CIPS_0_PSPMC_0_PSV_CRF_0_S_AXI_HIGHADDR 0xFD2DFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRL_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_CRL_0_S_AXI_BASEADDR 0xFF5E0000
#define XPAR_CIPS_0_PSPMC_0_PSV_CRL_0_S_AXI_HIGHADDR 0xFF8DFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRP_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_CRP_0_S_AXI_BASEADDR 0xF1260000
#define XPAR_CIPS_0_PSPMC_0_PSV_CRP_0_S_AXI_HIGHADDR 0xF126FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_AFI_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_AFI_2 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_AFI_2_S_AXI_BASEADDR 0xFD380000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_AFI_2_S_AXI_HIGHADDR 0xFD38FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_CCI_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_CCI_0_S_AXI_BASEADDR 0xFD5E0000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_CCI_0_S_AXI_HIGHADDR 0xFD5EFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_GPV_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_GPV_0_S_AXI_BASEADDR 0xFD700000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_GPV_0_S_AXI_HIGHADDR 0xFD7FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_MAINCCI_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_MAINCCI_0_S_AXI_BASEADDR 0xFD000000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_MAINCCI_0_S_AXI_HIGHADDR 0xFD0FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLAVE_XMPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLAVE_XMPU_0_S_AXI_BASEADDR 0xFD390000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLAVE_XMPU_0_S_AXI_HIGHADDR 0xFD39FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLCR_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLCR_0_S_AXI_BASEADDR 0xFD610000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLCR_0_S_AXI_HIGHADDR 0xFD61FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLCR_SECURE_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFD690000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFD69FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SMMU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SMMU_0_S_AXI_BASEADDR 0xFD5F0000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SMMU_0_S_AXI_HIGHADDR 0xFD5FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SMMUTCU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SMMUTCU_0_S_AXI_BASEADDR 0xFD800000
#define XPAR_CIPS_0_PSPMC_0_PSV_FPD_SMMUTCU_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_AFI_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_AFI_0_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_AFI_0_S_AXI_HIGHADDR 0xFF9BFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_BASEADDR 0xFF0A0000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_HIGHADDR 0xFF0AFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_IOU_SLCR_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_IOU_SLCR_0_S_AXI_BASEADDR 0xFF080000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_IOU_SLCR_0_S_AXI_HIGHADDR 0xFF09FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_SLCR_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_SLCR_0_S_AXI_BASEADDR 0xFF410000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_SLCR_0_S_AXI_HIGHADDR 0xFF50FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_SLCR_SECURE_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFF510000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFF54FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_XPPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_XPPU_0_S_AXI_BASEADDR 0xFF990000
#define XPAR_CIPS_0_PSPMC_0_PSV_LPD_XPPU_0_S_AXI_HIGHADDR 0xFF99FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_CTRL */
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_CTRL_S_AXI_BASEADDR 0xFF960000
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_CTRL_S_AXI_HIGHADDR 0xFF96FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_RAM_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_XMPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_XMPU_0_S_AXI_BASEADDR 0xFF980000
#define XPAR_CIPS_0_PSPMC_0_PSV_OCM_XMPU_0_S_AXI_HIGHADDR 0xFF98FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_AES */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_AES_S_AXI_BASEADDR 0xF11E0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_AES_S_AXI_HIGHADDR 0xF11EFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_BBRAM_CTRL */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_BBRAM_CTRL_S_AXI_BASEADDR 0xF11F0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_BBRAM_CTRL_S_AXI_HIGHADDR 0xF11FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CACHE */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CACHE_S_AXI_BASEADDR 0xF1250000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CACHE_S_AXI_HIGHADDR 0xF125FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CTRL */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CTRL_S_AXI_BASEADDR 0xF1240000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CTRL_S_AXI_HIGHADDR 0xF124FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_GLOBAL_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_GLOBAL_0_S_AXI_BASEADDR 0xF1110000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_GLOBAL_0_S_AXI_HIGHADDR 0xF115FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RAM */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RAM_S_AXI_BASEADDR 0xF2000000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RAM_S_AXI_HIGHADDR 0xF201FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RAM_NPI */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RAM_NPI_S_AXI_BASEADDR 0xF6000000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RAM_NPI_S_AXI_HIGHADDR 0xF7FFFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RSA */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RSA_S_AXI_BASEADDR 0xF1200000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RSA_S_AXI_HIGHADDR 0xF120FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SHA */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SHA_S_AXI_BASEADDR 0xF1210000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SHA_S_AXI_HIGHADDR 0xF121FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_S_AXI_BASEADDR 0xF1220000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_S_AXI_HIGHADDR 0xF122FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_STREAM */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_STREAM_S_AXI_BASEADDR 0xF2100000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_STREAM_S_AXI_HIGHADDR 0xF210FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XMPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XMPU_0_S_AXI_BASEADDR 0xF12F0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XMPU_0_S_AXI_HIGHADDR 0xF12FFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XPPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XPPU_0_S_AXI_BASEADDR 0xF1310000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XPPU_0_S_AXI_HIGHADDR 0xF131FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XPPU_NPI_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XPPU_NPI_0_S_AXI_BASEADDR 0xF1300000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_XPPU_NPI_0_S_AXI_HIGHADDR 0xF130FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_PSM_GLOBAL_REG */
#define XPAR_CIPS_0_PSPMC_0_PSV_PSM_GLOBAL_REG_S_AXI_BASEADDR 0xFFC90000
#define XPAR_CIPS_0_PSPMC_0_PSV_PSM_GLOBAL_REG_S_AXI_HIGHADDR 0xFFC9EFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_1_ATCM_GLOBAL */
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_1_ATCM_GLOBAL_S_AXI_BASEADDR 0xFFE90000
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_1_ATCM_GLOBAL_S_AXI_HIGHADDR 0xFFE9FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_1_BTCM_GLOBAL */
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_1_BTCM_GLOBAL_S_AXI_BASEADDR 0xFFEB0000
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_1_BTCM_GLOBAL_S_AXI_HIGHADDR 0xFFEBFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_TCM_RAM_GLOBAL */
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_TCM_RAM_GLOBAL_S_AXI_BASEADDR 0xFFE00000
#define XPAR_CIPS_0_PSPMC_0_PSV_R5_TCM_RAM_GLOBAL_S_AXI_HIGHADDR 0xFFE3FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_RPU_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_RPU_0_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_CIPS_0_PSPMC_0_PSV_RPU_0_S_AXI_HIGHADDR 0xFF9AFFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_SCNTR_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_SCNTR_0_S_AXI_BASEADDR 0xFF130000
#define XPAR_CIPS_0_PSPMC_0_PSV_SCNTR_0_S_AXI_HIGHADDR 0xFF13FFFF


/* Peripheral Definitions for peripheral CIPS_0_PSPMC_0_PSV_SCNTRS_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_SCNTRS_0_S_AXI_BASEADDR 0xFF140000
#define XPAR_CIPS_0_PSPMC_0_PSV_SCNTRS_0_S_AXI_HIGHADDR 0xFF14FFFF


/******************************************************************/




/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_APU_0 */
#define XPAR_PSV_APU_0_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_PSV_APU_0_S_AXI_HIGHADDR 0xFD5CFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_STM */
#define XPAR_PSV_CORESIGHT_FPD_STM_0_S_AXI_BASEADDR 0xF0B70000
#define XPAR_PSV_CORESIGHT_FPD_STM_0_S_AXI_HIGHADDR 0xF0B7FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_CPM */
#define XPAR_PSV_CPM_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PSV_CPM_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRF_0 */
#define XPAR_PSV_CRF_0_S_AXI_BASEADDR 0xFD1A0000
#define XPAR_PSV_CRF_0_S_AXI_HIGHADDR 0xFD2DFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRL_0 */
#define XPAR_PSV_CRL_0_S_AXI_BASEADDR 0xFF5E0000
#define XPAR_PSV_CRL_0_S_AXI_HIGHADDR 0xFF8DFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_CRP_0 */
#define XPAR_PSV_CRP_0_S_AXI_BASEADDR 0xF1260000
#define XPAR_PSV_CRP_0_S_AXI_HIGHADDR 0xF126FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_AFI_0 */
#define XPAR_PSV_FPD_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_PSV_FPD_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_AFI_2 */
#define XPAR_PSV_FPD_AFI_1_S_AXI_BASEADDR 0xFD380000
#define XPAR_PSV_FPD_AFI_1_S_AXI_HIGHADDR 0xFD38FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_CCI_0 */
#define XPAR_PSV_FPD_CCI_0_S_AXI_BASEADDR 0xFD5E0000
#define XPAR_PSV_FPD_CCI_0_S_AXI_HIGHADDR 0xFD5EFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_GPV_0 */
#define XPAR_PSV_FPD_GPV_0_S_AXI_BASEADDR 0xFD700000
#define XPAR_PSV_FPD_GPV_0_S_AXI_HIGHADDR 0xFD7FFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_MAINCCI_0 */
#define XPAR_PSV_FPD_MAINCCI_0_S_AXI_BASEADDR 0xFD000000
#define XPAR_PSV_FPD_MAINCCI_0_S_AXI_HIGHADDR 0xFD0FFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLAVE_XMPU_0 */
#define XPAR_PSV_FPD_SLAVE_XMPU_0_S_AXI_BASEADDR 0xFD390000
#define XPAR_PSV_FPD_SLAVE_XMPU_0_S_AXI_HIGHADDR 0xFD39FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLCR_0 */
#define XPAR_PSV_FPD_SLCR_0_S_AXI_BASEADDR 0xFD610000
#define XPAR_PSV_FPD_SLCR_0_S_AXI_HIGHADDR 0xFD61FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SLCR_SECURE_0 */
#define XPAR_PSV_FPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFD690000
#define XPAR_PSV_FPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFD69FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SMMU_0 */
#define XPAR_PSV_FPD_SMMU_0_S_AXI_BASEADDR 0xFD5F0000
#define XPAR_PSV_FPD_SMMU_0_S_AXI_HIGHADDR 0xFD5FFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_FPD_SMMUTCU_0 */
#define XPAR_PSV_FPD_SMMUTCU_0_S_AXI_BASEADDR 0xFD800000
#define XPAR_PSV_FPD_SMMUTCU_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_AFI_0 */
#define XPAR_PSV_LPD_AFI_0_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_PSV_LPD_AFI_0_S_AXI_HIGHADDR 0xFF9BFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0 */
#define XPAR_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_BASEADDR 0xFF0A0000
#define XPAR_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_HIGHADDR 0xFF0AFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_IOU_SLCR_0 */
#define XPAR_PSV_LPD_IOU_SLCR_0_S_AXI_BASEADDR 0xFF080000
#define XPAR_PSV_LPD_IOU_SLCR_0_S_AXI_HIGHADDR 0xFF09FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_SLCR_0 */
#define XPAR_PSV_LPD_SLCR_0_S_AXI_BASEADDR 0xFF410000
#define XPAR_PSV_LPD_SLCR_0_S_AXI_HIGHADDR 0xFF50FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_SLCR_SECURE_0 */
#define XPAR_PSV_LPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFF510000
#define XPAR_PSV_LPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFF54FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_LPD_XPPU_0 */
#define XPAR_PSV_LPD_XPPU_0_S_AXI_BASEADDR 0xFF990000
#define XPAR_PSV_LPD_XPPU_0_S_AXI_HIGHADDR 0xFF99FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_CTRL */
#define XPAR_PSV_OCM_0_S_AXI_BASEADDR 0xFF960000
#define XPAR_PSV_OCM_0_S_AXI_HIGHADDR 0xFF96FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_RAM_0 */
#define XPAR_PSV_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PSV_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_OCM_XMPU_0 */
#define XPAR_PSV_OCM_XMPU_0_S_AXI_BASEADDR 0xFF980000
#define XPAR_PSV_OCM_XMPU_0_S_AXI_HIGHADDR 0xFF98FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_AES */
#define XPAR_PSV_PMC_AES_0_S_AXI_BASEADDR 0xF11E0000
#define XPAR_PSV_PMC_AES_0_S_AXI_HIGHADDR 0xF11EFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_BBRAM_CTRL */
#define XPAR_PSV_PMC_BBRAM_CTRL_0_S_AXI_BASEADDR 0xF11F0000
#define XPAR_PSV_PMC_BBRAM_CTRL_0_S_AXI_HIGHADDR 0xF11FFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CACHE */
#define XPAR_PSV_PMC_EFUSE_CACHE_0_S_AXI_BASEADDR 0xF1250000
#define XPAR_PSV_PMC_EFUSE_CACHE_0_S_AXI_HIGHADDR 0xF125FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_EFUSE_CTRL */
#define XPAR_PSV_PMC_EFUSE_CTRL_0_S_AXI_BASEADDR 0xF1240000
#define XPAR_PSV_PMC_EFUSE_CTRL_0_S_AXI_HIGHADDR 0xF124FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_GLOBAL_0 */
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_BASEADDR 0xF1110000
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_HIGHADDR 0xF115FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RAM */
#define XPAR_PSV_PMC_RAM_0_S_AXI_BASEADDR 0xF2000000
#define XPAR_PSV_PMC_RAM_0_S_AXI_HIGHADDR 0xF201FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RAM_NPI */
#define XPAR_PSV_PMC_RAM_NPI_0_S_AXI_BASEADDR 0xF6000000
#define XPAR_PSV_PMC_RAM_NPI_0_S_AXI_HIGHADDR 0xF7FFFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RSA */
#define XPAR_PSV_PMC_RSA_0_S_AXI_BASEADDR 0xF1200000
#define XPAR_PSV_PMC_RSA_0_S_AXI_HIGHADDR 0xF120FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SHA */
#define XPAR_PSV_PMC_SHA_0_S_AXI_BASEADDR 0xF1210000
#define XPAR_PSV_PMC_SHA_0_S_AXI_HIGHADDR 0xF121FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT */
#define XPAR_PSV_PMC_SLAVE_BOOT_0_S_AXI_BASEADDR 0xF1220000
#define XPAR_PSV_PMC_SLAVE_BOOT_0_S_AXI_HIGHADDR 0xF122FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_SLAVE_BOOT_STREAM */
#define XPAR_PSV_PMC_SLAVE_BOOT_STREAM_0_S_AXI_BASEADDR 0xF2100000
#define XPAR_PSV_PMC_SLAVE_BOOT_STREAM_0_S_AXI_HIGHADDR 0xF210FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XMPU_0 */
#define XPAR_PSV_PMC_XMPU_0_S_AXI_BASEADDR 0xF12F0000
#define XPAR_PSV_PMC_XMPU_0_S_AXI_HIGHADDR 0xF12FFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XPPU_0 */
#define XPAR_PSV_PMC_XPPU_0_S_AXI_BASEADDR 0xF1310000
#define XPAR_PSV_PMC_XPPU_0_S_AXI_HIGHADDR 0xF131FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_XPPU_NPI_0 */
#define XPAR_PSV_PMC_XPPU_NPI_0_S_AXI_BASEADDR 0xF1300000
#define XPAR_PSV_PMC_XPPU_NPI_0_S_AXI_HIGHADDR 0xF130FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_PSM_GLOBAL_REG */
#define XPAR_PSV_PSM_GLOBAL_REG_0_S_AXI_BASEADDR 0xFFC90000
#define XPAR_PSV_PSM_GLOBAL_REG_0_S_AXI_HIGHADDR 0xFFC9EFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_1_ATCM_GLOBAL */
#define XPAR_PSV_TCM_GLOBAL_0_S_AXI_BASEADDR 0xFFE90000
#define XPAR_PSV_TCM_GLOBAL_0_S_AXI_HIGHADDR 0xFFE9FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_1_BTCM_GLOBAL */
#define XPAR_PSV_TCM_GLOBAL_1_S_AXI_BASEADDR 0xFFEB0000
#define XPAR_PSV_TCM_GLOBAL_1_S_AXI_HIGHADDR 0xFFEBFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_R5_TCM_RAM_GLOBAL */
#define XPAR_PSV_R5_TCM_0_S_AXI_BASEADDR 0xFFE00000
#define XPAR_PSV_R5_TCM_0_S_AXI_HIGHADDR 0xFFE3FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_RPU_0 */
#define XPAR_PSV_RPU_0_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_PSV_RPU_0_S_AXI_HIGHADDR 0xFF9AFFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_SCNTR_0 */
#define XPAR_PSV_SCNTR_0_S_AXI_BASEADDR 0xFF130000
#define XPAR_PSV_SCNTR_0_S_AXI_HIGHADDR 0xFF13FFFF


/* Canonical Definitions for peripheral CIPS_0_PSPMC_0_PSV_SCNTRS_0 */
#define XPAR_PSV_SCNTRS_0_S_AXI_BASEADDR 0xFF140000
#define XPAR_PSV_SCNTRS_0_S_AXI_HIGHADDR 0xFF14FFFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_GPIO_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_GPIO_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_GPIO_0_BASEADDR 0xF1020000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_GPIO_0_HIGHADDR 0xF102FFFF


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xF1020000
#define XPAR_XGPIOPS_0_HIGHADDR 0xF102FFFF


/******************************************************************/

#define  XPAR_XIPIPSU_NUM_INSTANCES  7U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_0 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_DEVICE_ID  0U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_S_AXI_BASEADDR  0xFF330000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BIT_MASK  0x00000004U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BUFFER_INDEX  0x2U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_INT_ID  62U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_1 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_DEVICE_ID  1U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_S_AXI_BASEADDR  0xFF340000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BIT_MASK  0x00000008U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BUFFER_INDEX  0x3U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_INT_ID  63U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_2 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_DEVICE_ID  2U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_S_AXI_BASEADDR  0xFF350000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BIT_MASK  0x00000010U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BUFFER_INDEX  0x4U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_INT_ID  64U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_3 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_DEVICE_ID  3U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_S_AXI_BASEADDR  0xFF360000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_INT_ID  65U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_4 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_DEVICE_ID  4U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_S_AXI_BASEADDR  0xFF370000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_INT_ID  66U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_5 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_DEVICE_ID  5U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_S_AXI_BASEADDR  0xFF380000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BIT_MASK  0x00000080U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BUFFER_INDEX  0x7U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_INT_ID  67U

/* Parameter definitions for peripheral cips_0_pspmc_0_psv_ipi_6 */
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_DEVICE_ID  6U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_S_AXI_BASEADDR  0xFF3A0000U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BIT_MASK  0x00000200U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BUFFER_INDEX  0xFFFFU
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_INT_ID  68U

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_0 */
#define  XPAR_XIPIPSU_0_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_DEVICE_ID
#define  XPAR_XIPIPSU_0_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_0_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPSU_0_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BUFFER_INDEX
#define  XPAR_XIPIPSU_0_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_1 */
#define  XPAR_XIPIPSU_1_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_DEVICE_ID
#define  XPAR_XIPIPSU_1_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_1_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPSU_1_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BUFFER_INDEX
#define  XPAR_XIPIPSU_1_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_2 */
#define  XPAR_XIPIPSU_2_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_DEVICE_ID
#define  XPAR_XIPIPSU_2_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_2_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPSU_2_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BUFFER_INDEX
#define  XPAR_XIPIPSU_2_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_3 */
#define  XPAR_XIPIPSU_3_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_DEVICE_ID
#define  XPAR_XIPIPSU_3_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_3_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPSU_3_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BUFFER_INDEX
#define  XPAR_XIPIPSU_3_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_4 */
#define  XPAR_XIPIPSU_4_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_DEVICE_ID
#define  XPAR_XIPIPSU_4_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_4_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPSU_4_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BUFFER_INDEX
#define  XPAR_XIPIPSU_4_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_5 */
#define  XPAR_XIPIPSU_5_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_DEVICE_ID
#define  XPAR_XIPIPSU_5_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_5_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPSU_5_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BUFFER_INDEX
#define  XPAR_XIPIPSU_5_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_INT_ID

/* Canonical definitions for peripheral cips_0_pspmc_0_psv_ipi_6 */
#define  XPAR_XIPIPSU_6_DEVICE_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_DEVICE_ID
#define  XPAR_XIPIPSU_6_BASE_ADDRESS	XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_6_BIT_MASK	XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPSU_6_BUFFER_INDEX	XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BUFFER_INDEX
#define  XPAR_XIPIPSU_6_INT_ID	XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_INT_ID

#define  XPAR_XIPIPSU_NUM_TARGETS  10U

#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BIT_MASK  0x00000004U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BUFFER_INDEX  0x2U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BIT_MASK  0x00000008U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BUFFER_INDEX  0x3U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BIT_MASK  0x00000010U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BUFFER_INDEX  0x4U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BIT_MASK  0x00000080U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BUFFER_INDEX  0x7U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BIT_MASK  0x00000200U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BUFFER_INDEX  0xFFFFU
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_BIT_MASK  0x00000002U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_BUFFER_INDEX  0x1U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_NOBUF_BIT_MASK  0x00000100U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_NOBUF_BUFFER_INDEX  0xFFFFU
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PSM_BIT_MASK  0x00000001U
#define  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PSM_BUFFER_INDEX  0x0U
/* Target List for referring to processor IPI Targets */

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_INDEX  0U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_INDEX  1U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_INDEX  2U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH3_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH3_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH4_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH4_INDEX  4U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH5_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH5_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH6_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH6_INDEX  6U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_INDEX  0U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_INDEX  1U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_INDEX  2U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH3_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH3_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH4_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH4_INDEX  4U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH5_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH5_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH6_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH6_INDEX  6U



#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_INDEX  7U
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PMC_NOBUF_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_INDEX  8U

#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_MASK  XPAR_CIPS_0_PSPMC_0_PSV_IPI_PSM_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_INDEX  9U

/* Definitions for driver PMONPSV */
#define XPAR_XPMONPSV_NUM_INSTANCES 2

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_ATM */
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_ATM_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_ATM_S_AXI_BASEADDR 0xF0B80000


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_LPD_ATM */
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_LPD_ATM_DEVICE_ID 1
#define XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_LPD_ATM_S_AXI_BASEADDR 0xF0980000


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_ATM */
#define XPAR_XPMONPSV_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_FPD_ATM_DEVICE_ID
#define XPAR_XPMONPSV_0_S_AXI_BASEADDR 0xF0B80000

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_CORESIGHT_LPD_ATM */
#define XPAR_XPMONPSV_1_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_CORESIGHT_LPD_ATM_DEVICE_ID
#define XPAR_XPMONPSV_1_S_AXI_BASEADDR 0xF0980000


/******************************************************************/

/* Definitions for driver RTCPSU */
#define XPAR_XRTCPSU_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RTC_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RTC_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RTC_0_BASEADDR 0xF12A0000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_RTC_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_RTC_0 */
#define XPAR_XRTCPSU_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_RTC_0_DEVICE_ID
#define XPAR_XRTCPSU_0_BASEADDR 0xF12A0000
#define XPAR_XRTCPSU_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ACPU_GIC */
#define XPAR_CIPS_0_PSPMC_0_PSV_ACPU_GIC_DEVICE_ID 0U
#define XPAR_CIPS_0_PSPMC_0_PSV_ACPU_GIC_BASEADDR 0xF9040000U
#define XPAR_CIPS_0_PSPMC_0_PSV_ACPU_GIC_HIGHADDR 0xF9041000U
#define XPAR_CIPS_0_PSPMC_0_PSV_ACPU_GIC_DIST_BASEADDR 0xF9000000U


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ACPU_GIC */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF9040000U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF9041000U
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF9000000U


/******************************************************************/

#define XPAR_XSYSMONPSV_NUM_INSTANCES 1

/* Definitions for peripheral  */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SYSMON_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_SYSMON_0_S_AXI_HIGHADDR 0xF129FFFF


/******************************************************************/

/* Canonical definitions for peripheral  */
#define XPAR_XSYSMONPSV_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_XSYSMONPSV_0_S_AXI_HIGHADDR 0xF129FFFF

#define XPAR_XSYSMONPSV_0_NO_MEAS	161

/******************************************************************/

/* Xilinx Sysmon Device Name */

/******************************************************************/

/* Definitions for driver TRNGPSV */
#define XPAR_XTRNGPSV_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_TRNG */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_TRNG_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_TRNG_BASEADDR 0xF1230000
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_TRNG_HIGHADDR 0xF123FFFF


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_TRNG */
#define XPAR_XTRNGPSV_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_PMC_TRNG_DEVICE_ID
#define XPAR_XTRNGPSV_0_BASEADDR 0xF1230000
#define XPAR_XTRNGPSV_0_HIGHADDR 0xF123FFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1U

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_DEVICE_ID 0U
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_BASEADDR 0xF0310000U
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_HIGHADDR 0xF0317FFFU
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_BAUDRATE 0U
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_USE_PARITY 0U
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_ODD_PARITY 0U
#define XPAR_CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0_DATA_BITS 0U

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_PMC_PPU1_MDM_0 */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0xF0310000U
#define XPAR_UARTLITE_0_HIGHADDR 0xF0317FFFU
#define XPAR_UARTLITE_0_BAUDRATE 0U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 0U


/******************************************************************/
/* Definitions for driver UARTPSV */
#define XPAR_XUARTPSV_NUM_INSTANCES 1

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_SBSAUART_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_BASEADDR 0xFF000000
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_HIGHADDR 0xFF00FFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_UART_CLK_FREQ_HZ 99999901
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_HAS_MODEM 0
#define XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_BAUDRATE 115200


/******************************************************************/

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_SBSAUART_0 */
#define XPAR_XUARTPSV_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_SBSAUART_0_DEVICE_ID
#define XPAR_XUARTPSV_0_BASEADDR 0xFF000000
#define XPAR_XUARTPSV_0_HIGHADDR 0xFF00FFFF
#define XPAR_XUARTPSV_0_UART_CLK_FREQ_HZ 99999901
#define XPAR_XUARTPSV_0_HAS_MODEM 0
#define XPAR_XUARTPSV_0_BAUDRATE 115200


/******************************************************************/

/* Definitions for driver ZDMA */
#define XPAR_XZDMA_NUM_INSTANCES 8

/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_0 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_DEVICE_ID 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_BASEADDR 0xFFA80000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_1 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_DEVICE_ID 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_BASEADDR 0xFFA90000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_2 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_DEVICE_ID 2
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_BASEADDR 0xFFAA0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_3 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_DEVICE_ID 3
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_BASEADDR 0xFFAB0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_4 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_DEVICE_ID 4
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_BASEADDR 0xFFAC0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_5 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_DEVICE_ID 5
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_BASEADDR 0xFFAD0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_6 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_DEVICE_ID 6
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_BASEADDR 0xFFAE0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_7 */
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_DEVICE_ID 7
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_BASEADDR 0xFFAF0000
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_DMA_MODE 1
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_IS_CACHE_COHERENT 0
#define XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_0 */
#define XPAR_XZDMA_0_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_0_DEVICE_ID
#define XPAR_XZDMA_0_BASEADDR 0xFFA80000
#define XPAR_XZDMA_0_DMA_MODE 1
#define XPAR_XZDMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_XZDMA_0_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_1 */
#define XPAR_XZDMA_1_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_1_DEVICE_ID
#define XPAR_XZDMA_1_BASEADDR 0xFFA90000
#define XPAR_XZDMA_1_DMA_MODE 1
#define XPAR_XZDMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_XZDMA_1_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_2 */
#define XPAR_XZDMA_2_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_2_DEVICE_ID
#define XPAR_XZDMA_2_BASEADDR 0xFFAA0000
#define XPAR_XZDMA_2_DMA_MODE 1
#define XPAR_XZDMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_XZDMA_2_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_3 */
#define XPAR_XZDMA_3_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_3_DEVICE_ID
#define XPAR_XZDMA_3_BASEADDR 0xFFAB0000
#define XPAR_XZDMA_3_DMA_MODE 1
#define XPAR_XZDMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_XZDMA_3_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_4 */
#define XPAR_XZDMA_4_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_4_DEVICE_ID
#define XPAR_XZDMA_4_BASEADDR 0xFFAC0000
#define XPAR_XZDMA_4_DMA_MODE 1
#define XPAR_XZDMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_XZDMA_4_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_5 */
#define XPAR_XZDMA_5_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_5_DEVICE_ID
#define XPAR_XZDMA_5_BASEADDR 0xFFAD0000
#define XPAR_XZDMA_5_DMA_MODE 1
#define XPAR_XZDMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_XZDMA_5_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_6 */
#define XPAR_XZDMA_6_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_6_DEVICE_ID
#define XPAR_XZDMA_6_BASEADDR 0xFFAE0000
#define XPAR_XZDMA_6_DMA_MODE 1
#define XPAR_XZDMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_XZDMA_6_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral CIPS_0_PSPMC_0_PSV_ADMA_7 */
#define XPAR_XZDMA_7_DEVICE_ID XPAR_CIPS_0_PSPMC_0_PSV_ADMA_7_DEVICE_ID
#define XPAR_XZDMA_7_BASEADDR 0xFFAF0000
#define XPAR_XZDMA_7_DMA_MODE 1
#define XPAR_XZDMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_XZDMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#endif  /* end of protection macro */
