//===- AirBinding.td ---------------------------------------*- tablegen -*-===//
//
// Copyright (C) 2021-2022, Xilinx Inc.
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_AIR_OPS
#define PYTHON_BINDINGS_AIR_OPS

include "mlir/Bindings/Python/Attributes.td"
include "air/Dialect/AIR/AIR.td"

#endif // PYTHON_BINDINGS_AIR_OPS