//===- AirExtensionBinding.td ------------------------------*- tablegen -*-===//
//
// Copyright (C) 2023, Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef AIR_DIALECTS_EXTENSION_BINDING
#define AIR_DIALECTS_EXTENSION_BINDING

include "mlir/Bindings/Python/Attributes.td"
include "air/Dialect/AIR/AIRTransformOps.td"

#endif // AIR_DIALECTS_EXTENSION_BINDING
