
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E080, LENGTH = 0x1F80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf411_unroll_1 = .;
. += 0x80;
. = 0x42400;
buf410_unroll_1 = .;
. += 0x80;
. = 0x40400;
buf409_unroll_1 = .;
. += 0x2000;
. = 0x44000;
buf408_unroll_1 = .;
. += 0x2000;
. = 0x48000;
buf407_unroll_1 = .;
. += 0x2000;
. = 0x4C000;
buf406_unroll_1 = .;
. += 0x2000;
. = 0x46000;
buf405_unroll_1 = .;
. += 0x2000;
. = 0x4E080;
buf404_unroll_1 = .;
. += 0x80;
. = 0x42480;
buf403_unroll_1 = .;
. += 0x80;
. = 0x4A000;
buf402_unroll_1 = .;
. += 0x2000;
. = 0x4E100;
buf401_unroll_1 = .;
. += 0x80;
. = 0x42500;
buf400_unroll_1 = .;
. += 0x80;
. = 0x4E180;
buf399_unroll_1 = .;
. += 0x80;
. = 0x42580;
buf398_unroll_1 = .;
. += 0x80;
. = 0x4E200;
buf397_unroll_1 = .;
. += 0x80;
. = 0x42600;
buf396_unroll_1 = .;
. += 0x80;
. = 0x5A000;
buf445_unroll_1 = .;
. += 0x80;
. = 0x5E000;
buf444_unroll_1 = .;
. += 0x80;
. = 0x50400;
buf443_unroll_1 = .;
. += 0x2000;
. = 0x54000;
buf442_unroll_1 = .;
. += 0x2000;
. = 0x58000;
buf441_unroll_1 = .;
. += 0x2000;
. = 0x5C000;
buf440_unroll_1 = .;
. += 0x2000;
. = 0x56000;
buf439_unroll_1 = .;
. += 0x2000;
. = 0x52400;
buf438_unroll_1 = .;
. += 0x80;
. = 0x5A080;
buf437_unroll_1 = .;
. += 0x80;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x7A000;
buf454_unroll_1 = .;
. += 0x80;
. = 0x7E000;
buf453_unroll_1 = .;
. += 0x80;
. = 0x70400;
buf452_unroll_1 = .;
. += 0x2000;
. = 0x74000;
buf451_unroll_1 = .;
. += 0x2000;
. = 0x78000;
buf450_unroll_1 = .;
. += 0x2000;
. = 0x7C000;
buf449_unroll_1 = .;
. += 0x2000;
. = 0x76000;
buf448_unroll_1 = .;
. += 0x2000;
. = 0x72400;
buf447_unroll_1 = .;
. += 0x80;
. = 0x7A080;
buf446_unroll_1 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_4h/attn.o)
PROVIDE(main = core_6_5);
