
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E280, LENGTH = 0x1D80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x5E000;
buf15_unroll_0 = .;
. += 0x80;
. = 0x52400;
buf14_unroll_0 = .;
. += 0x80;
. = 0x50400;
buf13_unroll_0 = .;
. += 0x2000;
. = 0x54000;
buf12_unroll_0 = .;
. += 0x2000;
. = 0x58000;
buf11_unroll_0 = .;
. += 0x2000;
. = 0x5C000;
buf10_unroll_0 = .;
. += 0x2000;
. = 0x56000;
buf9_unroll_0 = .;
. += 0x2000;
. = 0x5E080;
buf8_unroll_0 = .;
. += 0x80;
. = 0x52480;
buf7_unroll_0 = .;
. += 0x80;
. = 0x5A000;
buf6_unroll_0 = .;
. += 0x2000;
. = 0x5E100;
buf5_unroll_0 = .;
. += 0x80;
. = 0x52500;
buf4_unroll_0 = .;
. += 0x80;
. = 0x5E180;
buf3_unroll_0 = .;
. += 0x80;
. = 0x52580;
buf2_unroll_0 = .;
. += 0x80;
. = 0x5E200;
buf1_unroll_0 = .;
. += 0x80;
. = 0x52600;
buf0_unroll_0 = .;
. += 0x80;
. = 0x6E000;
buf95_unroll_0 = .;
. += 0x80;
. = 0x62400;
buf94_unroll_0 = .;
. += 0x80;
. = 0x60400;
buf93_unroll_0 = .;
. += 0x2000;
. = 0x64000;
buf92_unroll_0 = .;
. += 0x2000;
. = 0x68000;
buf91_unroll_0 = .;
. += 0x2000;
. = 0x6C000;
buf90_unroll_0 = .;
. += 0x2000;
. = 0x66000;
buf89_unroll_0 = .;
. += 0x2000;
. = 0x6E080;
buf88_unroll_0 = .;
. += 0x80;
. = 0x62480;
buf87_unroll_0 = .;
. += 0x80;
. = 0x6A000;
buf86_unroll_0 = .;
. += 0x2000;
. = 0x6E100;
buf85_unroll_0 = .;
. += 0x80;
. = 0x62500;
buf84_unroll_0 = .;
. += 0x80;
. = 0x6E180;
buf83_unroll_0 = .;
. += 0x80;
. = 0x62580;
buf82_unroll_0 = .;
. += 0x80;
. = 0x6E200;
buf81_unroll_0 = .;
. += 0x80;
. = 0x62600;
buf80_unroll_0 = .;
. += 0x80;
. = 0x7E000;
buf31_unroll_0 = .;
. += 0x80;
. = 0x72400;
buf30_unroll_0 = .;
. += 0x80;
. = 0x70400;
buf29_unroll_0 = .;
. += 0x2000;
. = 0x74000;
buf28_unroll_0 = .;
. += 0x2000;
. = 0x78000;
buf27_unroll_0 = .;
. += 0x2000;
. = 0x7C000;
buf26_unroll_0 = .;
. += 0x2000;
. = 0x76000;
buf25_unroll_0 = .;
. += 0x2000;
. = 0x7E080;
buf24_unroll_0 = .;
. += 0x80;
. = 0x72480;
buf23_unroll_0 = .;
. += 0x80;
. = 0x7A000;
buf22_unroll_0 = .;
. += 0x2000;
. = 0x7E100;
buf21_unroll_0 = .;
. += 0x80;
. = 0x72500;
buf20_unroll_0 = .;
. += 0x80;
. = 0x7E180;
buf19_unroll_0 = .;
. += 0x80;
. = 0x72580;
buf18_unroll_0 = .;
. += 0x80;
. = 0x7E200;
buf17_unroll_0 = .;
. += 0x80;
. = 0x72600;
buf16_unroll_0 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_4h/attn.o)
PROVIDE(main = core_1_2);
