
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E080, LENGTH = 0x1F80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf395_unroll_1 = .;
. += 0x80;
. = 0x42400;
buf394_unroll_1 = .;
. += 0x80;
. = 0x40400;
buf393_unroll_1 = .;
. += 0x2000;
. = 0x44000;
buf392_unroll_1 = .;
. += 0x2000;
. = 0x48000;
buf391_unroll_1 = .;
. += 0x2000;
. = 0x4C000;
buf390_unroll_1 = .;
. += 0x2000;
. = 0x46000;
buf389_unroll_1 = .;
. += 0x2000;
. = 0x4E080;
buf388_unroll_1 = .;
. += 0x80;
. = 0x42480;
buf387_unroll_1 = .;
. += 0x80;
. = 0x4A000;
buf386_unroll_1 = .;
. += 0x2000;
. = 0x4E100;
buf385_unroll_1 = .;
. += 0x80;
. = 0x42500;
buf384_unroll_1 = .;
. += 0x80;
. = 0x4E180;
buf383_unroll_1 = .;
. += 0x80;
. = 0x42580;
buf382_unroll_1 = .;
. += 0x80;
. = 0x4E200;
buf381_unroll_1 = .;
. += 0x80;
. = 0x42600;
buf380_unroll_1 = .;
. += 0x80;
. = 0x5A000;
buf436_unroll_1 = .;
. += 0x80;
. = 0x5E000;
buf435_unroll_1 = .;
. += 0x80;
. = 0x50400;
buf434_unroll_1 = .;
. += 0x2000;
. = 0x54000;
buf433_unroll_1 = .;
. += 0x2000;
. = 0x58000;
buf432_unroll_1 = .;
. += 0x2000;
. = 0x5C000;
buf431_unroll_1 = .;
. += 0x2000;
. = 0x56000;
buf430_unroll_1 = .;
. += 0x2000;
. = 0x52400;
buf429_unroll_1 = .;
. += 0x80;
. = 0x5A080;
buf428_unroll_1 = .;
. += 0x80;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x7A000;
buf445_unroll_1 = .;
. += 0x80;
. = 0x7E000;
buf444_unroll_1 = .;
. += 0x80;
. = 0x70400;
buf443_unroll_1 = .;
. += 0x2000;
. = 0x74000;
buf442_unroll_1 = .;
. += 0x2000;
. = 0x78000;
buf441_unroll_1 = .;
. += 0x2000;
. = 0x7C000;
buf440_unroll_1 = .;
. += 0x2000;
. = 0x76000;
buf439_unroll_1 = .;
. += 0x2000;
. = 0x72400;
buf438_unroll_1 = .;
. += 0x80;
. = 0x7A080;
buf437_unroll_1 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_4h/attn.o)
PROVIDE(main = core_5_5);
