//===- air_host_impl.h -----------------------------------------*- C++ -*-===//
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
//===----------------------------------------------------------------------===//

#ifndef AIR_HOST_IMPL_H
#define AIR_HOST_IMPL_H

#include "test_library.h"

typedef struct air_physical_device_s {
  char aie_bar_path[128];
  uint64_t aie_bar_size;
  char dram_bar_path[128];
  uint64_t dram_bar_size;
  char bram_bar_path[128];
  uint64_t bram_bar_size;
} air_physical_device_t;

typedef struct air_dev_mem_allocator_s {
  void *dev_mem;
  uint64_t dev_mem_ptr;
  uint64_t dev_mem_size;
} air_dev_mem_allocator_t;

// AIE config functions generated by AIE dialect lowering
struct air_rt_aie_functions_t {
  void (*configure_cores)(aie_libxaie_ctx_t *);
  void (*configure_switchboxes)(aie_libxaie_ctx_t *);
  void (*initialize_locks)(aie_libxaie_ctx_t *);
  void (*configure_dmas)(aie_libxaie_ctx_t *);
  void (*start_cores)(aie_libxaie_ctx_t *);
};

#endif