//===- air_host_impl.h -----------------------------------------*- C++ -*-===//
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef AIR_HOST_IMPL_H
#define AIR_HOST_IMPL_H

#include "test_library.h"

// AIE config functions generated by AIE dialect lowering
struct air_rt_aie_functions_t {
  int (*configure_cores)(aie_libxaie_ctx_t *);
  int (*configure_switchboxes)(aie_libxaie_ctx_t *);
  int (*initialize_locks)(aie_libxaie_ctx_t *);
  int (*configure_dmas)(aie_libxaie_ctx_t *);
  int (*start_cores)(aie_libxaie_ctx_t *);
};

/*
        Get the name of the device driver

        Use this to device to map various device memory regions into the host
   address space
*/
const char *air_get_driver_name(void);

#endif
