//===- air_host_impl.h -----------------------------------------*- C++ -*-===//
//
// Copyright (C) 2022, Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

#ifndef AIR_HOST_IMPL_H
#define AIR_HOST_IMPL_H

#include "test_library.h"

typedef struct air_physical_device_s {
  char aie_bar_path[128];
  uint64_t aie_bar_size;
  char dram_bar_path[128];
  uint64_t dram_bar_size;
  char bram_bar_path[128];
  uint64_t bram_bar_size;
} air_physical_device_t;

typedef struct air_dev_mem_allocator_s {
  void *dev_mem;
  uint64_t dev_mem_ptr;
  uint64_t dev_mem_size;
} air_dev_mem_allocator_t;

// AIE config functions generated by AIE dialect lowering
struct air_rt_aie_functions_t {
  void (*configure_cores)(aie_libxaie_ctx_t *);
  void (*configure_switchboxes)(aie_libxaie_ctx_t *);
  void (*initialize_locks)(aie_libxaie_ctx_t *);
  void (*configure_dmas)(aie_libxaie_ctx_t *);
  void (*start_cores)(aie_libxaie_ctx_t *);
};

#endif