#!/usr/bin/env python3
"""Emit a megakernel decode chain as AIR MLIR.

Qwen has 36 layers of several stages each. Nobody writes that by hand, and the
hand-written tests next to this one stop being a plan the moment the layer
count stops being 2. Fleet has the same problem and solves it the same way: its
task graph is described in Python and `src/kernel/runtime.cc` prints the C++.
This prints MLIR instead.

What a layer is here:

    r = x / sqrt(mean(x^2) + eps)     one task, a reduction
    h = r @ W1                        `tasks` tasks, one per slice of h
    y = relu(h) @ W2                  `tasks` tasks, reads all of h
    x = y                             carried to the next layer

Every stage boundary is an event, and the whole chain is one launch. The stage
structure is what scales: adding a layer adds queue slots and event slots, not
a kernel launch.

With --tokens M > 1 the chain runs M tokens at once, which is what a prefill or
a speculative window looks like: the M tokens attend a shared KV prefix (they
are not in each other's cache, so there is no mask among them) and every linear
stage becomes an (m, n) grid rather than a row of n. The traversal of that grid
is Fleet's, and it is the reason M > 1 is not just a bigger loop -- see
strided_stage below. At M = 1 the decomposition collapses to exactly the
index arithmetic this generator used before --tokens existed, so the decode
numbers stay comparable.

    ./gen.py --layers 4 --dim 128 > chain.mlir
    ./gen.py --layers 2 --dim 128 --tokens 4 > prefill.mlir
"""

import argparse
import math as _math
import sys


def emit(layers: int, dim: int, tasks: int, workers: int, repeat: int = 1,
         cache: int = 32, tokens: int = 1) -> str:
    assert dim % tasks == 0, "dim must divide evenly into tasks"
    slice_w = dim // tasks
    # Activations carry a token dimension; weights and the KV cache do not.
    # That asymmetry is the whole reason M > 1 changes the traversal: a weight
    # block is worth reading once and using `tokens` times.
    AT = f"memref<{tokens}x{dim}xf32>"
    ST = f"memref<{tokens}x{cache}xf32>"
    invsqrtd = dim ** -0.5
    # Weight magnitude. Small enough that relu(xa @ W1) @ W2 does not dominate
    # the residual it is added to; see the centring note where the weights are
    # built.
    wscale = 0.0625
    # Per layer: one event for the reduction, one for each of the two matmul
    # stages, and one for the carry.
    # Per layer: rmsnorm, q proj, scores, softmax, attn-weighted V, the
    # attention residual and pre-MLP norm, the two MLP matmuls, then the
    # residual carry.
    stages = 9
    events = stages * layers
    # A head per die per stage. The die count is not known until the program
    # runs, so allocate for more dies than any current part has and let the
    # unused heads sit at zero.
    maxdies = 16
    qslots = stages * maxdies
    # accumulate + arrivals per (layer, stage, die), then one word for flushes
    slots = layers * stages * maxdies
    flushword = 2 * slots
    locwords = flushword + 1
    # Only the multi-task stages signal per worker; the four single-task
    # ones are claimed by one workgroup and already signal once.
    strided_stages = 5  # stages 1, 2, 4, 6, 7
    naive = workers * strided_stages * layers
    o = []
    w = o.append

    w(f"""// Generated by test/gpu/megakernel_gen/gen.py -- do not edit.
//   layers={layers} dim={dim} tasks/stage={tasks} workers={workers}
//
// A decode chain as a megakernel: one launch, {layers} layers, every stage
// boundary an event rather than a return to the host.
module {{
  func.func @main() {{
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %cdim = arith.constant {dim} : index
    %zero = arith.constant 0 : i32
    %one = arith.constant 1 : i32
    %fzero = arith.constant 0.0 : f32
    %eps = arith.constant 1.0e-6 : f32
    %fdim = arith.constant {float(dim):.6e} : f32
    %c1f = arith.constant 1.0 : f32
    %c2f = arith.constant 2.0 : f32
    %c3f = arith.constant 3.0 : f32
    %c5f = arith.constant 5.0 : f32
    %c7f = arith.constant 7.0 : f32
    %scale = arith.constant 1.250000e-01 : f32
    %wscale = arith.constant {wscale:.8e} : f32
    %clayers = arith.constant {layers} : index
    %ctok = arith.constant {tokens} : index

    %X = memref.alloc() : {AT}
    %X0 = memref.alloc() : {AT}
    %W1 = memref.alloc() : memref<{layers}x{dim}x{dim}xf32>
    %W2 = memref.alloc() : memref<{layers}x{dim}x{dim}xf32>
    %Wq = memref.alloc() : memref<{layers}x{dim}x{dim}xf32>
    %Kc = memref.alloc() : memref<{layers}x{cache}x{dim}xf32>
    %Vc = memref.alloc() : memref<{layers}x{cache}x{dim}xf32>
    %Qv = memref.alloc() : {AT}
    %Sv = memref.alloc() : {ST}
    %Pv = memref.alloc() : {ST}
    %Av = memref.alloc() : {AT}
    %Xa = memref.alloc() : {AT}
    %R = memref.alloc() : {AT}
    %H = memref.alloc() : {AT}
    %Y = memref.alloc() : {AT}
    %ref = memref.alloc() : {AT}
    %refh = memref.alloc() : memref<{dim}xf32>

    // Each token gets a different *pattern*, not the same pattern shifted by a
    // constant. A constant offset does not survive: rmsnorm divides most of it
    // out, so the queries come out within a few percent of each other, the
    // attention outputs within 0.04%, and a token reading another token's
    // scores is then indistinguishable from correct. 3i + 7m mod 5 gives each
    // token a different rotation of the same values.
    scf.for %m = %c0 to %ctok step %c1 {{
      scf.for %i = %c0 to %cdim step %c1 {{
        %ii = arith.index_cast %i : index to i32
        %fi = arith.sitofp %ii : i32 to f32
        %mm = arith.index_cast %m : index to i32
        %fm = arith.sitofp %mm : i32 to f32
        %fi3 = arith.mulf %fi, %c3f : f32
        %fm7 = arith.mulf %fm, %c7f : f32
        %fim = arith.addf %fi3, %fm7 : f32
        %v0 = arith.remf %fim, %c5f : f32
        %v = arith.mulf %v0, %scale : f32
        %v2 = arith.addf %v, %scale : f32
        memref.store %v2, %X[%m, %i] : {AT}
        memref.store %v2, %X0[%m, %i] : {AT}
        memref.store %v2, %ref[%m, %i] : {AT}
        memref.store %fzero, %R[%m, %i] : {AT}
        memref.store %fzero, %H[%m, %i] : {AT}
        memref.store %fzero, %Y[%m, %i] : {AT}
        memref.store %fzero, %Qv[%m, %i] : {AT}
        memref.store %fzero, %Av[%m, %i] : {AT}
        memref.store %fzero, %Xa[%m, %i] : {AT}
      }}
    }}

    scf.for %i = %c0 to %cdim step %c1 {{
      %ii = arith.index_cast %i : index to i32
      %fi = arith.sitofp %ii : i32 to f32
      scf.for %l = %c0 to %clayers step %c1 {{
        scf.for %j = %c0 to %cdim step %c1 {{
          %jj = arith.index_cast %j : index to i32
          %fj = arith.sitofp %jj : i32 to f32
          %ll = arith.index_cast %l : index to i32
          %fl = arith.sitofp %ll : i32 to f32
          // Centred. x % 5 lands in [0, 5), so an uncentred weight matrix is
          // entirely non-negative and a matmul over `dim` of them is a sum of
          // non-negative terms rather than a random walk -- a gain of
          // ~dim*mean(W) per matmul, which ran the residual stream up to 1e4
          // by two layers and 1e71 by thirty-six. The tolerance below is
          // relative, so at that magnitude it admitted absolute errors in the
          // hundreds and the comparison stopped being a comparison.
          %d = arith.subf %fi, %fj : f32
          %d2 = arith.addf %d, %fl : f32
          %ww0 = arith.remf %d2, %c5f : f32
          %ww = arith.subf %ww0, %c2f : f32
          %wn = arith.mulf %ww, %wscale : f32
          memref.store %wn, %W1[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %w3 = arith.addf %d2, %c3f : f32
          %w40 = arith.remf %w3, %c5f : f32
          %w4 = arith.subf %w40, %c2f : f32
          %wn2 = arith.mulf %w4, %wscale : f32
          memref.store %wn2, %W2[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %wq0 = arith.addf %d2, %scale : f32
          %wq10 = arith.remf %wq0, %c3f : f32
          %wq1 = arith.subf %wq10, %c1f : f32
          %wq2 = arith.mulf %wq1, %scale : f32
          memref.store %wq2, %Wq[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
        }}
      }}
    }}

    // A warm KV cache. Decode reads it; this test does not grow it.
    %ccache = arith.constant {cache} : index
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %t = %c0 to %ccache step %c1 {{
        scf.for %i = %c0 to %cdim step %c1 {{
          %tt = arith.index_cast %t : index to i32
          %ii2 = arith.index_cast %i : index to i32
          %ll2 = arith.index_cast %l : index to i32
          %ft = arith.sitofp %tt : i32 to f32
          %fi2 = arith.sitofp %ii2 : i32 to f32
          %fl2 = arith.sitofp %ll2 : i32 to f32
          %ks = arith.addf %ft, %fi2 : f32
          %ks2 = arith.addf %ks, %fl2 : f32
          // Not centred, unlike the weight matrices below, because for K it
          // would change nothing: a constant added to every K entry adds a
          // t-independent constant to every score, and softmax is invariant
          // to that.
          %kr = arith.remf %ks2, %c5f : f32
          %kn = arith.mulf %kr, %scale : f32
          memref.store %kn, %Kc[%l, %t, %i] : memref<{layers}x{cache}x{dim}xf32>
          %vs = arith.subf %ft, %fi2 : f32
          %vr = arith.remf %vs, %c3f : f32
          %vn = arith.mulf %vr, %scale : f32
          memref.store %vn, %Vc[%l, %t, %i] : memref<{layers}x{cache}x{dim}xf32>
        }}
      }}
    }}
    scf.for %m = %c0 to %ctok step %c1 {{
      scf.for %t = %c0 to %ccache step %c1 {{
        memref.store %fzero, %Sv[%m, %t] : {ST}
        memref.store %fzero, %Pv[%m, %t] : {ST}
      }}
    }}

    // Reference for the whole chain, on the host.
    %invsqrtd = arith.constant {invsqrtd:.8e} : f32
    %negbig = arith.constant -1.000000e30 : f32
    %refs = memref.alloc() : memref<{cache}xf32>
    %refa = memref.alloc() : memref<{dim}xf32>
    %refq = memref.alloc() : memref<{dim}xf32>
    scf.for %l = %c0 to %clayers step %c1 {{
     scf.for %m = %c0 to %ctok step %c1 {{
      // rmsnorm
      %ss = scf.for %i = %c0 to %cdim step %c1
          iter_args(%s = %fzero) -> (f32) {{
        %v = memref.load %ref[%m, %i] : {AT}
        %sq = arith.mulf %v, %v : f32
        %s2 = arith.addf %s, %sq : f32
        scf.yield %s2 : f32
      }}
      %mean = arith.divf %ss, %fdim : f32
      %me = arith.addf %mean, %eps : f32
      %rms = math.sqrt %me : f32
      // q = r @ Wq
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %xv = memref.load %ref[%m, %i] : {AT}
          %rv = arith.divf %xv, %rms : f32
          %wv = memref.load %Wq[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %mu = arith.mulf %rv, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refq[%j] : memref<{dim}xf32>
      }}
      // scores, softmax
      scf.for %t = %c0 to %ccache step %c1 {{
        %dot = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %qv = memref.load %refq[%i] : memref<{dim}xf32>
          %kv = memref.load %Kc[%l, %t, %i] : memref<{layers}x{cache}x{dim}xf32>
          %mu = arith.mulf %qv, %kv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        %sc = arith.mulf %dot, %invsqrtd : f32
        memref.store %sc, %refs[%t] : memref<{cache}xf32>
      }}
      %mx = scf.for %t = %c0 to %ccache step %c1
          iter_args(%mv = %negbig) -> (f32) {{
        %v = memref.load %refs[%t] : memref<{cache}xf32>
        %m2 = arith.maxnumf %mv, %v : f32
        scf.yield %m2 : f32
      }}
      %sum = scf.for %t = %c0 to %ccache step %c1
          iter_args(%sm = %fzero) -> (f32) {{
        %v = memref.load %refs[%t] : memref<{cache}xf32>
        %d = arith.subf %v, %mx : f32
        %e = math.exp %d : f32
        memref.store %e, %refs[%t] : memref<{cache}xf32>
        %s2 = arith.addf %sm, %e : f32
        scf.yield %s2 : f32
      }}
      // a = p @ V
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %t = %c0 to %ccache step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %e = memref.load %refs[%t] : memref<{cache}xf32>
          %pp = arith.divf %e, %sum : f32
          %vv = memref.load %Vc[%l, %t, %j] : memref<{layers}x{cache}x{dim}xf32>
          %mu = arith.mulf %pp, %vv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refa[%j] : memref<{dim}xf32>
      }}
      // residual around attention, then the norm the MLP reads:
      // xa = rmsnorm(x + a)
      %ssa = scf.for %j = %c0 to %cdim step %c1
          iter_args(%s = %fzero) -> (f32) {{
        %xv2 = memref.load %ref[%m, %j] : {AT}
        %avv = memref.load %refa[%j] : memref<{dim}xf32>
        %xa = arith.addf %xv2, %avv : f32
        memref.store %xa, %Xa[%m, %j] : {AT}
        %sqa = arith.mulf %xa, %xa : f32
        %s2 = arith.addf %s, %sqa : f32
        scf.yield %s2 : f32
      }}
      %meana = arith.divf %ssa, %fdim : f32
      %mea = arith.addf %meana, %eps : f32
      %rmsa = math.sqrt %mea : f32
      scf.for %j = %c0 to %cdim step %c1 {{
        %xv3 = memref.load %Xa[%m, %j] : {AT}
        %xn = arith.divf %xv3, %rmsa : f32
        memref.store %xn, %Xa[%m, %j] : {AT}
      }}
      // h = xa @ W1
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %av = memref.load %Xa[%m, %i] : {AT}
          %wv = memref.load %W1[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %mu = arith.mulf %av, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refh[%j] : memref<{dim}xf32>
      }}
      // y = relu(h) @ W2
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %hv = memref.load %refh[%i] : memref<{dim}xf32>
          %rl = arith.maxnumf %hv, %fzero : f32
          %wv = memref.load %W2[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %mu = arith.mulf %rl, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %Y[%m, %j] : {AT}
      }}
      // residual around the MLP: x = xa + y
      scf.for %j = %c0 to %cdim step %c1 {{
        %xav = memref.load %Xa[%m, %j] : {AT}
        %yv = memref.load %Y[%m, %j] : {AT}
        %nx = arith.addf %xav, %yv : f32
        memref.store %nx, %ref[%m, %j] : {AT}
      }}
     }}
    }}
    scf.for %m = %c0 to %ctok step %c1 {{
      scf.for %i = %c0 to %cdim step %c1 {{
        memref.store %fzero, %Y[%m, %i] : {AT}
        memref.store %fzero, %Xa[%m, %i] : {AT}
      }}
    }}

    // Queues and events, sized by the chain rather than hand-counted.
    %Q = memref.alloc() : memref<{layers}x{qslots}xi32>
    %cq = arith.constant {qslots} : index
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %k = %c0 to %cq step %c1 {{
        memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
      }}
    }}
    // Two-level event counting (persistent_kernel.cuh:1226-1251): workers add
    // into a counter only their own die touches, and the last one out flushes
    // the die's whole share to the device counter. Slots per (layer, stage,
    // die): the running total, then how many workers have finished, then one
    // word counting flushes so the host can see how many device-scope atomics
    // actually happened.
    %Loc = memref.alloc() : memref<{locwords}xi32>
    %cloc = arith.constant {locwords} : index
    scf.for %i = %c0 to %cloc step %c1 {{
      memref.store %zero, %Loc[%i] : memref<{locwords}xi32>
    }}
    %E = memref.alloc() : memref<{events}xi32>
    %ce = arith.constant {events} : index
    scf.for %i = %c0 to %ce step %c1 {{
      memref.store %zero, %E[%i] : memref<{events}xi32>
    }}

    %dX = gpu.alloc () : {AT}
    %dR = gpu.alloc () : {AT}
    %dH = gpu.alloc () : {AT}
    %dY = gpu.alloc () : {AT}
    %dWq = gpu.alloc () : memref<{layers}x{dim}x{dim}xf32>
    %dKc = gpu.alloc () : memref<{layers}x{cache}x{dim}xf32>
    %dVc = gpu.alloc () : memref<{layers}x{cache}x{dim}xf32>
    %dQv = gpu.alloc () : {AT}
    %dSv = gpu.alloc () : {ST}
    %dPv = gpu.alloc () : {ST}
    %dAv = gpu.alloc () : {AT}
    %dXa = gpu.alloc () : {AT}
    %dW1 = gpu.alloc () : memref<{layers}x{dim}x{dim}xf32>
    %dW2 = gpu.alloc () : memref<{layers}x{dim}x{dim}xf32>
    %dQ = gpu.alloc () : memref<{layers}x{qslots}xi32>
    %dLoc = gpu.alloc () : memref<{locwords}xi32>
    %dE = gpu.alloc () : memref<{events}xi32>
    gpu.memcpy %dX, %X : {AT}, {AT}
    gpu.memcpy %dR, %R : {AT}, {AT}
    gpu.memcpy %dH, %H : {AT}, {AT}
    gpu.memcpy %dY, %Y : {AT}, {AT}
    gpu.memcpy %dWq, %Wq : memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>
    gpu.memcpy %dKc, %Kc : memref<{layers}x{cache}x{dim}xf32>, memref<{layers}x{cache}x{dim}xf32>
    gpu.memcpy %dVc, %Vc : memref<{layers}x{cache}x{dim}xf32>, memref<{layers}x{cache}x{dim}xf32>
    gpu.memcpy %dQv, %Qv : {AT}, {AT}
    gpu.memcpy %dSv, %Sv : {ST}, {ST}
    gpu.memcpy %dPv, %Pv : {ST}, {ST}
    gpu.memcpy %dAv, %Av : {AT}, {AT}
    gpu.memcpy %dXa, %Xa : {AT}, {AT}
    gpu.memcpy %dW1, %W1 : memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>
    gpu.memcpy %dW2, %W2 : memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>
    gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
    gpu.memcpy %dLoc, %Loc : memref<{locwords}xi32>, memref<{locwords}xi32>
    gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>

    // --repeat runs the chain more than once so an external clock has
    // something to measure. Timing it from inside with mgpuEventRecord does not
    // work: the events go on the stream created here, while gpu-to-llvm puts
    // the kernel on one of its own, so the elapsed time is between two events
    // on an idle stream -- mgpuEventElapsedTime returns hipErrorInvalidHandle
    // and the number is garbage. The 4k GEMM test has the same problem.
    %crep = arith.constant {repeat} : index
    scf.for %rep = %c0 to %crep step %c1 {{
      // Re-arm the queues and events so each repetition is a fresh chain.
      scf.for %l = %c0 to %clayers step %c1 {{
        scf.for %k = %c0 to %cq step %c1 {{
          memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
        }}
      }}
      scf.for %i = %c0 to %ce step %c1 {{
        memref.store %zero, %E[%i] : memref<{events}xi32>
      }}
      scf.for %i = %c0 to %cloc step %c1 {{
        memref.store %zero, %Loc[%i] : memref<{locwords}xi32>
      }}
      gpu.memcpy %dLoc, %Loc : memref<{locwords}xi32>, memref<{locwords}xi32>
      gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
      gpu.memcpy %dLoc, %Loc : memref<{locwords}xi32>, memref<{locwords}xi32>
    gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>
      // The chain rewrites x in place, so a second repetition would start from
      // the first one's output rather than the input.
      gpu.memcpy %dX, %X0 : {AT}, {AT}
      func.call @chain(%dQ, %dE, %dX, %dR, %dH, %dY, %dW1, %dW2,
                       %dWq, %dKc, %dVc, %dQv, %dSv, %dPv, %dAv, %dXa, %dLoc)
        : (memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT},
           {AT}, {AT}, {AT},
           memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>,
           memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{cache}x{dim}xf32>,
           memref<{layers}x{cache}x{dim}xf32>, {AT},
           {ST}, {ST}, {AT},
           {AT}, memref<{locwords}xi32>) -> ()
    }}

    gpu.memcpy %X, %dX : {AT}, {AT}

    %tol = arith.constant 2.0e-2 : f32
    %fone = arith.constant 1.0 : f32
    %bad = scf.for %m = %c0 to %ctok step %c1
        iter_args(%bo = %zero) -> (i32) {{
      %bi = scf.for %i = %c0 to %cdim step %c1
          iter_args(%b = %bo) -> (i32) {{
        %got = memref.load %X[%m, %i] : {AT}
        %want = memref.load %ref[%m, %i] : {AT}
        %d = arith.subf %got, %want : f32
        %ad = math.absf %d : f32
        %aw = math.absf %want : f32
        %sc = arith.maxnumf %aw, %fone : f32
        %rel = arith.divf %ad, %sc : f32
        %ok = arith.cmpf ole, %rel, %tol : f32
        %inc = arith.select %ok, %zero, %one : i32
        %b2 = arith.addi %b, %inc : i32
        scf.yield %b2 : i32
      }}
      scf.yield %bi : i32
    }}
    vector.print str "layers = "
    %nl = arith.constant {layers} : i32
    vector.print %nl : i32
    vector.print str "tokens = "
    %ntk = arith.constant {tokens} : i32
    vector.print %ntk : i32
    gpu.memcpy %Loc, %dLoc : memref<{locwords}xi32>, memref<{locwords}xi32>
    %cflush = arith.constant {flushword} : index
    %flushes = memref.load %Loc[%cflush] : memref<{locwords}xi32>
    vector.print str "device-scope event flushes = "
    vector.print %flushes : i32
    %cnaive = arith.constant {naive} : i32
    vector.print str "what signalling per worker would have been = "
    vector.print %cnaive : i32
    vector.print str "output elements differing from the reference = "
    vector.print %bad : i32
    return
  }}
""")

    layer_consts = "\n".join(
        f"        %L{i} = arith.constant {i} : index" for i in range(layers))
    w(f"""
  func.func @chain(%Q: memref<{layers}x{qslots}xi32>, %E: memref<{events}xi32>,
                   %X: {AT}, %Rv: {AT},
                   %Hv: {AT}, %Yv: {AT},
                   %W1: memref<{layers}x{dim}x{dim}xf32>, %W2: memref<{layers}x{dim}x{dim}xf32>,
                   %Wq: memref<{layers}x{dim}x{dim}xf32>,
                   %Kc: memref<{layers}x{cache}x{dim}xf32>,
                   %Vc: memref<{layers}x{cache}x{dim}xf32>,
                   %Qv: {AT}, %Sv: {ST},
                   %Pv: {ST}, %Av: {AT},
                   %Xa: {AT}, %Loc: memref<{locwords}xi32>) {{
    %c1 = arith.constant 1 : index
    %cw = arith.constant {workers} : index
    air.launch (%bx, %by) in (%nbx=%cw, %nby=%c1)
        args(%q=%Q, %eb=%E, %x=%X, %r=%Rv, %h=%Hv, %y=%Yv, %w1=%W1, %w2=%W2,
             %wq=%Wq, %kc=%Kc, %vc=%Vc, %qv=%Qv, %sv=%Sv, %pv=%Pv, %av=%Av, %xab=%Xa, %loc=%Loc)
        : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT},
          {AT}, {AT}, {AT},
          memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>,
          memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{cache}x{dim}xf32>,
          memref<{layers}x{cache}x{dim}xf32>, {AT},
          {ST}, {ST}, {AT},
          {AT}, memref<{locwords}xi32> {{
      air.segment @worker args(%sq=%q, %se=%eb, %sx=%x, %sr=%r, %sh=%h, %sy=%y, %sw1=%w1, %sw2=%w2,
                               %swq=%wq, %skc=%kc, %svc=%vc, %sqv=%qv, %ssv=%sv, %spv=%pv, %sav=%av, %sxa=%xab, %sloc=%loc)
          : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT},
            {AT}, {AT}, {AT},
            memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>,
            memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{cache}x{dim}xf32>,
            memref<{layers}x{cache}x{dim}xf32>, {AT},
            {ST}, {ST}, {AT},
          {AT}, memref<{locwords}xi32> {{
        %c0_s = arith.constant 0 : index
        %c1_s = arith.constant 1 : index
        %c2_s = arith.constant 2 : index
        %c3_s = arith.constant 3 : index
        %ctasks = arith.constant {tasks} : index
        %cslice = arith.constant {slice_w} : index
        %cdim_s = arith.constant {dim} : index
        %one_s = arith.constant 1 : i32
        %zero_s = arith.constant 0 : i32
        %ntasks = arith.constant {tasks} : i32
        %ctok_s = arith.constant {tokens} : index
        // A stage's pieces are the (token, n-slice) grid, so the event it
        // signals counts tokens * slices.
        %ntasks_t = arith.constant {tokens * tasks} : i32
        %ncache_t = arith.constant {tokens * cache} : i32
        %n1 = arith.constant 1 : i32
        %fzero_s = arith.constant 0.0 : f32
        %eps_s = arith.constant 1.0e-6 : f32
        %fdim_s = arith.constant {float(dim):.6e} : f32
        %invsqrtd_s = arith.constant {invsqrtd:.8e} : f32
        %negbig_s = arith.constant -1.000000e30 : f32
        %ccache_s = arith.constant {cache} : index
        %ncache = arith.constant {cache} : i32
        %c4_s = arith.constant 4 : index
        %c5_s = arith.constant 5 : index
        %c6_s = arith.constant 6 : index
        %c7_s = arith.constant 7 : index
        %c8_s = arith.constant 8 : index
        %true = arith.constant true

        %tx_s = gpu.thread_id x
        %ty_s = gpu.thread_id y
        %tz_s = gpu.thread_id z
        %t01 = arith.ori %tx_s, %ty_s : index
        %t012 = arith.ori %t01, %tz_s : index
        %isLead = arith.cmpi eq, %t012, %c0_s : index
        // Which die this workgroup is on. Work is claimed per die so that the
        // slices a die computes are the ones its own cache is holding.
        %mydie_raw = air.chiplet_id
        %cmaxdies = arith.constant {maxdies} : index
        %mydie = arith.remui %mydie_raw, %cmaxdies : index
{layer_consts}
        %locbase = memref.extract_aligned_pointer_as_index %sloc : memref<{locwords}xi32> -> index
        %locbi = arith.index_cast %locbase : index to i64
        %locp = llvm.inttoptr %locbi : i64 to !llvm.ptr
        %fourL = arith.constant 4 : i64
        %cflushW = arith.constant {4*flushword} : i64
        %flushP = llvm.getelementptr %locp[%cflushW] : (!llvm.ptr, i64) -> !llvm.ptr, i8
        %cslots = arith.constant {slots} : index
        %myrank2 = air.chiplet_block_id
        %mycnt = air.chiplet_dim_blocks
        %mycnt_i = arith.index_cast %mycnt : index to i32
        %evbase = memref.extract_aligned_pointer_as_index %se : memref<{events}xi32> -> index
        %evi = arith.index_cast %evbase : index to i64
        %evptr = llvm.inttoptr %evi : i64 to !llvm.ptr

        scf.if %isLead {{""")

    # Queue head for (stage, die): heads are laid out stage-major so a die's
    # heads are strided, which keeps two dies off the same cache line more
    # often than not.
    def head(stage, die_expr):
        return f"{stage} * {maxdies} + {die_expr}"

    # A stage whose work splits into independent pieces. Each die has its own
    # head and its own stride of pieces, so what a die touches is what its cache
    # already holds. A die that runs out steals from the others, which is what
    # keeps this correct when the dispatcher does not use every die: locality is
    # a preference here, not an assumption.
    #
    # With `tokens` > 1 a piece is an (m, n) pair and the order the die walks
    # them in matters. Fleet sweeps M fast and N slow
    # (gang_linear_mi300.cuh:75-76, full-M-major so its window W is m_tiles):
    #
    #     m_tile = local % win_h        n_tile = local / win_h
    #
    # so `win_h` consecutive claims land on the same n -- the same block of
    # weight rows -- with different tokens. The block is read into the die's
    # cache once and serves all of them. Walking N fast instead computes the
    # same numbers while pulling a different weight block on every claim.
    #
    # Applied here to the die's own claim counter rather than a global tile id,
    # because that counter is what a die's workgroups share. At tokens == 1
    # this is m = 0, n = k, which is the index arithmetic the decode chain
    # already had -- so M = 1 stays byte-for-byte what it was.
    def strided_stage(l, stage, ev, count_expr, total_const, body):
        return f"""
          // stage {stage}
          %p{l}_{stage} = llvm.getelementptr %evptr[{4*ev}] : (!llvm.ptr) -> !llvm.ptr, i8
          %hb{l}_{stage} = arith.constant {stage * maxdies} : index
          %t{l}_{stage} = scf.for %pp = %c0_s to %cmaxdies step %c1_s
              iter_args(%outer = %zero_s) -> (i32) {{
            // Own die first, then the others in order.
            %draw = arith.addi %mydie, %pp : index
            %d = arith.remui %draw, %cmaxdies : index
            %hidx = arith.addi %hb{l}_{stage}, %d : index
            %inner:2 = scf.while (%go = %true, %acc = %outer) : (i1, i32) -> (i1, i32) {{
              scf.condition(%go) %go, %acc : i1, i32
            }} do {{
            ^bb0(%g: i1, %acc: i32):
              %cl = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hidx] : (i32, memref<{layers}x{qslots}xi32>) -> i32
              %k = arith.index_cast %cl : i32 to index
              // M fast, N slow: the token moves every claim, the weight block
              // only every `tokens` claims.
              %m = arith.remui %k, %ctok_s : index
              %kn = arith.divui %k, %ctok_s : index
              %kstride = arith.muli %kn, %cmaxdies : index
              %ix = arith.addi %d, %kstride : index
              %has = arith.cmpi ult, %ix, {count_expr} : index
              %acc2 = scf.if %has -> i32 {{
{body}
                %n = arith.addi %acc, %one_s : i32
                scf.yield %n : i32
              }} else {{
                scf.yield %acc : i32
              }}
              scf.yield %has, %acc2 : i1, i32
            }}
            scf.yield %inner#1 : i32
          }}
          // Two-level: add into a counter only this die touches, then let the
          // last worker on the die flush the die's whole share once. The
          // instructions are the same as signalling per worker; what changes is
          // how many times the device-scope one runs.
          %lw{l}_{stage} = arith.constant {4*(( (l)*stages + (stage) )*maxdies)} : i64
          %myd{l}_{stage} = arith.index_cast %mydie : index to i64
          %myd4{l}_{stage} = arith.muli %myd{l}_{stage}, %fourL : i64
          %lo{l}_{stage} = arith.addi %lw{l}_{stage}, %myd4{l}_{stage} : i64
          %locP{l}_{stage} = llvm.getelementptr %locp[%lo{l}_{stage}] : (!llvm.ptr, i64) -> !llvm.ptr, i8
          %aw{l}_{stage} = arith.constant {4*slots} : i64
          %ao{l}_{stage} = arith.addi %aw{l}_{stage}, %lo{l}_{stage} : i64
          %arrP{l}_{stage} = llvm.getelementptr %locp[%ao{l}_{stage}] : (!llvm.ptr, i64) -> !llvm.ptr, i8
          %la{l}_{stage} = llvm.atomicrmw add %locP{l}_{stage}, %t{l}_{stage} syncscope("agent") monotonic : !llvm.ptr, i32
          // Release on the arrival so the accumulate above is visible to
          // whoever turns out to be last.
          %ar{l}_{stage} = llvm.atomicrmw add %arrP{l}_{stage}, %one_s syncscope("agent") release : !llvm.ptr, i32
          %last{l}_{stage} = arith.subi %mycnt_i, %one_s : i32
          %amLast{l}_{stage} = arith.cmpi eq, %ar{l}_{stage}, %last{l}_{stage} : i32
          scf.if %amLast{l}_{stage} {{
            %tot{l}_{stage} = llvm.load %locP{l}_{stage} atomic syncscope("agent") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %sig{l}_{stage} = llvm.atomicrmw add %p{l}_{stage}, %tot{l}_{stage} syncscope("") release : !llvm.ptr, i32
            %cnt{l}_{stage} = llvm.atomicrmw add %flushP, %one_s syncscope("") monotonic : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_{stage} atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, {total_const} : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}"""

    def matmul_stage(l, stage, ev, out, lhs, wmat, wtype, relu):
        # The weights are read once per layer and never again inside a decode
        # step, and they are far larger than anything else in flight, so they
        # are exactly what would evict the activations. Fleet loads them
        # non-temporally too (gang_ksplit_linear_mi300.cuh:88 uses
        # amd_buffer_coherence_enum(18), which is nt|sc1). The activations are
        # deliberately left alone: Fleet marks its activation stores
        # non-temporal as well, but at 128 floats these live in cache happily
        # and pushing them to HBM would only cost.
        act = ("%la = arith.maxnumf %lv, %fzero_s : f32" if relu
               else "%la = arith.addf %lv, %fzero_s : f32")
        body = f"""                %j0 = arith.muli %ix, %cslice : index
                scf.for %jj = %c0_s to %cslice step %c1_s {{
                  %j = arith.addi %j0, %jj : index
                  %a = scf.for %i = %c0_s to %cdim_s step %c1_s
                      iter_args(%sacc = %fzero_s) -> (f32) {{
                    %lv = memref.load {lhs}[%m, %i] : {AT}
                    {act}
                    %wv = memref.load {wmat}[%L{l}, %i, %j] {{nontemporal = true}} : {wtype}
                    %mp = arith.mulf %la, %wv : f32
                    %s2 = arith.addf %sacc, %mp : f32
                    scf.yield %s2 : f32
                  }}
                  memref.store %a, {out}[%m, %j] : {AT}
                }}"""
        return strided_stage(l, stage, ev, "%ctasks", "%ntasks_t", body)

    for l in range(layers):
        base = stages * l
        w(f"""
          // ================= layer {l} =================
          // stage 0: rmsnorm. One task -- it reduces over all of x.
          %hsingle0_{l} = arith.constant 0 : index
          %p{l}_0 = llvm.getelementptr %evptr[{4*base}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_0 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hsingle0_{l}] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_0 = arith.cmpi eq, %cl{l}_0, %zero_s : i32
          scf.if %mine{l}_0 {{
            scf.for %m = %c0_s to %ctok_s step %c1_s {{
              %ss{l} = scf.for %i = %c0_s to %cdim_s step %c1_s
                  iter_args(%s = %fzero_s) -> (f32) {{
                %v = memref.load %sx[%m, %i] : {AT}
                %sq2 = arith.mulf %v, %v : f32
                %s2 = arith.addf %s, %sq2 : f32
                scf.yield %s2 : f32
              }}
              %mean{l} = arith.divf %ss{l}, %fdim_s : f32
              %me{l} = arith.addf %mean{l}, %eps_s : f32
              %rms{l} = math.sqrt %me{l} : f32
              scf.for %i = %c0_s to %cdim_s step %c1_s {{
                %v = memref.load %sx[%m, %i] : {AT}
                %n = arith.divf %v, %rms{l} : f32
                memref.store %n, %sr[%m, %i] : {AT}
              }}
            }}
            %sig{l}_0 = llvm.atomicrmw add %p{l}_0, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_0 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}""")

        w(matmul_stage(l, 1, base + 1, "%sqv", "%sr", "%swq",
                       f"memref<{layers}x{dim}x{dim}xf32>", False))

        # stage 2: one score per cache entry, claimed per die like the rest.
        w(strided_stage(l, 2, base + 2, "%ccache_s", "%ncache_t",
                        f"""                %dot = scf.for %i = %c0_s to %cdim_s step %c1_s
                    iter_args(%sdot = %fzero_s) -> (f32) {{
                  %qv2 = memref.load %sqv[%m, %i] : {AT}
                  %kv = memref.load %skc[%L{l}, %ix, %i] {{nontemporal = true}} : memref<{layers}x{cache}x{dim}xf32>
                  %mp = arith.mulf %qv2, %kv : f32
                  %s2 = arith.addf %sdot, %mp : f32
                  scf.yield %s2 : f32
                }}
                %sc = arith.mulf %dot, %invsqrtd_s : f32
                memref.store %sc, %ssv[%m, %ix] : {ST}"""))

        w(f"""
          // stage 3: softmax. One task -- it reduces over every score.
          %hsingle3_{l} = arith.constant {3*maxdies} : index
          %p{l}_3 = llvm.getelementptr %evptr[{4*(base+3)}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_3 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hsingle3_{l}] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_3 = arith.cmpi eq, %cl{l}_3, %zero_s : i32
          scf.if %mine{l}_3 {{
            scf.for %m = %c0_s to %ctok_s step %c1_s {{
              %mx{l} = scf.for %t = %c0_s to %ccache_s step %c1_s
                  iter_args(%mv = %negbig_s) -> (f32) {{
                %v = memref.load %ssv[%m, %t] : {ST}
                %m2 = arith.maxnumf %mv, %v : f32
                scf.yield %m2 : f32
              }}
              %sum{l} = scf.for %t = %c0_s to %ccache_s step %c1_s
                  iter_args(%sm = %fzero_s) -> (f32) {{
                %v = memref.load %ssv[%m, %t] : {ST}
                %d = arith.subf %v, %mx{l} : f32
                %e = math.exp %d : f32
                memref.store %e, %spv[%m, %t] : {ST}
                %s2 = arith.addf %sm, %e : f32
                scf.yield %s2 : f32
              }}
              scf.for %t = %c0_s to %ccache_s step %c1_s {{
                %en = memref.load %spv[%m, %t] : {ST}
                %pn = arith.divf %en, %sum{l} : f32
                memref.store %pn, %spv[%m, %t] : {ST}
              }}
            }}
            %sig{l}_3 = llvm.atomicrmw add %p{l}_3, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_3 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}""")

        # stage 4: the attention-weighted sum of V, claimed like the
        # matmuls so it signals the same way they do.
        w(strided_stage(l, 4, base + 4, "%ctasks", "%ntasks_t",
                        f'                %j0 = arith.muli %ix, %cslice : index\n                scf.for %jj = %c0_s to %cslice step %c1_s {{\n                  %j = arith.addi %j0, %jj : index\n                  %a = scf.for %t = %c0_s to %ccache_s step %c1_s\n                      iter_args(%sacc = %fzero_s) -> (f32) {{\n                    %pn = memref.load %spv[%m, %t] : {ST}\n                    %vv = memref.load %svc[%L{l}, %t, %j] {{nontemporal = true}} : memref<{layers}x{cache}x{dim}xf32>\n                    %mp = arith.mulf %pn, %vv : f32\n                    %s2 = arith.addf %sacc, %mp : f32\n                    scf.yield %s2 : f32\n                  }}\n                  memref.store %a, %sav[%m, %j] : {AT}\n                }}'))


        # stage 5: the residual around attention and the norm in front of the
        # MLP. One task: the norm is a reduction, and it reads x, which the MLP
        # stages are about to overwrite.
        #
        # The norm is not decoration. Without it nothing renormalises the
        # residual stream -- stage 0's rmsnorm feeds only the q projection --
        # so the stream grows or decays geometrically with depth, and since the
        # host comparison is relative, a stream in the thousands hides every
        # error smaller than itself. A real decoder layer has this norm too.
        w(f"""
          // stage 5: xa = rmsnorm(x + a), the residual around attention and
          // the norm the MLP reads.
          %hsingle5_{l} = arith.constant {5*maxdies} : index
          %p{l}_5 = llvm.getelementptr %evptr[{4*(base+5)}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_5 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hsingle5_{l}] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_5 = arith.cmpi eq, %cl{l}_5, %zero_s : i32
          scf.if %mine{l}_5 {{
            scf.for %m = %c0_s to %ctok_s step %c1_s {{
              %ssa{l} = scf.for %i = %c0_s to %cdim_s step %c1_s
                  iter_args(%s = %fzero_s) -> (f32) {{
                %xv = memref.load %sx[%m, %i] : {AT}
                %avv = memref.load %sav[%m, %i] : {AT}
                %xa = arith.addf %xv, %avv : f32
                memref.store %xa, %sxa[%m, %i] : {AT}
                %sqa = arith.mulf %xa, %xa : f32
                %s2 = arith.addf %s, %sqa : f32
                scf.yield %s2 : f32
              }}
              %meana{l} = arith.divf %ssa{l}, %fdim_s : f32
              %mea{l} = arith.addf %meana{l}, %eps_s : f32
              %rmsa{l} = math.sqrt %mea{l} : f32
              scf.for %i = %c0_s to %cdim_s step %c1_s {{
                %xv3 = memref.load %sxa[%m, %i] : {AT}
                %xn = arith.divf %xv3, %rmsa{l} : f32
                memref.store %xn, %sxa[%m, %i] : {AT}
              }}
            }}
            %sig{l}_5 = llvm.atomicrmw add %p{l}_5, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_5 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}""")
        w(matmul_stage(l, 6, base + 6, "%sh", "%sxa", "%sw1",
                       f"memref<{layers}x{dim}x{dim}xf32>", False))
        w(matmul_stage(l, 7, base + 7, "%sy", "%sh", "%sw2",
                       f"memref<{layers}x{dim}x{dim}xf32>", True))

        w(f"""
          // stage 8: x = xa + y, the residual around the MLP, carried into
          // the next layer.
          %hsingle8_{l} = arith.constant {8*maxdies} : index
          %p{l}_8 = llvm.getelementptr %evptr[{4*(base+8)}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_8 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hsingle8_{l}] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_8 = arith.cmpi eq, %cl{l}_8, %zero_s : i32
          scf.if %mine{l}_8 {{
            scf.for %m = %c0_s to %ctok_s step %c1_s {{
              scf.for %i = %c0_s to %cdim_s step %c1_s {{
                %xav = memref.load %sxa[%m, %i] : {AT}
                %v = memref.load %sy[%m, %i] : {AT}
                %nx = arith.addf %xav, %v : f32
                memref.store %nx, %sx[%m, %i] : {AT}
              }}
            }}
            %sig{l}_8 = llvm.atomicrmw add %p{l}_8, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_8 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}""")

    w(f"""
        }}

        air.herd @herd tile (%htx, %hty) in (%ntx=%c1_s, %nty=%c1_s) {{
        }}
      }}
    }}
    return
  }}
}}
""")
    return "".join(o)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layers", type=int, default=4)
    ap.add_argument("--dim", type=int, default=128)
    ap.add_argument("--tasks", type=int, default=8,
                    help="tasks per matmul stage; dim must divide by this")
    ap.add_argument("--workers", type=int, default=32,
                    help="resident workgroups; must fit the device at once")
    ap.add_argument("--cache", type=int, default=32,
                    help="KV cache length the attention stage reads")
    ap.add_argument("--tokens", type=int, default=1,
                    help="tokens in flight (M). 1 is a decode step; >1 is a "
                         "prefill or speculative window, and is what makes the "
                         "M-major traversal do anything")
    ap.add_argument("--repeat", type=int, default=1,
                    help="how many times to launch the chain, for timing: "
                         "--layers 36 --repeat 1 is one launch doing 36 layers, "
                         "--layers 1 --repeat 36 is 36 launches doing one each")
    a = ap.parse_args()
    sys.stdout.write(
        emit(a.layers, a.dim, a.tasks, a.workers, a.repeat, a.cache, a.tokens))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
