#!/usr/bin/env python3
"""Emit a megakernel decode chain as AIR MLIR.

Qwen has 36 layers of several stages each. Nobody writes that by hand, and the
hand-written tests next to this one stop being a plan the moment the layer
count stops being 2. Fleet has the same problem and solves it the same way: its
task graph is described in Python and `src/kernel/runtime.cc` prints the C++.
This prints MLIR instead.

What a layer is here:

    r = x / sqrt(mean(x^2) + eps)     one task, a reduction
    h = r @ W1                        `tasks` tasks, one per slice of h
    y = relu(h) @ W2                  `tasks` tasks, reads all of h
    x = y                             carried to the next layer

Every stage boundary is an event, and the whole chain is one launch. The stage
structure is what scales: adding a layer adds queue slots and event slots, not
a kernel launch.

    ./gen.py --layers 4 --dim 128 > chain.mlir
"""

import argparse
import sys


def emit(layers: int, dim: int, tasks: int, workers: int, repeat: int = 1) -> str:
    assert dim % tasks == 0, "dim must divide evenly into tasks"
    slice_w = dim // tasks
    # Per layer: one event for the reduction, one for each of the two matmul
    # stages, and one for the carry.
    events = 4 * layers
    qslots = 4  # head per stage, plus the carry claim
    o = []
    w = o.append

    w(f"""// Generated by test/gpu/megakernel_gen/gen.py -- do not edit.
//   layers={layers} dim={dim} tasks/stage={tasks} workers={workers}
//
// A decode chain as a megakernel: one launch, {layers} layers, every stage
// boundary an event rather than a return to the host.
module {{
  func.func @main() {{
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %cdim = arith.constant {dim} : index
    %zero = arith.constant 0 : i32
    %one = arith.constant 1 : i32
    %fzero = arith.constant 0.0 : f32
    %eps = arith.constant 1.0e-6 : f32
    %fdim = arith.constant {float(dim):.6e} : f32
    %c3f = arith.constant 3.0 : f32
    %c5f = arith.constant 5.0 : f32
    %scale = arith.constant 1.250000e-01 : f32
    %clayers = arith.constant {layers} : index

    %X = memref.alloc() : memref<{dim}xf32>
    %X0 = memref.alloc() : memref<{dim}xf32>
    %W1 = memref.alloc() : memref<{layers}x{dim}x{dim}xf32>
    %W2 = memref.alloc() : memref<{layers}x{dim}x{dim}xf32>
    %R = memref.alloc() : memref<{dim}xf32>
    %H = memref.alloc() : memref<{dim}xf32>
    %Y = memref.alloc() : memref<{dim}xf32>
    %ref = memref.alloc() : memref<{dim}xf32>
    %refh = memref.alloc() : memref<{dim}xf32>

    scf.for %i = %c0 to %cdim step %c1 {{
      %ii = arith.index_cast %i : index to i32
      %fi = arith.sitofp %ii : i32 to f32
      %v = arith.remf %fi, %c3f : f32
      %v2 = arith.addf %v, %scale : f32
      memref.store %v2, %X[%i] : memref<{dim}xf32>
      memref.store %v2, %X0[%i] : memref<{dim}xf32>
      memref.store %v2, %ref[%i] : memref<{dim}xf32>
      memref.store %fzero, %R[%i] : memref<{dim}xf32>
      memref.store %fzero, %H[%i] : memref<{dim}xf32>
      memref.store %fzero, %Y[%i] : memref<{dim}xf32>
      scf.for %l = %c0 to %clayers step %c1 {{
        scf.for %j = %c0 to %cdim step %c1 {{
          %jj = arith.index_cast %j : index to i32
          %fj = arith.sitofp %jj : i32 to f32
          %ll = arith.index_cast %l : index to i32
          %fl = arith.sitofp %ll : i32 to f32
          %d = arith.subf %fi, %fj : f32
          %d2 = arith.addf %d, %fl : f32
          %ww = arith.remf %d2, %c5f : f32
          %wn = arith.mulf %ww, %scale : f32
          memref.store %wn, %W1[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %w3 = arith.addf %d2, %c3f : f32
          %w4 = arith.remf %w3, %c5f : f32
          %wn2 = arith.mulf %w4, %scale : f32
          memref.store %wn2, %W2[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
        }}
      }}
    }}

    // Reference for the whole chain, on the host.
    scf.for %l = %c0 to %clayers step %c1 {{
      %ss = scf.for %i = %c0 to %cdim step %c1
          iter_args(%s = %fzero) -> (f32) {{
        %v = memref.load %ref[%i] : memref<{dim}xf32>
        %sq = arith.mulf %v, %v : f32
        %s2 = arith.addf %s, %sq : f32
        scf.yield %s2 : f32
      }}
      %mean = arith.divf %ss, %fdim : f32
      %me = arith.addf %mean, %eps : f32
      %rms = math.sqrt %me : f32
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %xv = memref.load %ref[%i] : memref<{dim}xf32>
          %rv = arith.divf %xv, %rms : f32
          %wv = memref.load %W1[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %m = arith.mulf %rv, %wv : f32
          %s2 = arith.addf %s, %m : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refh[%j] : memref<{dim}xf32>
      }}
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %hv = memref.load %refh[%i] : memref<{dim}xf32>
          %rl = arith.maxnumf %hv, %fzero : f32
          %wv = memref.load %W2[%l, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
          %m = arith.mulf %rl, %wv : f32
          %s2 = arith.addf %s, %m : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %Y[%j] : memref<{dim}xf32>
      }}
      scf.for %j = %c0 to %cdim step %c1 {{
        %v = memref.load %Y[%j] : memref<{dim}xf32>
        memref.store %v, %ref[%j] : memref<{dim}xf32>
      }}
    }}
    scf.for %i = %c0 to %cdim step %c1 {{
      memref.store %fzero, %Y[%i] : memref<{dim}xf32>
    }}

    // Queues and events, sized by the chain rather than hand-counted.
    %Q = memref.alloc() : memref<{layers}x{qslots}xi32>
    %cq = arith.constant {qslots} : index
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %k = %c0 to %cq step %c1 {{
        memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
      }}
    }}
    %E = memref.alloc() : memref<{events}xi32>
    %ce = arith.constant {events} : index
    scf.for %i = %c0 to %ce step %c1 {{
      memref.store %zero, %E[%i] : memref<{events}xi32>
    }}

    %dX = gpu.alloc () : memref<{dim}xf32>
    %dR = gpu.alloc () : memref<{dim}xf32>
    %dH = gpu.alloc () : memref<{dim}xf32>
    %dY = gpu.alloc () : memref<{dim}xf32>
    %dW1 = gpu.alloc () : memref<{layers}x{dim}x{dim}xf32>
    %dW2 = gpu.alloc () : memref<{layers}x{dim}x{dim}xf32>
    %dQ = gpu.alloc () : memref<{layers}x{qslots}xi32>
    %dE = gpu.alloc () : memref<{events}xi32>
    gpu.memcpy %dX, %X : memref<{dim}xf32>, memref<{dim}xf32>
    gpu.memcpy %dR, %R : memref<{dim}xf32>, memref<{dim}xf32>
    gpu.memcpy %dH, %H : memref<{dim}xf32>, memref<{dim}xf32>
    gpu.memcpy %dY, %Y : memref<{dim}xf32>, memref<{dim}xf32>
    gpu.memcpy %dW1, %W1 : memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>
    gpu.memcpy %dW2, %W2 : memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>
    gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
    gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>

    // --repeat runs the chain more than once so an external clock has
    // something to measure. Timing it from inside with mgpuEventRecord does not
    // work: the events go on the stream created here, while gpu-to-llvm puts
    // the kernel on one of its own, so the elapsed time is between two events
    // on an idle stream -- mgpuEventElapsedTime returns hipErrorInvalidHandle
    // and the number is garbage. The 4k GEMM test has the same problem.
    %crep = arith.constant {repeat} : index
    scf.for %rep = %c0 to %crep step %c1 {{
      // Re-arm the queues and events so each repetition is a fresh chain.
      scf.for %l = %c0 to %clayers step %c1 {{
        scf.for %k = %c0 to %cq step %c1 {{
          memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
        }}
      }}
      scf.for %i = %c0 to %ce step %c1 {{
        memref.store %zero, %E[%i] : memref<{events}xi32>
      }}
      gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
      gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>
      // The chain rewrites x in place, so a second repetition would start from
      // the first one's output rather than the input.
      gpu.memcpy %dX, %X0 : memref<{dim}xf32>, memref<{dim}xf32>
      func.call @chain(%dQ, %dE, %dX, %dR, %dH, %dY, %dW1, %dW2)
        : (memref<{layers}x{qslots}xi32>, memref<{events}xi32>, memref<{dim}xf32>,
           memref<{dim}xf32>, memref<{dim}xf32>, memref<{dim}xf32>,
           memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32>) -> ()
    }}

    gpu.memcpy %X, %dX : memref<{dim}xf32>, memref<{dim}xf32>

    %tol = arith.constant 2.0e-2 : f32
    %fone = arith.constant 1.0 : f32
    %bad = scf.for %i = %c0 to %cdim step %c1
        iter_args(%b = %zero) -> (i32) {{
      %got = memref.load %X[%i] : memref<{dim}xf32>
      %want = memref.load %ref[%i] : memref<{dim}xf32>
      %d = arith.subf %got, %want : f32
      %ad = math.absf %d : f32
      %aw = math.absf %want : f32
      %sc = arith.maxnumf %aw, %fone : f32
      %rel = arith.divf %ad, %sc : f32
      %ok = arith.cmpf ole, %rel, %tol : f32
      %inc = arith.select %ok, %zero, %one : i32
      %b2 = arith.addi %b, %inc : i32
      scf.yield %b2 : i32
    }}
    vector.print str "layers = "
    %nl = arith.constant {layers} : i32
    vector.print %nl : i32
    vector.print str "output elements differing from the reference = "
    vector.print %bad : i32
    return
  }}
""")

    layer_consts = "\n".join(
        f"        %L{i} = arith.constant {i} : index" for i in range(layers))
    w(f"""
  func.func @chain(%Q: memref<{layers}x{qslots}xi32>, %E: memref<{events}xi32>,
                   %X: memref<{dim}xf32>, %Rv: memref<{dim}xf32>,
                   %Hv: memref<{dim}xf32>, %Yv: memref<{dim}xf32>,
                   %W1: memref<{layers}x{dim}x{dim}xf32>, %W2: memref<{layers}x{dim}x{dim}xf32>) {{
    %c1 = arith.constant 1 : index
    %cw = arith.constant {workers} : index
    air.launch (%bx, %by) in (%nbx=%cw, %nby=%c1)
        args(%q=%Q, %e=%E, %x=%X, %r=%Rv, %h=%Hv, %y=%Yv, %w1=%W1, %w2=%W2)
        : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, memref<{dim}xf32>,
          memref<{dim}xf32>, memref<{dim}xf32>, memref<{dim}xf32>,
          memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32> {{
      air.segment @worker args(%sq=%q, %se=%e, %sx=%x, %sr=%r, %sh=%h, %sy=%y, %sw1=%w1, %sw2=%w2)
          : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, memref<{dim}xf32>,
            memref<{dim}xf32>, memref<{dim}xf32>, memref<{dim}xf32>,
            memref<{layers}x{dim}x{dim}xf32>, memref<{layers}x{dim}x{dim}xf32> {{
        %c0_s = arith.constant 0 : index
        %c1_s = arith.constant 1 : index
        %c2_s = arith.constant 2 : index
        %c3_s = arith.constant 3 : index
        %ctasks = arith.constant {tasks} : index
        %cslice = arith.constant {slice_w} : index
        %cdim_s = arith.constant {dim} : index
        %one_s = arith.constant 1 : i32
        %zero_s = arith.constant 0 : i32
        %ntasks = arith.constant {tasks} : i32
        %n1 = arith.constant 1 : i32
        %fzero_s = arith.constant 0.0 : f32
        %eps_s = arith.constant 1.0e-6 : f32
        %fdim_s = arith.constant {float(dim):.6e} : f32
        %true = arith.constant true

        %tx_s = gpu.thread_id x
        %ty_s = gpu.thread_id y
        %tz_s = gpu.thread_id z
        %t01 = arith.ori %tx_s, %ty_s : index
        %t012 = arith.ori %t01, %tz_s : index
        %isLead = arith.cmpi eq, %t012, %c0_s : index
{layer_consts}
        %evbase = memref.extract_aligned_pointer_as_index %se : memref<{events}xi32> -> index
        %evi = arith.index_cast %evbase : index to i64
        %evptr = llvm.inttoptr %evi : i64 to !llvm.ptr

        scf.if %isLead {{""")

    for l in range(layers):
        e0, e1, e2, e3 = 4 * l, 4 * l + 1, 4 * l + 2, 4 * l + 3
        w(f"""
          // ================= layer {l} =================
          // stage 0: the reduction. One task, so one worker; everyone waits.
          %p{l}_0 = llvm.getelementptr %evptr[{4*e0}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_0 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %c0_s] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_0 = arith.cmpi eq, %cl{l}_0, %zero_s : i32
          scf.if %mine{l}_0 {{
            %ss{l} = scf.for %i = %c0_s to %cdim_s step %c1_s
                iter_args(%s = %fzero_s) -> (f32) {{
              %v = memref.load %sx[%i] : memref<{dim}xf32>
              %sq2 = arith.mulf %v, %v : f32
              %s2 = arith.addf %s, %sq2 : f32
              scf.yield %s2 : f32
            }}
            %mean{l} = arith.divf %ss{l}, %fdim_s : f32
            %me{l} = arith.addf %mean{l}, %eps_s : f32
            %rms{l} = math.sqrt %me{l} : f32
            scf.for %i = %c0_s to %cdim_s step %c1_s {{
              %v = memref.load %sx[%i] : memref<{dim}xf32>
              %n = arith.divf %v, %rms{l} : f32
              memref.store %n, %sr[%i] : memref<{dim}xf32>
            }}
            %sig{l}_0 = llvm.atomicrmw add %p{l}_0, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_0 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}

          // stage 1: h = r @ W1, one task per slice.
          %p{l}_1 = llvm.getelementptr %evptr[{4*e1}] : (!llvm.ptr) -> !llvm.ptr, i8
          %t{l}_1:2 = scf.while (%go = %true, %acc = %zero_s) : (i1, i32) -> (i1, i32) {{
            scf.condition(%go) %go, %acc : i1, i32
          }} do {{
          ^bb0(%g: i1, %acc: i32):
            %cl = memref.atomic_rmw addi %one_s, %sq[%L{l}, %c1_s] : (i32, memref<{layers}x{qslots}xi32>) -> i32
            %ix = arith.index_cast %cl : i32 to index
            %has = arith.cmpi ult, %ix, %ctasks : index
            %acc2 = scf.if %has -> i32 {{
              %j0 = arith.muli %ix, %cslice : index
              scf.for %jj = %c0_s to %cslice step %c1_s {{
                %j = arith.addi %j0, %jj : index
                %a = scf.for %i = %c0_s to %cdim_s step %c1_s
                    iter_args(%s = %fzero_s) -> (f32) {{
                  %rv = memref.load %sr[%i] : memref<{dim}xf32>
                  %wv = memref.load %sw1[%L{l}, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
                  %m = arith.mulf %rv, %wv : f32
                  %s2 = arith.addf %s, %m : f32
                  scf.yield %s2 : f32
                }}
                memref.store %a, %sh[%j] : memref<{dim}xf32>
              }}
              %n = arith.addi %acc, %one_s : i32
              scf.yield %n : i32
            }} else {{
              scf.yield %acc : i32
            }}
            scf.yield %has, %acc2 : i1, i32
          }}
          %sig{l}_1 = llvm.atomicrmw add %p{l}_1, %t{l}_1#1 syncscope("") release : !llvm.ptr, i32
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_1 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %ntasks : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}

          // stage 2: y = relu(h) @ W2. Reads all of h, hence the gate above.
          %p{l}_2 = llvm.getelementptr %evptr[{4*e2}] : (!llvm.ptr) -> !llvm.ptr, i8
          %t{l}_2:2 = scf.while (%go2 = %true, %acc2i = %zero_s) : (i1, i32) -> (i1, i32) {{
            scf.condition(%go2) %go2, %acc2i : i1, i32
          }} do {{
          ^bb0(%g2: i1, %acc2i: i32):
            %cl2 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %c2_s] : (i32, memref<{layers}x{qslots}xi32>) -> i32
            %ix2 = arith.index_cast %cl2 : i32 to index
            %has2 = arith.cmpi ult, %ix2, %ctasks : index
            %acc3 = scf.if %has2 -> i32 {{
              %j0 = arith.muli %ix2, %cslice : index
              scf.for %jj = %c0_s to %cslice step %c1_s {{
                %j = arith.addi %j0, %jj : index
                %a = scf.for %i = %c0_s to %cdim_s step %c1_s
                    iter_args(%s = %fzero_s) -> (f32) {{
                  %hv = memref.load %sh[%i] : memref<{dim}xf32>
                  %rl = arith.maxnumf %hv, %fzero_s : f32
                  %wv = memref.load %sw2[%L{l}, %i, %j] : memref<{layers}x{dim}x{dim}xf32>
                  %m = arith.mulf %rl, %wv : f32
                  %s2 = arith.addf %s, %m : f32
                  scf.yield %s2 : f32
                }}
                memref.store %a, %sy[%j] : memref<{dim}xf32>
              }}
              %n = arith.addi %acc2i, %one_s : i32
              scf.yield %n : i32
            }} else {{
              scf.yield %acc2i : i32
            }}
            scf.yield %has2, %acc3 : i1, i32
          }}
          %sig{l}_2 = llvm.atomicrmw add %p{l}_2, %t{l}_2#1 syncscope("") release : !llvm.ptr, i32
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_2 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %ntasks : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}

          // carry y into x for the next layer.
          %p{l}_3 = llvm.getelementptr %evptr[{4*e3}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_3 = memref.atomic_rmw addi %one_s, %sq[%L{l}, %c3_s] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_3 = arith.cmpi eq, %cl{l}_3, %zero_s : i32
          scf.if %mine{l}_3 {{
            scf.for %i = %c0_s to %cdim_s step %c1_s {{
              %v = memref.load %sy[%i] : memref<{dim}xf32>
              memref.store %v, %sx[%i] : memref<{dim}xf32>
            }}
            %sig{l}_3 = llvm.atomicrmw add %p{l}_3, %n1 syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_3 atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1 : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}""")

    w(f"""
        }}

        air.herd @herd tile (%htx, %hty) in (%ntx=%c1_s, %nty=%c1_s) {{
        }}
      }}
    }}
    return
  }}
}}
""")
    return "".join(o)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layers", type=int, default=4)
    ap.add_argument("--dim", type=int, default=128)
    ap.add_argument("--tasks", type=int, default=8,
                    help="tasks per matmul stage; dim must divide by this")
    ap.add_argument("--workers", type=int, default=32,
                    help="resident workgroups; must fit the device at once")
    ap.add_argument("--repeat", type=int, default=1,
                    help="how many times to launch the chain, for timing: "
                         "--layers 36 --repeat 1 is one launch doing 36 layers, "
                         "--layers 1 --repeat 36 is 36 launches doing one each")
    a = ap.parse_args()
    sys.stdout.write(emit(a.layers, a.dim, a.tasks, a.workers, a.repeat))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
