#!/usr/bin/env python3
"""Emit a megakernel decode chain as AIR MLIR.

Qwen has 36 layers of several stages each. Nobody writes that by hand, and the
hand-written tests next to this one stop being a plan the moment the layer
count stops being 2. Fleet has the same problem and solves it the same way: its
task graph is described in Python and `src/kernel/runtime.cc` prints the C++.
This prints MLIR instead.

The layer is shaped like the one Fleet builds for Qwen3
(python/mirage/mpk/models/qwen3/builder.py): an input norm with a learned
weight, a projection, attention over a KV cache, an output projection folded
into the residual, a second norm, a fused gate/up projection, SwiGLU, and a
down projection folded into the residual.

    r   = rmsnorm(x) * n1          0   one task, a reduction
    q   = r @ Wq                   1
    s   = q . K[t] / sqrt(d)       2   one task per cache entry
    p   = softmax(s)               3   one task, a reduction
    a   = p @ V                    4
    ao  = a @ Wo                   5
    xa  = rmsnorm(x + ao) * n2     6   one task, a reduction
    gu  = xa @ Wgu                 7   gate and up fused, as Fleet fuses them
    act = silu(gu_g) * gu_u        8   SwiGLU
    x   = xa + act @ Wd            9   carried to the next layer

Every stage boundary is an event, and the whole chain is one launch. The stage
structure is what scales: adding a layer adds queue slots and event slots, not
a kernel launch.

With --tokens M > 1 the chain runs M tokens at once, which is what a prefill or
a speculative window looks like: the M tokens attend a shared KV prefix (they
are not in each other's cache, so there is no mask among them) and every linear
stage becomes an (m, n) grid rather than a row of n. The traversal of that grid
is Fleet's -- see strided_stage. At M = 1 the decomposition collapses to the
index arithmetic this generator used before --tokens existed.

    ./gen.py --layers 4 --dim 128 > chain.mlir
    ./gen.py --layers 2 --dim 128 --tokens 4 > prefill.mlir
"""

import argparse
import math as _math
import sys

# Every weight is built from `index % modulus`, and every one of them uses a
# different modulus. Sharing one makes the matmuls resonate: a weight matrix
# W[i, j] = f(i - j) is a convolution, and if the activation it multiplies has
# the same period, the products add coherently and the gain is ~dim instead of
# ~sqrt(dim). Measured, with a period-5 activation: a period-5 weight amplifies
# 2.84x what a random walk would, every other period 0.2x.
MOD_Q, MOD_O, MOD_G, MOD_U, MOD_D, MOD_K, MOD_V = 3, 5, 7, 13, 3, 7, 5
# Weight magnitude after centring and scaling to unit standard deviation.
WSCALE = 0.25


def _uscale(mod, s=WSCALE):
    """Scale that turns `x % mod` into a unit-variance value times s."""
    return s / _math.sqrt((mod * mod - 1) / 12.0)


def emit(layers: int, dim: int, tasks: int, workers: int, repeat: int = 1,
         cache: int = 32, tokens: int = 1, inter: int = 0) -> str:
    inter = inter or 2 * dim
    assert dim % tasks == 0, "dim must divide evenly into tasks"
    assert inter % tasks == 0, "inter must divide evenly into tasks"
    slice_d = dim // tasks
    slice_i = inter // tasks
    slice_2i = (2 * inter) // tasks
    invsqrtd = dim ** -0.5
    # Activations carry a token dimension; weights and the KV cache do not.
    # That asymmetry is the whole reason M > 1 changes the traversal: a weight
    # block is worth reading once and using `tokens` times.
    AT = f"memref<{tokens}x{dim}xf32>"
    IT = f"memref<{tokens}x{inter}xf32>"
    GT = f"memref<{tokens}x{2 * inter}xf32>"
    ST = f"memref<{tokens}x{cache}xf32>"
    WT = f"memref<{layers}x{dim}x{dim}xf32>"
    WGT = f"memref<{layers}x{dim}x{2 * inter}xf32>"
    WDT = f"memref<{layers}x{inter}x{dim}xf32>"
    CT = f"memref<{layers}x{cache}x{dim}xf32>"
    NT = f"memref<{layers}x{dim}xf32>"

    stages = 10
    events = stages * layers
    # A head per die per stage. The die count is not known until the program
    # runs, so allocate for more dies than any current part has and let the
    # unused heads sit at zero.
    maxdies = 16
    qslots = stages * maxdies
    # accumulate + arrivals per (layer, stage, die), then one word for flushes
    slots = layers * stages * maxdies
    flushword = 2 * slots
    locwords = flushword + 1
    # Only the multi-task stages signal per worker; the three single-task ones
    # are claimed by one workgroup and already signal once.
    strided_stages = 7  # stages 1, 2, 4, 5, 7, 8, 9
    naive = workers * strided_stages * layers
    o = []
    w = o.append

    w(f"""// Generated by test/gpu/megakernel_gen/gen.py -- do not edit.
//   layers={layers} dim={dim} inter={inter} tasks/stage={tasks} workers={workers} tokens={tokens}
//
// A decode chain as a megakernel: one launch, {layers} layers, every stage
// boundary an event rather than a return to the host.
module {{
  func.func @main() {{
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index
    %cdim = arith.constant {dim} : index
    %cinter = arith.constant {inter} : index
    %c2inter = arith.constant {2 * inter} : index
    %zero = arith.constant 0 : i32
    %one = arith.constant 1 : i32
    %fzero = arith.constant 0.0 : f32
    %fone = arith.constant 1.0 : f32
    %eps = arith.constant 1.0e-6 : f32
    %fdim = arith.constant {float(dim):.6e} : f32
    %fred_d = arith.constant {float(dim):.6e} : f32
    %fred_i = arith.constant {float(inter):.6e} : f32
    %fred_c = arith.constant {float(cache):.6e} : f32
    %c2f = arith.constant 2.0 : f32
    %c3f = arith.constant 3.0 : f32
    %c5f = arith.constant 5.0 : f32
    %c7f = arith.constant 7.0 : f32
    %c11f = arith.constant 11.0 : f32
    %c13f = arith.constant 13.0 : f32
    %quarter = arith.constant 2.500000e-01 : f32
    %eighth = arith.constant 1.250000e-01 : f32
    %sixteenth = arith.constant 6.250000e-02 : f32
    %clayers = arith.constant {layers} : index
    %ctok = arith.constant {tokens} : index
    %ccache = arith.constant {cache} : index

    %X = memref.alloc() : {AT}
    %X0 = memref.alloc() : {AT}
    %Rv = memref.alloc() : {AT}
    %Qv = memref.alloc() : {AT}
    %Sv = memref.alloc() : {ST}
    %Pv = memref.alloc() : {ST}
    %Av = memref.alloc() : {AT}
    %Aov = memref.alloc() : {AT}
    %Xa = memref.alloc() : {AT}
    %GU = memref.alloc() : {GT}
    %Actv = memref.alloc() : {IT}
    %Wq = memref.alloc() : {WT}
    %Wo = memref.alloc() : {WT}
    %Wgu = memref.alloc() : {WGT}
    %Wd = memref.alloc() : {WDT}
    %Kc = memref.alloc() : {CT}
    %Vc = memref.alloc() : {CT}
    %N1 = memref.alloc() : {NT}
    %N2 = memref.alloc() : {NT}
    %ref = memref.alloc() : {AT}

    // Each token gets a different *pattern*, not the same pattern shifted by a
    // constant. A constant offset does not survive: rmsnorm divides most of it
    // out, so the queries come out within a few percent of each other and a
    // token reading another token's scores is indistinguishable from correct.
    // 3i + 7m mod 11 gives each token a different rotation; 11 is coprime with
    // every weight modulus, so the input does not resonate with any of them.
    scf.for %m = %c0 to %ctok step %c1 {{
      scf.for %i = %c0 to %cdim step %c1 {{
        %ii = arith.index_cast %i : index to i32
        %fi = arith.sitofp %ii : i32 to f32
        %mm = arith.index_cast %m : index to i32
        %fm = arith.sitofp %mm : i32 to f32
        %fi3 = arith.mulf %fi, %c3f : f32
        %fm7 = arith.mulf %fm, %c7f : f32
        %fim = arith.addf %fi3, %fm7 : f32
        %v0 = arith.remf %fim, %c11f : f32
        %v = arith.mulf %v0, %sixteenth : f32
        %v2 = arith.addf %v, %eighth : f32
        memref.store %v2, %X[%m, %i] : {AT}
        memref.store %v2, %X0[%m, %i] : {AT}
        memref.store %v2, %ref[%m, %i] : {AT}
        memref.store %fzero, %Rv[%m, %i] : {AT}
        memref.store %fzero, %Qv[%m, %i] : {AT}
        memref.store %fzero, %Av[%m, %i] : {AT}
        memref.store %fzero, %Aov[%m, %i] : {AT}
        memref.store %fzero, %Xa[%m, %i] : {AT}
      }}
      scf.for %i = %c0 to %c2inter step %c1 {{
        memref.store %fzero, %GU[%m, %i] : {GT}
      }}
      scf.for %i = %c0 to %cinter step %c1 {{
        memref.store %fzero, %Actv[%m, %i] : {IT}
      }}
      scf.for %t = %c0 to %ccache step %c1 {{
        memref.store %fzero, %Sv[%m, %t] : {ST}
        memref.store %fzero, %Pv[%m, %t] : {ST}
      }}
    }}

    // The norm weights. Not all ones -- a weight of one is a weight that is not
    // being tested.
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %i = %c0 to %cdim step %c1 {{
        %ii = arith.index_cast %i : index to i32
        %fi = arith.sitofp %ii : i32 to f32
        %ll = arith.index_cast %l : index to i32
        %fl = arith.sitofp %ll : i32 to f32
        %a0 = arith.addf %fi, %fl : f32
        %r0 = arith.remf %a0, %c3f : f32
        %d0 = arith.subf %r0, %fone : f32
        %s0 = arith.mulf %d0, %quarter : f32
        %n1 = arith.addf %fone, %s0 : f32
        memref.store %n1, %N1[%l, %i] : {NT}
        %a1 = arith.addf %a0, %fone : f32
        %r1 = arith.remf %a1, %c5f : f32
        %d1 = arith.subf %r1, %c2f : f32
        %s1 = arith.mulf %d1, %eighth : f32
        %n2 = arith.addf %fone, %s1 : f32
        memref.store %n2, %N2[%l, %i] : {NT}
      }}
    }}
""")

    # The raw weight patterns. Everything is `something % modulus`; the
    # centring pass below is what makes them usable.
    w(f"""
    scf.for %l = %c0 to %clayers step %c1 {{
      %ll = arith.index_cast %l : index to i32
      %fl = arith.sitofp %ll : i32 to f32
      scf.for %i = %c0 to %cdim step %c1 {{
        %ii = arith.index_cast %i : index to i32
        %fi = arith.sitofp %ii : i32 to f32
        scf.for %j = %c0 to %cdim step %c1 {{
          %jj = arith.index_cast %j : index to i32
          %fj = arith.sitofp %jj : i32 to f32
          %d = arith.subf %fi, %fj : f32
          %d2 = arith.addf %d, %fl : f32
          %d3 = arith.addf %d2, %fone : f32
          %rq = arith.remf %d3, %c{MOD_Q}f : f32
          memref.store %rq, %Wq[%l, %i, %j] : {WT}
          %ro = arith.remf %d3, %c{MOD_O}f : f32
          memref.store %ro, %Wo[%l, %i, %j] : {WT}
        }}
        scf.for %p = %c0 to %cinter step %c1 {{
          %pp = arith.index_cast %p : index to i32
          %fp = arith.sitofp %pp : i32 to f32
          %e = arith.subf %fi, %fp : f32
          %e2 = arith.addf %e, %fl : f32
          %rg = arith.remf %e2, %c{MOD_G}f : f32
          memref.store %rg, %Wgu[%l, %i, %p] : {WGT}
          %e3 = arith.addf %e2, %c3f : f32
          %ru = arith.remf %e3, %c{MOD_U}f : f32
          %pu = arith.addi %p, %cinter : index
          memref.store %ru, %Wgu[%l, %i, %pu] : {WGT}
        }}
      }}
      scf.for %p = %c0 to %cinter step %c1 {{
        %pp = arith.index_cast %p : index to i32
        %fp = arith.sitofp %pp : i32 to f32
        scf.for %j = %c0 to %cdim step %c1 {{
          %jj = arith.index_cast %j : index to i32
          %fj = arith.sitofp %jj : i32 to f32
          %f = arith.subf %fp, %fj : f32
          %f2 = arith.addf %f, %fl : f32
          %rd = arith.remf %f2, %c{MOD_D}f : f32
          memref.store %rd, %Wd[%l, %p, %j] : {WDT}
        }}
      }}
      // K varies with t*t, not t. With t+i every K row is a cyclic shift of one
      // pattern, so q.K[t] moves with t only through a shift correlation, the
      // softmax comes out nearly uniform, and the attention output stops
      // depending on the query at all.
      scf.for %t = %c0 to %ccache step %c1 {{
        %tt = arith.index_cast %t : index to i32
        %ft = arith.sitofp %tt : i32 to f32
        %ft2 = arith.mulf %ft, %ft : f32
        scf.for %i = %c0 to %cdim step %c1 {{
          %ii2 = arith.index_cast %i : index to i32
          %fi2 = arith.sitofp %ii2 : i32 to f32
          %fi3 = arith.mulf %fi2, %c3f : f32
          %ks = arith.addf %ft2, %fi3 : f32
          %ks2 = arith.addf %ks, %fl : f32
          %kr = arith.remf %ks2, %c{MOD_K}f : f32
          memref.store %kr, %Kc[%l, %t, %i] : {CT}
          %vs = arith.subf %ft, %fi2 : f32
          %vs2 = arith.addf %vs, %fone : f32
          %vr = arith.remf %vs2, %c{MOD_V}f : f32
          memref.store %vr, %Vc[%l, %t, %i] : {CT}
        }}
      }}
    }}
""")

    def centre(buf, mtype, red_const, red_len_const, out_const, scale, tag):
        """Subtract each column's mean along the reduction axis, then scale.

        `x % mod` lands in [0, mod), so an uncentred weight matrix is entirely
        non-negative and a matmul over it sums non-negative terms rather than
        taking a random walk. Subtracting a constant is not enough: the columns
        only sum to zero if the reduction length is a multiple of the modulus,
        and when it is not, the leftover DC term is multiplied by the mean of
        the activation and by the reduction length. That is what made the
        attention output swamp the residual it was supposed to perturb.
        Centring each column exactly costs one pass and leaves nothing behind.
        """
        return f"""
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %o_{tag} = %c0 to {out_const} step %c1 {{
        %sum_{tag} = scf.for %k_{tag} = %c0 to {red_const} step %c1
            iter_args(%acc_{tag} = %fzero) -> (f32) {{
          %v_{tag} = memref.load {buf}[%l, %k_{tag}, %o_{tag}] : {mtype}
          %a_{tag} = arith.addf %acc_{tag}, %v_{tag} : f32
          scf.yield %a_{tag} : f32
        }}
        %mu_{tag} = arith.divf %sum_{tag}, {red_len_const} : f32
        scf.for %k2_{tag} = %c0 to {red_const} step %c1 {{
          %v2_{tag} = memref.load {buf}[%l, %k2_{tag}, %o_{tag}] : {mtype}
          %d_{tag} = arith.subf %v2_{tag}, %mu_{tag} : f32
          %s_{tag} = arith.mulf %d_{tag}, {scale} : f32
          memref.store %s_{tag}, {buf}[%l, %k2_{tag}, %o_{tag}] : {mtype}
        }}
      }}
    }}"""

    for nm, val in (("sq", _uscale(MOD_Q)), ("so", _uscale(MOD_O)),
                    ("sg", _uscale(MOD_G)), ("su", _uscale(MOD_U)),
                    ("sd", _uscale(MOD_D)), ("sk", _uscale(MOD_K, 1.0)),
                    ("sv", _uscale(MOD_V))):
        w(f"\n    %{nm}c = arith.constant {val:.10e} : f32")
    # Wgu holds the gate half and the up half side by side and they come from
    # different moduli, so it is centred in two pieces.
    w(centre("%Wq", WT, "%cdim", "%fred_d", "%cdim", "%sqc", "wq"))
    w(centre("%Wo", WT, "%cdim", "%fred_d", "%cdim", "%soc", "wo"))
    w(f"""
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %o_gu = %c0 to %c2inter step %c1 {{
        %isup = arith.cmpi uge, %o_gu, %cinter : index
        %scl = arith.select %isup, %suc, %sgc : f32
        %sum_gu = scf.for %k_gu = %c0 to %cdim step %c1
            iter_args(%acc_gu = %fzero) -> (f32) {{
          %v_gu = memref.load %Wgu[%l, %k_gu, %o_gu] : {WGT}
          %a_gu = arith.addf %acc_gu, %v_gu : f32
          scf.yield %a_gu : f32
        }}
        %mu_gu = arith.divf %sum_gu, %fred_d : f32
        scf.for %k2_gu = %c0 to %cdim step %c1 {{
          %v2_gu = memref.load %Wgu[%l, %k2_gu, %o_gu] : {WGT}
          %d_gu = arith.subf %v2_gu, %mu_gu : f32
          %s_gu = arith.mulf %d_gu, %scl : f32
          memref.store %s_gu, %Wgu[%l, %k2_gu, %o_gu] : {WGT}
        }}
      }}
    }}""")
    w(centre("%Wd", WDT, "%cinter", "%fred_i", "%cdim", "%sdc", "wd"))
    w(centre("%Kc", CT, "%ccache", "%fred_c", "%cdim", "%skc", "kc"))
    w(centre("%Vc", CT, "%ccache", "%fred_c", "%cdim", "%svc", "vc"))

    # ---- host reference ----
    w(f"""

    %invsqrtd = arith.constant {invsqrtd:.8e} : f32
    %negbig = arith.constant -1.000000e30 : f32
    %refs = memref.alloc() : memref<{cache}xf32>
    %refq = memref.alloc() : memref<{dim}xf32>
    %refa = memref.alloc() : memref<{dim}xf32>
    %refao = memref.alloc() : memref<{dim}xf32>
    %refxa = memref.alloc() : memref<{dim}xf32>
    %refgu = memref.alloc() : memref<{2 * inter}xf32>
    %refact = memref.alloc() : memref<{inter}xf32>
    scf.for %l = %c0 to %clayers step %c1 {{
     scf.for %m = %c0 to %ctok step %c1 {{
      // 0: r = rmsnorm(x) * n1
      %ss = scf.for %i = %c0 to %cdim step %c1
          iter_args(%s = %fzero) -> (f32) {{
        %v = memref.load %ref[%m, %i] : {AT}
        %sq2 = arith.mulf %v, %v : f32
        %s2 = arith.addf %s, %sq2 : f32
        scf.yield %s2 : f32
      }}
      %mean = arith.divf %ss, %fdim : f32
      %me = arith.addf %mean, %eps : f32
      %rms = math.sqrt %me : f32
      scf.for %i = %c0 to %cdim step %c1 {{
        %v = memref.load %ref[%m, %i] : {AT}
        %nv = arith.divf %v, %rms : f32
        %nw = memref.load %N1[%l, %i] : {NT}
        %rv = arith.mulf %nv, %nw : f32
        memref.store %rv, %Rv[%m, %i] : {AT}
      }}
      // 1: q = r @ Wq
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %rv = memref.load %Rv[%m, %i] : {AT}
          %wv = memref.load %Wq[%l, %i, %j] : {WT}
          %mu = arith.mulf %rv, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refq[%j] : memref<{dim}xf32>
      }}
      // 2, 3: scores and softmax
      scf.for %t = %c0 to %ccache step %c1 {{
        %dot = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %qv = memref.load %refq[%i] : memref<{dim}xf32>
          %kv = memref.load %Kc[%l, %t, %i] : {CT}
          %mu = arith.mulf %qv, %kv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        %sc = arith.mulf %dot, %invsqrtd : f32
        memref.store %sc, %refs[%t] : memref<{cache}xf32>
      }}
      %mx = scf.for %t = %c0 to %ccache step %c1
          iter_args(%mv = %negbig) -> (f32) {{
        %v = memref.load %refs[%t] : memref<{cache}xf32>
        %m2 = arith.maxnumf %mv, %v : f32
        scf.yield %m2 : f32
      }}
      %sum = scf.for %t = %c0 to %ccache step %c1
          iter_args(%sm = %fzero) -> (f32) {{
        %v = memref.load %refs[%t] : memref<{cache}xf32>
        %d = arith.subf %v, %mx : f32
        %e = math.exp %d : f32
        memref.store %e, %refs[%t] : memref<{cache}xf32>
        %s2 = arith.addf %sm, %e : f32
        scf.yield %s2 : f32
      }}
      // 4: a = p @ V
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %t = %c0 to %ccache step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %e = memref.load %refs[%t] : memref<{cache}xf32>
          %pp = arith.divf %e, %sum : f32
          %vv = memref.load %Vc[%l, %t, %j] : {CT}
          %mu = arith.mulf %pp, %vv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refa[%j] : memref<{dim}xf32>
      }}
      // 5: ao = a @ Wo
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %av = memref.load %refa[%i] : memref<{dim}xf32>
          %wv = memref.load %Wo[%l, %i, %j] : {WT}
          %mu = arith.mulf %av, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refao[%j] : memref<{dim}xf32>
      }}
      // 6: xa = rmsnorm(x + ao) * n2
      %ssa = scf.for %j = %c0 to %cdim step %c1
          iter_args(%s = %fzero) -> (f32) {{
        %xv = memref.load %ref[%m, %j] : {AT}
        %av = memref.load %refao[%j] : memref<{dim}xf32>
        %xa = arith.addf %xv, %av : f32
        memref.store %xa, %refxa[%j] : memref<{dim}xf32>
        %sqa = arith.mulf %xa, %xa : f32
        %s2 = arith.addf %s, %sqa : f32
        scf.yield %s2 : f32
      }}
      %meana = arith.divf %ssa, %fdim : f32
      %mea = arith.addf %meana, %eps : f32
      %rmsa = math.sqrt %mea : f32
      scf.for %j = %c0 to %cdim step %c1 {{
        %xv = memref.load %refxa[%j] : memref<{dim}xf32>
        %nv = arith.divf %xv, %rmsa : f32
        %nw = memref.load %N2[%l, %j] : {NT}
        %xn = arith.mulf %nv, %nw : f32
        memref.store %xn, %refxa[%j] : memref<{dim}xf32>
      }}
      // 7: gu = xa @ Wgu
      scf.for %p = %c0 to %c2inter step %c1 {{
        %acc = scf.for %i = %c0 to %cdim step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %xv = memref.load %refxa[%i] : memref<{dim}xf32>
          %wv = memref.load %Wgu[%l, %i, %p] : {WGT}
          %mu = arith.mulf %xv, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        memref.store %acc, %refgu[%p] : memref<{2 * inter}xf32>
      }}
      // 8: act = silu(gate) * up
      scf.for %p = %c0 to %cinter step %c1 {{
        %gv = memref.load %refgu[%p] : memref<{2 * inter}xf32>
        %pu = arith.addi %p, %cinter : index
        %uv = memref.load %refgu[%pu] : memref<{2 * inter}xf32>
        %ng = arith.negf %gv : f32
        %eg = math.exp %ng : f32
        %de = arith.addf %fone, %eg : f32
        %si = arith.divf %gv, %de : f32
        %av = arith.mulf %si, %uv : f32
        memref.store %av, %refact[%p] : memref<{inter}xf32>
      }}
      // 9: x = xa + act @ Wd
      scf.for %j = %c0 to %cdim step %c1 {{
        %acc = scf.for %p = %c0 to %cinter step %c1
            iter_args(%s = %fzero) -> (f32) {{
          %av = memref.load %refact[%p] : memref<{inter}xf32>
          %wv = memref.load %Wd[%l, %p, %j] : {WDT}
          %mu = arith.mulf %av, %wv : f32
          %s2 = arith.addf %s, %mu : f32
          scf.yield %s2 : f32
        }}
        %xv = memref.load %refxa[%j] : memref<{dim}xf32>
        %nx = arith.addf %xv, %acc : f32
        memref.store %nx, %ref[%m, %j] : {AT}
      }}
     }}
    }}
    scf.for %m = %c0 to %ctok step %c1 {{
      scf.for %i = %c0 to %cdim step %c1 {{
        memref.store %fzero, %Rv[%m, %i] : {AT}
      }}
    }}
""")

    # ---- queues, events, device buffers ----
    w(f"""
    %Q = memref.alloc() : memref<{layers}x{qslots}xi32>
    %cq = arith.constant {qslots} : index
    scf.for %l = %c0 to %clayers step %c1 {{
      scf.for %k = %c0 to %cq step %c1 {{
        memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
      }}
    }}
    // Two-level event counting (persistent_kernel.cuh:1226-1251): workers add
    // into a counter only their own die touches, and the last one out flushes
    // the die's whole share to the device counter. Slots per (layer, stage,
    // die): the running total, then how many workers have finished, then one
    // word counting flushes so the host can see how many device-scope atomics
    // actually happened.
    %Loc = memref.alloc() : memref<{locwords}xi32>
    %cloc = arith.constant {locwords} : index
    scf.for %i = %c0 to %cloc step %c1 {{
      memref.store %zero, %Loc[%i] : memref<{locwords}xi32>
    }}
    %E = memref.alloc() : memref<{events}xi32>
    %ce = arith.constant {events} : index
    scf.for %i = %c0 to %ce step %c1 {{
      memref.store %zero, %E[%i] : memref<{events}xi32>
    }}

    %dX = gpu.alloc () : {AT}
    %dRv = gpu.alloc () : {AT}
    %dQv = gpu.alloc () : {AT}
    %dSv = gpu.alloc () : {ST}
    %dPv = gpu.alloc () : {ST}
    %dAv = gpu.alloc () : {AT}
    %dAov = gpu.alloc () : {AT}
    %dXa = gpu.alloc () : {AT}
    %dGU = gpu.alloc () : {GT}
    %dActv = gpu.alloc () : {IT}
    %dWq = gpu.alloc () : {WT}
    %dWo = gpu.alloc () : {WT}
    %dWgu = gpu.alloc () : {WGT}
    %dWd = gpu.alloc () : {WDT}
    %dKc = gpu.alloc () : {CT}
    %dVc = gpu.alloc () : {CT}
    %dN1 = gpu.alloc () : {NT}
    %dN2 = gpu.alloc () : {NT}
    %dQ = gpu.alloc () : memref<{layers}x{qslots}xi32>
    %dLoc = gpu.alloc () : memref<{locwords}xi32>
    %dE = gpu.alloc () : memref<{events}xi32>
    gpu.memcpy %dX, %X : {AT}, {AT}
    gpu.memcpy %dRv, %Rv : {AT}, {AT}
    gpu.memcpy %dQv, %Qv : {AT}, {AT}
    gpu.memcpy %dSv, %Sv : {ST}, {ST}
    gpu.memcpy %dPv, %Pv : {ST}, {ST}
    gpu.memcpy %dAv, %Av : {AT}, {AT}
    gpu.memcpy %dAov, %Aov : {AT}, {AT}
    gpu.memcpy %dXa, %Xa : {AT}, {AT}
    gpu.memcpy %dGU, %GU : {GT}, {GT}
    gpu.memcpy %dActv, %Actv : {IT}, {IT}
    gpu.memcpy %dWq, %Wq : {WT}, {WT}
    gpu.memcpy %dWo, %Wo : {WT}, {WT}
    gpu.memcpy %dWgu, %Wgu : {WGT}, {WGT}
    gpu.memcpy %dWd, %Wd : {WDT}, {WDT}
    gpu.memcpy %dKc, %Kc : {CT}, {CT}
    gpu.memcpy %dVc, %Vc : {CT}, {CT}
    gpu.memcpy %dN1, %N1 : {NT}, {NT}
    gpu.memcpy %dN2, %N2 : {NT}, {NT}
    gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
    gpu.memcpy %dLoc, %Loc : memref<{locwords}xi32>, memref<{locwords}xi32>
    gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>

    // --repeat runs the chain more than once so an external clock has
    // something to measure. Timing it from inside with mgpuEventRecord does not
    // work: the events go on the stream created here, while gpu-to-llvm puts
    // the kernel on one of its own, so the elapsed time is between two events
    // on an idle stream -- mgpuEventElapsedTime returns hipErrorInvalidHandle
    // and the number is garbage. The 4k GEMM test has the same problem.
    %crep = arith.constant {repeat} : index
    scf.for %rep = %c0 to %crep step %c1 {{
      scf.for %l = %c0 to %clayers step %c1 {{
        scf.for %k = %c0 to %cq step %c1 {{
          memref.store %zero, %Q[%l, %k] : memref<{layers}x{qslots}xi32>
        }}
      }}
      scf.for %i = %c0 to %ce step %c1 {{
        memref.store %zero, %E[%i] : memref<{events}xi32>
      }}
      scf.for %i = %c0 to %cloc step %c1 {{
        memref.store %zero, %Loc[%i] : memref<{locwords}xi32>
      }}
      gpu.memcpy %dQ, %Q : memref<{layers}x{qslots}xi32>, memref<{layers}x{qslots}xi32>
      gpu.memcpy %dLoc, %Loc : memref<{locwords}xi32>, memref<{locwords}xi32>
      gpu.memcpy %dE, %E : memref<{events}xi32>, memref<{events}xi32>
      // The chain rewrites x in place, so a second repetition would start from
      // the first one's output rather than the input.
      gpu.memcpy %dX, %X0 : {AT}, {AT}
      func.call @chain(%dQ, %dE, %dX, %dRv, %dQv, %dSv, %dPv, %dAv, %dAov,
                       %dXa, %dGU, %dActv, %dWq, %dWo, %dWgu, %dWd,
                       %dKc, %dVc, %dN1, %dN2, %dLoc)
        : (memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT}, {AT},
           {AT}, {ST}, {ST}, {AT}, {AT}, {AT}, {GT}, {IT},
           {WT}, {WT}, {WGT}, {WDT}, {CT}, {CT}, {NT}, {NT},
           memref<{locwords}xi32>) -> ()
    }}

    gpu.memcpy %X, %dX : {AT}, {AT}

    %tol = arith.constant 2.0e-2 : f32
    %bad = scf.for %m = %c0 to %ctok step %c1
        iter_args(%bo = %zero) -> (i32) {{
      %bi = scf.for %i = %c0 to %cdim step %c1
          iter_args(%b = %bo) -> (i32) {{
        %got = memref.load %X[%m, %i] : {AT}
        %want = memref.load %ref[%m, %i] : {AT}
        %d = arith.subf %got, %want : f32
        %ad = math.absf %d : f32
        %aw = math.absf %want : f32
        %sc = arith.maxnumf %aw, %fone : f32
        %rel = arith.divf %ad, %sc : f32
        %ok = arith.cmpf ole, %rel, %tol : f32
        %inc = arith.select %ok, %zero, %one : i32
        %b2 = arith.addi %b, %inc : i32
        scf.yield %b2 : i32
      }}
      scf.yield %bi : i32
    }}
    vector.print str "layers = "
    %nl = arith.constant {layers} : i32
    vector.print %nl : i32
    vector.print str "tokens = "
    %ntk = arith.constant {tokens} : i32
    vector.print %ntk : i32
    gpu.memcpy %Loc, %dLoc : memref<{locwords}xi32>, memref<{locwords}xi32>
    %cflush = arith.constant {flushword} : index
    %flushes = memref.load %Loc[%cflush] : memref<{locwords}xi32>
    vector.print str "device-scope event flushes = "
    vector.print %flushes : i32
    %cnaive = arith.constant {naive} : i32
    vector.print str "what signalling per worker would have been = "
    vector.print %cnaive : i32
    vector.print str "output elements differing from the reference = "
    vector.print %bad : i32
    return
  }}
""")

    # ---- device ----
    layer_consts = "\n".join(
        f"        %L{i} = arith.constant {i} : index" for i in range(layers))
    w(f"""
  func.func @chain(%Q: memref<{layers}x{qslots}xi32>, %E: memref<{events}xi32>,
                   %X: {AT}, %Rv: {AT}, %Qvb: {AT}, %Sv: {ST}, %Pv: {ST},
                   %Av: {AT}, %Aov: {AT}, %Xa: {AT}, %GU: {GT}, %Actv: {IT},
                   %Wq: {WT}, %Wo: {WT}, %Wgu: {WGT}, %Wd: {WDT},
                   %Kc: {CT}, %Vc: {CT}, %N1: {NT}, %N2: {NT},
                   %Loc: memref<{locwords}xi32>) {{
    %c1 = arith.constant 1 : index
    %cw = arith.constant {workers} : index
    air.launch (%bx, %by) in (%nbx=%cw, %nby=%c1)
        args(%q=%Q, %eb=%E, %x=%X, %r=%Rv, %qb=%Qvb, %sv=%Sv, %pv=%Pv,
             %av=%Av, %aov=%Aov, %xab=%Xa, %gub=%GU, %actb=%Actv,
             %wq=%Wq, %wo=%Wo, %wgu=%Wgu, %wd=%Wd, %kc=%Kc, %vc=%Vc,
             %n1=%N1, %n2=%N2, %loc=%Loc)
        : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT}, {AT},
          {AT}, {ST}, {ST}, {AT}, {AT}, {AT}, {GT}, {IT},
          {WT}, {WT}, {WGT}, {WDT}, {CT}, {CT}, {NT}, {NT},
          memref<{locwords}xi32> {{
      air.segment @worker args(%sq=%q, %se=%eb, %sx=%x, %sr=%r, %sqv=%qb,
                               %ssv=%sv, %spv=%pv, %sav=%av, %saov=%aov,
                               %sxa=%xab, %sgu=%gub, %sact=%actb,
                               %swq=%wq, %swo=%wo, %swgu=%wgu, %swd=%wd,
                               %skc=%kc, %svc=%vc, %sn1=%n1, %sn2=%n2,
                               %sloc=%loc)
          : memref<{layers}x{qslots}xi32>, memref<{events}xi32>, {AT}, {AT},
            {AT}, {ST}, {ST}, {AT}, {AT}, {AT}, {GT}, {IT},
            {WT}, {WT}, {WGT}, {WDT}, {CT}, {CT}, {NT}, {NT},
            memref<{locwords}xi32> {{
        %c0_s = arith.constant 0 : index
        %c1_s = arith.constant 1 : index
        %ctasks = arith.constant {tasks} : index
        %csliceD = arith.constant {slice_d} : index
        %csliceI = arith.constant {slice_i} : index
        %cslice2I = arith.constant {slice_2i} : index
        %cdim_s = arith.constant {dim} : index
        %cinter_s = arith.constant {inter} : index
        %one_s = arith.constant 1 : i32
        %zero_s = arith.constant 0 : i32
        %ctok_s = arith.constant {tokens} : index
        // A stage's pieces are the (token, n-slice) grid, so the event it
        // signals counts tokens * slices.
        %ntasks_t = arith.constant {tokens * tasks} : i32
        %ncache_t = arith.constant {tokens * cache} : i32
        %n1_s = arith.constant 1 : i32
        %fzero_s = arith.constant 0.0 : f32
        %fone_s = arith.constant 1.0 : f32
        %eps_s = arith.constant 1.0e-6 : f32
        %fdim_s = arith.constant {float(dim):.6e} : f32
        %invsqrtd_s = arith.constant {invsqrtd:.8e} : f32
        %negbig_s = arith.constant -1.000000e30 : f32
        %ccache_s = arith.constant {cache} : index
        %true = arith.constant true

        %tx_s = gpu.thread_id x
        %ty_s = gpu.thread_id y
        %tz_s = gpu.thread_id z
        %t01 = arith.ori %tx_s, %ty_s : index
        %t012 = arith.ori %t01, %tz_s : index
        %isLead = arith.cmpi eq, %t012, %c0_s : index
        // Which die this workgroup is on. Work is claimed per die so that the
        // slices a die computes are the ones its own cache is holding.
        %mydie_raw = air.chiplet_id
        %cmaxdies = arith.constant {maxdies} : index
        %mydie = arith.remui %mydie_raw, %cmaxdies : index
{layer_consts}
        %locbase = memref.extract_aligned_pointer_as_index %sloc : memref<{locwords}xi32> -> index
        %locbi = arith.index_cast %locbase : index to i64
        %locp = llvm.inttoptr %locbi : i64 to !llvm.ptr
        %fourL = arith.constant 4 : i64
        %cflushW = arith.constant {4 * flushword} : i64
        %flushP = llvm.getelementptr %locp[%cflushW] : (!llvm.ptr, i64) -> !llvm.ptr, i8
        %myrank2 = air.chiplet_block_id
        %mycnt = air.chiplet_dim_blocks
        %mycnt_i = arith.index_cast %mycnt : index to i32
        %evbase = memref.extract_aligned_pointer_as_index %se : memref<{events}xi32> -> index
        %evi = arith.index_cast %evbase : index to i64
        %evptr = llvm.inttoptr %evi : i64 to !llvm.ptr

        scf.if %isLead {{""")

    # A stage whose work splits into independent pieces. Each die has its own
    # head and its own stride of pieces, so what a die touches is what its cache
    # already holds. A die that runs out steals from the others, which is what
    # keeps this correct when the dispatcher does not use every die: locality is
    # a preference here, not an assumption.
    #
    # With `tokens` > 1 a piece is an (m, n) pair and the order the die walks
    # them in matters. Fleet sweeps M fast and N slow
    # (gang_linear_mi300.cuh:75-76, full-M-major so its window W is m_tiles):
    #
    #     m_tile = local % win_h        n_tile = local / win_h
    #
    # so `win_h` consecutive claims land on the same n -- the same block of
    # weight rows -- with different tokens. The block is read into the die's
    # cache once and serves all of them. Walking N fast instead computes the
    # same numbers while pulling a different weight block on every claim.
    #
    # Applied here to the die's own claim counter rather than a global tile id,
    # because that counter is what a die's workgroups share. At tokens == 1
    # this is m = 0, n = k, which is the index arithmetic the decode chain
    # already had.
    def strided_stage(l, stage, ev, count_expr, total_const, body):
        return f"""
          // stage {stage}
          %p{l}_{stage} = llvm.getelementptr %evptr[{4 * ev}] : (!llvm.ptr) -> !llvm.ptr, i8
          %hb{l}_{stage} = arith.constant {stage * maxdies} : index
          %t{l}_{stage} = scf.for %pp = %c0_s to %cmaxdies step %c1_s
              iter_args(%outer = %zero_s) -> (i32) {{
            // Own die first, then the others in order.
            %draw = arith.addi %mydie, %pp : index
            %d = arith.remui %draw, %cmaxdies : index
            %hidx = arith.addi %hb{l}_{stage}, %d : index
            %inner:2 = scf.while (%go = %true, %acc = %outer) : (i1, i32) -> (i1, i32) {{
              scf.condition(%go) %go, %acc : i1, i32
            }} do {{
            ^bb0(%g: i1, %acc: i32):
              %cl = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hidx] : (i32, memref<{layers}x{qslots}xi32>) -> i32
              %k = arith.index_cast %cl : i32 to index
              // M fast, N slow: the token moves every claim, the weight block
              // only every `tokens` claims.
              %m = arith.remui %k, %ctok_s : index
              %kn = arith.divui %k, %ctok_s : index
              %kstride = arith.muli %kn, %cmaxdies : index
              %ix = arith.addi %d, %kstride : index
              %has = arith.cmpi ult, %ix, {count_expr} : index
              %acc2 = scf.if %has -> i32 {{
{body}
                %n = arith.addi %acc, %one_s : i32
                scf.yield %n : i32
              }} else {{
                scf.yield %acc : i32
              }}
              scf.yield %has, %acc2 : i1, i32
            }}
            scf.yield %inner#1 : i32
          }}
          // Two-level: add into a counter only this die touches, then let the
          // last worker on the die flush the die's whole share once. The
          // instructions are the same as signalling per worker; what changes is
          // how many times the device-scope one runs.
          %lw{l}_{stage} = arith.constant {4 * (((l) * stages + (stage)) * maxdies)} : i64
          %myd{l}_{stage} = arith.index_cast %mydie : index to i64
          %myd4{l}_{stage} = arith.muli %myd{l}_{stage}, %fourL : i64
          %lo{l}_{stage} = arith.addi %lw{l}_{stage}, %myd4{l}_{stage} : i64
          %locP{l}_{stage} = llvm.getelementptr %locp[%lo{l}_{stage}] : (!llvm.ptr, i64) -> !llvm.ptr, i8
          %aw{l}_{stage} = arith.constant {4 * slots} : i64
          %ao{l}_{stage} = arith.addi %aw{l}_{stage}, %lo{l}_{stage} : i64
          %arrP{l}_{stage} = llvm.getelementptr %locp[%ao{l}_{stage}] : (!llvm.ptr, i64) -> !llvm.ptr, i8
          %la{l}_{stage} = llvm.atomicrmw add %locP{l}_{stage}, %t{l}_{stage} syncscope("agent") monotonic : !llvm.ptr, i32
          // Release on the arrival so the accumulate above is visible to
          // whoever turns out to be last.
          %ar{l}_{stage} = llvm.atomicrmw add %arrP{l}_{stage}, %one_s syncscope("agent") release : !llvm.ptr, i32
          %last{l}_{stage} = arith.subi %mycnt_i, %one_s : i32
          %amLast{l}_{stage} = arith.cmpi eq, %ar{l}_{stage}, %last{l}_{stage} : i32
          scf.if %amLast{l}_{stage} {{
            %tot{l}_{stage} = llvm.load %locP{l}_{stage} atomic syncscope("agent") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %sig{l}_{stage} = llvm.atomicrmw add %p{l}_{stage}, %tot{l}_{stage} syncscope("") release : !llvm.ptr, i32
            %cnt{l}_{stage} = llvm.atomicrmw add %flushP, %one_s syncscope("") monotonic : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_{stage} atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, {total_const} : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}"""

    def single_stage(l, stage, ev, body):
        return f"""
          // stage {stage} -- one task: it reduces, so it cannot be split by
          // output slice the way the matmuls can.
          %hsingle{stage}_{l} = arith.constant {stage * maxdies} : index
          %p{l}_{stage} = llvm.getelementptr %evptr[{4 * ev}] : (!llvm.ptr) -> !llvm.ptr, i8
          %cl{l}_{stage} = memref.atomic_rmw addi %one_s, %sq[%L{l}, %hsingle{stage}_{l}] : (i32, memref<{layers}x{qslots}xi32>) -> i32
          %mine{l}_{stage} = arith.cmpi eq, %cl{l}_{stage}, %zero_s : i32
          scf.if %mine{l}_{stage} {{
            scf.for %m = %c0_s to %ctok_s step %c1_s {{
{body}
            }}
            %sig{l}_{stage} = llvm.atomicrmw add %p{l}_{stage}, %n1_s syncscope("") release : !llvm.ptr, i32
          }}
          scf.while : () -> () {{
            %seen = llvm.load %p{l}_{stage} atomic syncscope("") acquire {{alignment = 4 : i64}} : !llvm.ptr -> i32
            %notYet = arith.cmpi ult, %seen, %n1_s : i32
            scf.condition(%notYet)
          }} do {{
            scf.yield
          }}"""

    # The weights are read once per layer and never again inside a decode step,
    # and they are far larger than anything else in flight, so they are exactly
    # what would evict the activations. Fleet loads them non-temporally too
    # (gang_ksplit_linear_mi300.cuh:88 uses amd_buffer_coherence_enum(18),
    # which is nt|sc1). The activations are deliberately left alone.
    def matmul_stage(l, stage, ev, out, outty, lhs, lhsty, wmat, wty,
                     slice_c, red_c, count_expr, total_const, residual=None):
        res = ""
        if residual:
            res = f"""
                  %rv = memref.load {residual}[%m, %j] : {outty}
                  %a2 = arith.addf %rv, %a : f32
                  memref.store %a2, {out}[%m, %j] : {outty}"""
        else:
            res = f"""
                  memref.store %a, {out}[%m, %j] : {outty}"""
        return strided_stage(l, stage, ev, count_expr, total_const, f"""                %j0 = arith.muli %ix, {slice_c} : index
                scf.for %jj = %c0_s to {slice_c} step %c1_s {{
                  %j = arith.addi %j0, %jj : index
                  %a = scf.for %i = %c0_s to {red_c} step %c1_s
                      iter_args(%sacc = %fzero_s) -> (f32) {{
                    %lv = memref.load {lhs}[%m, %i] : {lhsty}
                    %wv = memref.load {wmat}[%L{l}, %i, %j] {{nontemporal = true}} : {wty}
                    %mp = arith.mulf %lv, %wv : f32
                    %s2 = arith.addf %sacc, %mp : f32
                    scf.yield %s2 : f32
                  }}{res}
                }}""")

    for l in range(layers):
        base = stages * l
        w(f"\n          // ================= layer {l} =================")

        # 0: r = rmsnorm(x) * n1
        w(single_stage(l, 0, base + 0, f"""              %ss{l} = scf.for %i = %c0_s to %cdim_s step %c1_s
                  iter_args(%s = %fzero_s) -> (f32) {{
                %v = memref.load %sx[%m, %i] : {AT}
                %sq2 = arith.mulf %v, %v : f32
                %s2 = arith.addf %s, %sq2 : f32
                scf.yield %s2 : f32
              }}
              %mean{l} = arith.divf %ss{l}, %fdim_s : f32
              %me{l} = arith.addf %mean{l}, %eps_s : f32
              %rms{l} = math.sqrt %me{l} : f32
              scf.for %i = %c0_s to %cdim_s step %c1_s {{
                %v = memref.load %sx[%m, %i] : {AT}
                %nv = arith.divf %v, %rms{l} : f32
                %nw = memref.load %sn1[%L{l}, %i] : {NT}
                %rv = arith.mulf %nv, %nw : f32
                memref.store %rv, %sr[%m, %i] : {AT}
              }}"""))

        # 1: q = r @ Wq
        w(matmul_stage(l, 1, base + 1, "%sqv", AT, "%sr", AT, "%swq", WT,
                       "%csliceD", "%cdim_s", "%ctasks", "%ntasks_t"))

        # 2: one score per cache entry
        w(strided_stage(l, 2, base + 2, "%ccache_s", "%ncache_t",
                        f"""                %dot = scf.for %i = %c0_s to %cdim_s step %c1_s
                    iter_args(%sdot = %fzero_s) -> (f32) {{
                  %qv2 = memref.load %sqv[%m, %i] : {AT}
                  %kv = memref.load %skc[%L{l}, %ix, %i] {{nontemporal = true}} : {CT}
                  %mp = arith.mulf %qv2, %kv : f32
                  %s2 = arith.addf %sdot, %mp : f32
                  scf.yield %s2 : f32
                }}
                %sc = arith.mulf %dot, %invsqrtd_s : f32
                memref.store %sc, %ssv[%m, %ix] : {ST}"""))

        # 3: softmax
        w(single_stage(l, 3, base + 3, f"""              %mx{l} = scf.for %t = %c0_s to %ccache_s step %c1_s
                  iter_args(%mv = %negbig_s) -> (f32) {{
                %v = memref.load %ssv[%m, %t] : {ST}
                %m2 = arith.maxnumf %mv, %v : f32
                scf.yield %m2 : f32
              }}
              %sum{l} = scf.for %t = %c0_s to %ccache_s step %c1_s
                  iter_args(%sm = %fzero_s) -> (f32) {{
                %v = memref.load %ssv[%m, %t] : {ST}
                %d = arith.subf %v, %mx{l} : f32
                %e = math.exp %d : f32
                memref.store %e, %spv[%m, %t] : {ST}
                %s2 = arith.addf %sm, %e : f32
                scf.yield %s2 : f32
              }}
              scf.for %t = %c0_s to %ccache_s step %c1_s {{
                %en = memref.load %spv[%m, %t] : {ST}
                %pn = arith.divf %en, %sum{l} : f32
                memref.store %pn, %spv[%m, %t] : {ST}
              }}"""))

        # 4: a = p @ V
        w(strided_stage(l, 4, base + 4, "%ctasks", "%ntasks_t",
                        f"""                %j0 = arith.muli %ix, %csliceD : index
                scf.for %jj = %c0_s to %csliceD step %c1_s {{
                  %j = arith.addi %j0, %jj : index
                  %a = scf.for %t = %c0_s to %ccache_s step %c1_s
                      iter_args(%sacc = %fzero_s) -> (f32) {{
                    %pn = memref.load %spv[%m, %t] : {ST}
                    %vv = memref.load %svc[%L{l}, %t, %j] {{nontemporal = true}} : {CT}
                    %mp = arith.mulf %pn, %vv : f32
                    %s2 = arith.addf %sacc, %mp : f32
                    scf.yield %s2 : f32
                  }}
                  memref.store %a, %sav[%m, %j] : {AT}
                }}"""))

        # 5: ao = a @ Wo
        w(matmul_stage(l, 5, base + 5, "%saov", AT, "%sav", AT, "%swo", WT,
                       "%csliceD", "%cdim_s", "%ctasks", "%ntasks_t"))

        # 6: xa = rmsnorm(x + ao) * n2. The norm in front of the MLP is not
        # decoration: without it nothing renormalises the residual stream --
        # stage 0's rmsnorm feeds only the q projection -- so the stream grows
        # or decays geometrically with depth, and since the host comparison is
        # relative, a stream in the thousands hides every error smaller than
        # itself.
        w(single_stage(l, 6, base + 6, f"""              %ssa{l} = scf.for %i = %c0_s to %cdim_s step %c1_s
                  iter_args(%s = %fzero_s) -> (f32) {{
                %xv = memref.load %sx[%m, %i] : {AT}
                %avv = memref.load %saov[%m, %i] : {AT}
                %xa = arith.addf %xv, %avv : f32
                memref.store %xa, %sxa[%m, %i] : {AT}
                %sqa = arith.mulf %xa, %xa : f32
                %s2 = arith.addf %s, %sqa : f32
                scf.yield %s2 : f32
              }}
              %meana{l} = arith.divf %ssa{l}, %fdim_s : f32
              %mea{l} = arith.addf %meana{l}, %eps_s : f32
              %rmsa{l} = math.sqrt %mea{l} : f32
              scf.for %i = %c0_s to %cdim_s step %c1_s {{
                %xv3 = memref.load %sxa[%m, %i] : {AT}
                %nv = arith.divf %xv3, %rmsa{l} : f32
                %nw = memref.load %sn2[%L{l}, %i] : {NT}
                %xn = arith.mulf %nv, %nw : f32
                memref.store %xn, %sxa[%m, %i] : {AT}
              }}"""))

        # 7: gu = xa @ Wgu, gate and up in one matmul as Fleet fuses them
        w(matmul_stage(l, 7, base + 7, "%sgu", GT, "%sxa", AT, "%swgu", WGT,
                       "%cslice2I", "%cdim_s", "%ctasks", "%ntasks_t"))

        # 8: SwiGLU. Elementwise, so a piece is a slice of the intermediate
        # width rather than a reduction.
        w(strided_stage(l, 8, base + 8, "%ctasks", "%ntasks_t",
                        f"""                %j0 = arith.muli %ix, %csliceI : index
                scf.for %jj = %c0_s to %csliceI step %c1_s {{
                  %j = arith.addi %j0, %jj : index
                  %gv = memref.load %sgu[%m, %j] : {GT}
                  %ju = arith.addi %j, %cinter_s : index
                  %uv = memref.load %sgu[%m, %ju] : {GT}
                  %ng = arith.negf %gv : f32
                  %eg = math.exp %ng : f32
                  %de = arith.addf %fone_s, %eg : f32
                  %si = arith.divf %gv, %de : f32
                  %actv = arith.mulf %si, %uv : f32
                  memref.store %actv, %sact[%m, %j] : {IT}
                }}"""))

        # 9: x = xa + act @ Wd, the residual folded into the matmul as Fleet
        # folds it (linear_with_residual_layer).
        w(matmul_stage(l, 9, base + 9, "%sx", AT, "%sact", IT, "%swd", WDT,
                       "%csliceD", "%cinter_s", "%ctasks", "%ntasks_t",
                       residual="%sxa"))

    w(f"""
        }}

        air.herd @herd tile (%htx, %hty) in (%ntx=%c1_s, %nty=%c1_s) {{
        }}
      }}
    }}
    return
  }}
}}
""")
    return "".join(o)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--layers", type=int, default=4)
    ap.add_argument("--dim", type=int, default=128)
    ap.add_argument("--inter", type=int, default=0,
                    help="MLP intermediate width; defaults to 2*dim")
    ap.add_argument("--tasks", type=int, default=8,
                    help="tasks per matmul stage; dim and inter must divide by this")
    ap.add_argument("--workers", type=int, default=32,
                    help="resident workgroups; must fit the device at once")
    ap.add_argument("--cache", type=int, default=32,
                    help="KV cache length the attention stage reads")
    ap.add_argument("--tokens", type=int, default=1,
                    help="tokens in flight (M). 1 is a decode step; >1 is a "
                         "prefill or speculative window, and is what makes the "
                         "M-major traversal do anything")
    ap.add_argument("--repeat", type=int, default=1,
                    help="how many times to launch the chain, for timing: "
                         "--layers 36 --repeat 1 is one launch doing 36 layers, "
                         "--layers 1 --repeat 36 is 36 launches doing one each")
    a = ap.parse_args()
    sys.stdout.write(emit(a.layers, a.dim, a.tasks, a.workers, a.repeat,
                          a.cache, a.tokens, a.inter))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
