##===- utils/env_setup.sh - Setup mlir-aie env post build to compile mlir-aie designs --*- Script -*-===##
# 
# This file licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# 
##===----------------------------------------------------------------------===##
#
# This script sets up the environment to run the mlir-aie build tools.
# It must be sourced, not executed.
#
# e.g. source env_setup.sh /scratch/mlir-air/install /scratch/mlir-aie/install /scratch/llvm/install
#
##===----------------------------------------------------------------------===##

# a configuration file contains the necessary variables to find the necessary tools and libraries
config_file=${CONFIG:-"env_config"}
echo "Using configuration file $config_file"

# load the configuration file if it exists. If not, the user must provide the
# paths on the command line, and those are written to a new file for next time.
if [[ ! -f $config_file ]]; then
	if [ "$#" -ne 3 ]; then
		echo "ERROR: Needs 3 arguments for <mlir-air install dir> <mlir-aie install dir> and <llvm install dir>"
		return
	fi

	MLIR_AIR_INSTALL_DIR=$1
	MLIR_AIE_INSTALL_DIR=$2
	LLVM_INSTALL_DIR=$3

	echo "# Configuration file auto-generated by $0, but you can edit it!" > $config_file
	echo "" > $config_file
	echo "MLIR_AIR_INSTALL_DIR=$MLIR_AIR_INSTALL_DIR # location of AIR" >> $config_file
	echo "MLIR_AIE_INSTALL_DIR=$MLIR_AIE_INSTALL_DIR # location of AIE" >> $config_file
	echo "LLVM_INSTALL_DIR=$LLVM_INSTALL_DIR # location of LLVM" >> $config_file
	echo "Wrote configuration to $config_file"
fi

# Source env variables
source $config_file

# set up the paths
export PATH=${MLIR_AIR_INSTALL_DIR}/bin:${MLIR_AIE_INSTALL_DIR}/bin:${LLVM_INSTALL_DIR}/bin:${PATH} 
export PYTHONPATH=${MLIR_AIR_INSTALL_DIR}/python:${MLIR_AIE_INSTALL_DIR}/python:${PYTHONPATH} 
export LD_LIBRARY_PATH=${MLIR_AIR_INSTALL_DIR}/lib:${MLIR_AIE_INSTALL_DIR}/lib:${LLVM_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}
