# ./python/air/compiler/aircc/main.py -*- Python -*-
#
# Copyright (C) 2022, Xilinx Inc.
# Copyright (C) 2022, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""
aircc - AIR compiler driver for MLIR tools
"""

import os
import platform
import sys
import subprocess
import shutil
import tempfile

import air.compiler.aircc.cl_arguments as cl_arguments
from air.compiler.aircc.configure import *

# Import AIR Python bindings at module level to ensure the air dialect
# is registered. Other modules (e.g. xrt.py) import aircc which triggers
# this registration as a side effect.
try:
    from air.passmanager import PassManager
    from air.ir import Module, Context, Location
    from air.dialects import air as airdialect
except ImportError:
    pass  # GPU-only builds may not have AIR Python bindings

# Pass logging for documenting which passes are called
_pass_counter = 0
_pass_log = []
_debug_ir_dir = None


def get_pass_log():
    """Return list of all passes executed."""
    return _pass_log


def dump_pass_log(log_file):
    """Write pass log to a file for documentation purposes."""
    with open(log_file, "w") as f:
        f.write("# MLIR-AIR Compilation Pass Log\n")
        f.write("# Generated by aircc\n")
        f.write("#\n")
        f.write(
            "# NOTE: Each pass_XXX_after_*.mlir file shows the IR AFTER that pass is applied.\n"
        )
        f.write(
            "# CHECKPOINT markers indicate which debug IR files correspond to the\n"
        )
        f.write(
            "# standard output files (placed.air.mlir, aie.air.mlir, npu.air.mlir).\n"
        )
        f.write("#\n\n")
        for entry in _pass_log:
            if entry.get("is_checkpoint"):
                f.write(f"\n{'='*70}\n")
                f.write(f"CHECKPOINT: {entry['pass_name']}\n")
                f.write(f"  This is equivalent to: {entry['equivalent_file']}\n")
                f.write(f"  Debug IR file: {entry.get('outputfile', 'N/A')}\n")
                f.write(f"{'='*70}\n\n")
            else:
                f.write(f"[PASS {entry['index']:03d}] {entry['pass_name']}\n")
                if entry.get("outputfile"):
                    f.write(f"  -> Output: {entry['outputfile']}\n")


def reset_pass_log():
    """Reset pass counter and log."""
    global _pass_counter, _pass_log, _debug_ir_dir
    _pass_counter = 0
    _pass_log = []
    _debug_ir_dir = None


def setup_debug_ir_dir(tmpdir):
    """Setup debug IR directory for fine-grained IR output."""
    global _debug_ir_dir
    _debug_ir_dir = os.path.join(tmpdir, "debug_ir")
    os.makedirs(_debug_ir_dir, exist_ok=True)
    return _debug_ir_dir


def split_pipeline_to_passes(pipeline):
    """Split a pass pipeline string into individual passes.

    Handles complex cases like:
    - Simple: "canonicalize,cse"
    - With args: "air-to-aie{emit-while-loop=true}"
    - Nested: "func.func(air-split-l2-memref)"
    - Combined: "func.func(air-opt-memtile-dma-bds{device=npu2})"

    Args:
        pipeline: Pass pipeline string (e.g., "builtin.module(pass1,pass2,...)")

    Returns:
        List of individual pass strings with proper wrapping
    """
    # Remove builtin.module() wrapper if present
    if pipeline.startswith("builtin.module(") and pipeline.endswith(")"):
        inner = pipeline[len("builtin.module(") : -1]
    else:
        inner = pipeline

    # Parse the inner passes, respecting nested parentheses and braces
    passes = []
    current_pass = ""
    depth = 0  # Track nesting depth for () and {}

    for char in inner:
        if char in "({":
            depth += 1
            current_pass += char
        elif char in ")}":
            depth -= 1
            current_pass += char
        elif char == "," and depth == 0:
            # Top-level comma - end of current pass
            if current_pass.strip():
                passes.append(current_pass.strip())
            current_pass = ""
        else:
            current_pass += char

    # Don't forget the last pass
    if current_pass.strip():
        passes.append(current_pass.strip())

    return passes


def get_pass_short_name(pass_str):
    """Extract a short name from a pass string for filename use.

    Examples:
    - "canonicalize" -> "canonicalize"
    - "air-to-aie{emit-while-loop=true...}" -> "air-to-aie"
    - "func.func(air-split-l2-memref)" -> "func.func_air-split-l2-memref"
    """
    # Remove arguments in braces
    name = pass_str.split("{")[0]
    # Replace parentheses with underscores for nested passes
    name = name.replace("(", "_").replace(")", "")
    # Clean up any trailing underscores
    name = name.rstrip("_")
    return name


def save_initial_ir(mlir_module, opts):
    """Save the initial IR before any passes are applied (in debug mode)."""
    global _pass_log, _debug_ir_dir

    if _debug_ir_dir:
        ir_file = os.path.join(_debug_ir_dir, "pass_000_initial_input.mlir")
        with open(ir_file, "w") as f:
            f.write(str(mlir_module))

        entry = {
            "index": 0,
            "pass_name": "[Initial IR before passes]",
            "outputfile": ir_file,
        }
        _pass_log.append(entry)

        if opts.verbose:
            print(f"[PASS 000] Saved initial IR to {ir_file}")


def add_checkpoint(checkpoint_name, equivalent_file, last_pass_output=None):
    """Add a checkpoint marker to the pass log."""
    global _pass_log
    entry = {
        "index": -1,
        "pass_name": checkpoint_name,
        "is_checkpoint": True,
        "equivalent_file": equivalent_file,
        "outputfile": last_pass_output,
    }
    _pass_log.append(entry)


def do_call(command, opts):
    """Execute a command and exit on failure."""
    if opts.verbose:
        print(" ".join(command))
    ret = subprocess.call(command)
    if ret != 0:
        print("Error encountered while running: " + " ".join(command))
        sys.exit(1)


def do_run(command, opts):
    """Execute a command and return the result."""
    if opts.verbose:
        print(" ".join(command))
    ret = subprocess.run(
        command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True
    )
    return ret


def run_gpu_compilation(opts):
    """
    GPU compilation pipeline using subprocess calls.
    Does not require Python bindings or AIE.

    Pipeline:
    1. air-opt -air-to-rocdl
    2. air-opt -air-gpu-outlining
    3. mlir-opt: lower-affine, convert-linalg-to-loops, convert-scf-to-cf, gpu-kernel-outlining
    4. mlir-opt: rocdl-attach-target, convert-gpu-to-rocdl, gpu-module-to-binary, gpu-to-llvm, convert-to-llvm
    """
    input_file = opts.air_mlir_file
    _, input_filename = os.path.split(input_file)
    base_name = os.path.splitext(input_filename)[0]

    # Create tmpdir if needed
    if opts.tmpdir:
        tmpdirname = opts.tmpdir
        try:
            os.mkdir(tmpdirname)
        except FileExistsError:
            pass
    else:
        tmpdirname = tempfile.mkdtemp(prefix="aircc_gpu_")

    if opts.verbose:
        print(f"GPU compilation for {input_file}")
        print(f"  Architecture: {opts.gpu_arch}")
        print(f"  Runtime: {opts.gpu_runtime}")
        print(f"  Tmpdir: {tmpdirname}")

    # Find tools
    air_opt = shutil.which("air-opt")
    mlir_opt = shutil.which("mlir-opt")

    if not air_opt:
        print("Error: could not find air-opt in PATH")
        sys.exit(1)
    if not mlir_opt:
        print("Error: could not find mlir-opt in PATH")
        sys.exit(1)

    # Step 1: AIR to ROCDL
    step1_output = os.path.join(tmpdirname, f"{base_name}_step1_rocdl.mlir")
    do_call([air_opt, input_file, "-air-to-rocdl", "-o", step1_output], opts)

    # Step 2: GPU Kernel Outlining (AIR-specific)
    step2_output = os.path.join(tmpdirname, f"{base_name}_step2_outlined.mlir")
    do_call([air_opt, step1_output, "-air-gpu-outlining", "-o", step2_output], opts)

    # Step 3: LLVM Lowering + GPU kernel outlining
    step3_output = os.path.join(tmpdirname, f"{base_name}_step3_gpu.mlir")
    do_call(
        [
            mlir_opt,
            step2_output,
            "--pass-pipeline=builtin.module(func.func(lower-affine, convert-linalg-to-loops, convert-scf-to-cf), gpu-kernel-outlining)",
            "-o",
            step3_output,
        ],
        opts,
    )

    # Step 4: ROCDL Binary Generation
    # Build the pass pipeline for GPU binary generation
    gpu_pipeline = (
        f"builtin.module("
        f"rocdl-attach-target{{chip={opts.gpu_arch} O=3}},"
        f"gpu.module(convert-gpu-to-rocdl{{chipset={opts.gpu_arch} runtime={opts.gpu_runtime}}},reconcile-unrealized-casts),"
        f"gpu-module-to-binary,"
        f"func.func(gpu-async-region),"
        f"gpu-to-llvm,"
        f"convert-to-llvm,"
        f"reconcile-unrealized-casts"
        f")"
    )

    # Determine output file
    if opts.output_file:
        final_output = opts.output_file
    else:
        final_output = os.path.join(tmpdirname, f"{base_name}_final.mlir")

    do_call(
        [mlir_opt, step3_output, f"--pass-pipeline={gpu_pipeline}", "-o", final_output],
        opts,
    )

    if opts.verbose:
        print(f"\nGPU compilation complete!")
        print(f"Output: {final_output}")
        if opts.tmpdir:
            print(f"Intermediate files in: {tmpdirname}")

    # Print to stdout if no output file specified
    if not opts.output_file:
        with open(final_output, "r") as f:
            print(f.read())


def run_aie_compilation(opts, mlir_module=None):
    """
    AIE compilation pipeline using Python bindings.
    Requires MLIR Python bindings and AIE support.
    """
    # Import AIR Python bindings (needed for all AIE compilation)
    # Note: aiecc is imported later, just before use, to avoid loading
    # libAIEAggregateCAPI.so before air-to-std runs. Loading both CAPI
    # libraries simultaneously causes duplicate MLIR TypeID conflicts.
    try:
        from air.passmanager import PassManager
        from air.ir import Module, Context, Location
        from air.dialects import air as airdialect
    except ImportError as e:
        print(
            f"Error: AIE compilation requires Python bindings which are not available."
        )
        print(f"       Import error: {e}")
        print(f"       ")
        print(f"       For GPU compilation, use: aircc.py --target gpu ...")
        print(f"       For AIE compilation, rebuild with Python bindings enabled.")
        sys.exit(1)

    # Import the rest of the AIE-specific functions
    from joblib import Parallel, delayed

    def get_L2_splitting_analysis_pass():
        L2_SPLITTING_PASSES = [
            "func.func(air-split-l2-memref)",
            "canonicalize",
            "cse",
            "air-isolate-async-dma-loop-nests",
            "canonicalize",
            "cse",
        ]
        return L2_SPLITTING_PASSES

    def get_air_optimization_pass(
        device,
        omit_pingpong="",
        lower_linalg_to_func=None,
        air_loop_fusion=False,
        omit_auto_broadcast=False,
        channel_multiplexing=[],
    ):
        OPTIMIZATION_PASSES = [
            "air-dependency",
            "air-hoist-dma-in-accum-pattern",
        ]
        if not omit_auto_broadcast:
            OPTIMIZATION_PASSES += [
                "air-broadcast-detection",
                "air-specialize-dma-broadcast",
            ]
        OPTIMIZATION_PASSES += [
            "air-dma-to-channel",
            "canonicalize",
            "cse",
            "air-dependency-canonicalize",
            "canonicalize",
            "cse",
            "air-isolate-async-dma-loop-nests",
            "canonicalize",
            "cse",
        ]
        if len(channel_multiplexing) != 0:
            OPTIMIZATION_PASSES += [
                "air-fuse-channels{aggressive-mode="
                + ",".join(s for s in channel_multiplexing)
                + "}",
            ]
        else:
            OPTIMIZATION_PASSES += [
                "air-fuse-channels",
            ]
        OPTIMIZATION_PASSES += [
            "canonicalize",
            "cse",
        ]
        if "npu_1col" not in device:
            OPTIMIZATION_PASSES += get_L2_splitting_analysis_pass()
        if air_loop_fusion:
            OPTIMIZATION_PASSES += [
                "func.func(air-loop-fusion)",
            ]
        else:
            OPTIMIZATION_PASSES += [
                "func.func(air-fuse-alloc-dealloc)",
                "func.func(air-shrink-memref-sizes-by-access)",
            ]
        if omit_pingpong in ["", "L1", "L2"]:
            label_pass = "air-label-scf-for-to-ping-pong"
            ping_pong_pass = "air-ping-pong-transform"
            if omit_pingpong in ["L1", "L2"]:
                label_pass = f"air-label-scf-for-to-ping-pong{{omit-memory-space={omit_pingpong}}}"
                ping_pong_pass = (
                    f"air-ping-pong-transform{{omit-memory-space={omit_pingpong}}}"
                )
            OPTIMIZATION_PASSES += [
                label_pass,
                ping_pong_pass,
                "canonicalize",
                "cse",
            ]
        if lower_linalg_to_func != None:
            OPTIMIZATION_PASSES += [
                "air-linalg-to-func{link-with=" + f"{lower_linalg_to_func}" + "}",
            ]
        else:
            OPTIMIZATION_PASSES += [
                "func.func(convert-linalg-to-loops)",
            ]

        OPTIMIZATION_PASSES += [
            "func.func(air-opt-memtile-dma-bds{" + f"device={device}" + "})",
            "canonicalize",
            "cse",
        ]
        return OPTIMIZATION_PASSES

    def emit_wrapper(herd_name="segment", include_name="aie.inc"):
        s = """// generated by aircc, do not edit
#include "stdio.h"
#include "assert.h"
#include "air_host.h"
#include "air_host_impl.h"

namespace air {
namespace segments {
"""
        s = s + f"namespace {herd_name} {{\n"
        s = s + f'#include "{include_name}"'
        s = s + """
}
}
}
"""
        s = s + f"using namespace air::segments::{herd_name};"
        s = s + """
extern "C" {
"""
        s = s + f"air_rt_aie_functions_t __airrt_{herd_name}_aie_functions {{"
        s = s + """
  .configure_cores = &mlir_aie_configure_cores,
  .configure_switchboxes = &mlir_aie_configure_switchboxes,
  .initialize_locks = &mlir_aie_initialize_locks,
  .configure_dmas = &mlir_aie_configure_dmas,
  .start_cores = &mlir_aie_start_cores
};
}
"""
        return s

    def run_single_pass(pass_str, mlir_module, opts):
        """Run a single MLIR pass and save IR in debug mode."""
        global _pass_counter, _pass_log, _debug_ir_dir
        _pass_counter += 1

        short_name = get_pass_short_name(pass_str)
        entry = {"index": _pass_counter, "pass_name": pass_str, "outputfile": None}

        if opts.verbose:
            print(f"[PASS {_pass_counter:03d}] {pass_str}")

        full_pipeline = f"builtin.module({pass_str})"
        PassManager.parse(full_pipeline).run(mlir_module.operation)

        if _debug_ir_dir:
            ir_file = os.path.join(
                _debug_ir_dir, f"pass_{_pass_counter:03d}_after_{short_name}.mlir"
            )
            with open(ir_file, "w") as f:
                f.write(str(mlir_module))
            entry["outputfile"] = ir_file

            pass_log_file = os.path.join(_debug_ir_dir, "pass.log")
            dump_pass_log(pass_log_file)

        _pass_log.append(entry)

    def run_passes(pass_pipeline, mlir_module, opts, outputfile=None):
        """Run MLIR pass pipeline and optionally save the result.

        In normal mode: runs the entire pipeline as one unit.
        In debug mode (opts.debug_ir): splits the pipeline and runs each pass
        individually, saving IR after each pass for fine-grained inspection.
        """
        global _pass_counter, _pass_log, _debug_ir_dir

        debug_mode = getattr(opts, "debug_ir", False)

        if debug_mode:
            individual_passes = split_pipeline_to_passes(pass_pipeline)

            if opts.verbose:
                print(
                    f"[DEBUG] Splitting pipeline into {len(individual_passes)} individual passes"
                )

            if _pass_counter == 0 and _debug_ir_dir:
                save_initial_ir(mlir_module, opts)

            for single_pass in individual_passes:
                run_single_pass(single_pass, mlir_module, opts)

            if outputfile:
                with open(outputfile, "w") as f:
                    f.write(str(mlir_module))
        else:
            if opts.verbose:
                print("Running:", pass_pipeline)
            PassManager.parse(pass_pipeline).run(mlir_module.operation)
            if outputfile:
                with open(outputfile, "w") as g:
                    g.write(str(mlir_module))

    def lower_airrt_to_airhost(
        air_to_aie_module, air_placed_module, air_mlir_filename, opts, aiecc_path
    ):
        pass_pipeline = "air-split-devices{"
        pass_pipeline = pass_pipeline + f"output-prefix={opts.tmpdir}/" + "}"
        run_passes("builtin.module(" + pass_pipeline + ")", air_to_aie_module, opts)

        airrt_module = Module.parse(str(air_to_aie_module))
        aie_ctrl_airrt = opts.tmpdir + "/airrt." + air_mlir_filename
        pass_pipeline = ",".join(
            [
                "convert-vector-to-llvm",
                "convert-math-to-llvm",
                "func.func(air-label-broadcast-channel-with-tile)",
                "lower-affine",
                "func.func(air-opt-shim-dma-bds{device=" + opts.device + "})",
                "air-to-std",
                "air-lower-linalg-tensors",
                "canonicalize",
                "cse",
            ]
        )
        run_passes(
            "builtin.module(" + pass_pipeline + ")", airrt_module, opts, aie_ctrl_airrt
        )

        aie_ctrl = opts.tmpdir + "/aie_ctrl." + air_mlir_filename
        pass_pipeline = ",".join(["airrt-to-llvm", "one-shot-bufferize"])
        run_passes(
            "builtin.module(" + pass_pipeline + ")", airrt_module, opts, aie_ctrl
        )

        aie_ctrl_refback = opts.tmpdir + "/refback." + air_mlir_filename
        pass_pipeline = ",".join(
            [
                "convert-vector-to-llvm",
                "convert-math-to-llvm",
                "func.func(air-label-broadcast-channel-with-tile)",
                "lower-affine",
                "func.func(air-opt-shim-dma-bds{device=" + opts.device + "})",
                "air-to-std",
                "air-lower-linalg-tensors",
                "canonicalize",
                "cse",
                "airrt-to-llvm",
                "canonicalize",
                "cse",
            ]
        )
        run_passes(
            "builtin.module(" + pass_pipeline + ")",
            Module.parse(str(air_placed_module)),
            opts,
            aie_ctrl_refback,
        )

        aie_ctrl_llvm = opts.tmpdir + "/llvm." + air_mlir_filename
        pass_pipeline = ",".join(
            [
                "expand-strided-metadata",
                "lower-affine",
                "convert-scf-to-cf",
                "finalize-memref-to-llvm",
                "convert-func-to-llvm",
                "convert-arith-to-llvm",
                "convert-cf-to-llvm",
                "canonicalize",
                "cse",
            ]
        )
        run_passes(
            "builtin.module(" + pass_pipeline + ")", airrt_module, opts, aie_ctrl_llvm
        )

        aie_ctrl_llvm_ir = opts.tmpdir + "/" + air_mlir_filename + ".ll"
        do_call(
            [
                "aie-translate",
                "--mlir-to-llvmir",
                aie_ctrl_llvm,
                "-o",
                aie_ctrl_llvm_ir,
            ],
            opts,
        )

        aie_ctrl_llvm_opt_bc = opts.tmpdir + "/" + air_mlir_filename + ".opt.bc"
        do_call(["opt", "-O3", aie_ctrl_llvm_ir, "-o", aie_ctrl_llvm_opt_bc], opts)

        aie_ctrl_llvm_opt_ir = opts.tmpdir + "/" + air_mlir_filename + ".opt.ll"
        do_call(["llvm-dis", aie_ctrl_llvm_opt_bc, "-o", aie_ctrl_llvm_opt_ir], opts)

        aie_ctrl_obj = opts.tmpdir + "/" + air_mlir_filename + ".o"
        llc_target = None
        if "x86_64" in opts.host_target:
            llc_target = "x86-64"
        elif "aarch64" in opts.host_target:
            llc_target = "aarch64"
        elif opts.host_target:
            print("Unhandled llc host target: '" + opts.host_target + "'")
        do_call(
            ["llc", "-O3", "--filetype=obj", "--relocation-model=pic"]
            + (["-march=" + llc_target] if llc_target else [])
            + [aie_ctrl_llvm_opt_ir, "-o", aie_ctrl_obj],
            opts,
        )

        t = do_run(["air-translate", "--airrt-generate-json", aie_ctrl_airrt], opts)
        module_meta = eval(t.stdout)
        segments = [module_meta[segment]["sym_name"] for segment in module_meta]
        obj_files = [aie_ctrl_obj]
        for segment in segments:
            if opts.verbose:
                print("Compiling segment:", segment)

            segment_file = opts.tmpdir + "/aie." + segment + ".mlir"
            aiecc_file = opts.tmpdir + "/aiecc." + segment + ".mlir"
            aiecc_dir = opts.tmpdir + "/" + segment

            do_call(
                [
                    "air-opt",
                    segment_file,
                    "-air-lower-linalg-tensors",
                    "-lower-affine",
                    "-canonicalize",
                    "-cse",
                    "-o",
                    aiecc_file,
                ],
                opts,
            )

            if "x86_64" in platform.uname()[5]:
                aiecc_target = "x86_64-amd-linux-gnu"
            else:
                aiecc_target = "aarch64-linux-gnu"
            aiecc_target = opts.host_target if opts.host_target else aiecc_target

            sysroot = opts.sysroot if opts.sysroot else "/"
            do_call(
                ["aiecc.py"]
                + (["-v"] if opts.verbose else [])
                + ["--sysroot", sysroot]
                + ["--host-target", aiecc_target]
                + ["--tmpdir", aiecc_dir]
                + ["--no-aiesim"]
                + ["--compile-host"]
                + ["--xbridge" if opts.xbridge else "--no-xbridge"]
                + ["--xchesscc" if opts.xchesscc else "--no-xchesscc"]
                + [aiecc_file],
                opts,
            )

            inc_file = opts.tmpdir + "/" + air_mlir_filename + "." + segment + ".inc"
            cpp_file = opts.tmpdir + "/" + air_mlir_filename + "." + segment + ".cpp"
            obj_file = opts.tmpdir + "/" + air_mlir_filename + "." + segment + ".o"

            do_call(["cp", aiecc_dir + "/aie_inc.cpp", inc_file], opts)

            with open(cpp_file, "w") as f:
                f.write(emit_wrapper(segment, inc_file))

            cmd = [opts.cc, "-std=c++17", "-g", "-I."]

            cmd += ["--sysroot=%s" % opts.sysroot] if opts.sysroot else []
            if opts.sysroot and "aarch64-linux-gnu" in opts.host_target:
                cmd += ["--gcc-toolchain=%s/usr" % opts.sysroot]
            cmd += ["--target=%s" % opts.host_target] if opts.host_target else []

            thispath = os.path.dirname(os.path.realpath(__file__))
            cmd += [f"-I{thispath}/../../../../runtime_lib/airhost/include"]

            if "x86_64" in aiecc_target:
                cmd += [f"-I{aiecc_path}/runtime_lib/x86_64/test_lib/include"]
            if "aarch64" in aiecc_target:
                cmd += [f"-I{aiecc_path}/runtime_lib/aarch64/test_lib/include"]

            cmd += [f"-I{libxaie_path}/include"]
            cmd += [f"-I{rocm_path}/../../../include"]
            cmd += ["-DLIBXAIENGINEV2"]
            cmd += ["-DAIE_LIBXAIE_ENABLE", "-fPIC", "-c"]
            cmd += ["-o", obj_file, cpp_file]
            do_call(cmd, opts)

            obj_files.append(obj_file)

        lib_file = air_mlir_filename + (".so" if opts.shared else ".a")
        lib_file = opts.tmpdir + "/" + lib_file
        if opts.shared:
            cmd = ["clang", "-shared"]
            cmd += ["--sysroot", opts.sysroot] if opts.sysroot else []
            cmd += ["-target", opts.host_target] if opts.host_target else []
            cmd += ["-fuse-ld=lld", "-o", lib_file] + obj_files
        else:
            cmd = ["llvm-ar", "rc", lib_file] + obj_files
        do_call(cmd, opts)

        if opts.output_file:
            do_call(["cp", lib_file, opts.output_file], opts)

    # Main AIE compilation logic
    if opts.tmpdir:
        tmpdirname = opts.tmpdir
        try:
            os.mkdir(tmpdirname)
        except FileExistsError:
            pass
        if opts.verbose:
            print("created temporary directory", tmpdirname)

    if not opts.num_cols:
        if "npu1" in opts.device:
            opts.num_cols = 4
        elif "npu2_4col" in opts.device:
            opts.num_cols = 4
        elif "npu2" in opts.device:
            opts.num_cols = 8
        else:
            opts.num_cols = 10

    if not opts.col_offset:
        opts.col_offset = 0 if "npu" in opts.device else 7

    if not opts.num_rows:
        opts.num_rows = 6

    if not opts.row_offset:
        opts.row_offset = 2

    if opts.verbose:
        print("compiling %s for %s\n" % (opts.air_mlir_file, opts.device))

    # Validate output_format compatibility with target device
    if opts.output_format == "elf" and "npu1" in opts.device:
        print(f"Error: output_format='elf' is not supported for {opts.device} target.")
        print("ELF output format is only supported on npu2 and later devices.")
        sys.exit(1)

    # Setup debug IR directory if debug mode is enabled
    if getattr(opts, "debug_ir", False):
        debug_dir = setup_debug_ir_dir(opts.tmpdir)
        if opts.verbose:
            print(f"Debug mode enabled: saving intermediate IRs to {debug_dir}")

    aiecc_path = shutil.which("aiecc.py")
    if aiecc_path == None:
        print("Error: could not find aiecc.py")
        sys.exit(1)

    aiecc_path = os.path.dirname(os.path.realpath(aiecc_path)) + "/.."
    if opts.verbose:
        print("Using aiecc.py from: ", aiecc_path)

    if mlir_module is not None:
        # Use the caller's module and context (from run() API)
        ctx_manager = mlir_module.context
        _, air_mlir_filename = os.path.split(
            opts.air_mlir_file if hasattr(opts, "air_mlir_file") else "input.mlir"
        )
    else:
        # Create new context and read from file (from main() CLI)
        ctx_manager = Context()

    with ctx_manager as ctx, Location.unknown():
        if mlir_module is None:
            with open(opts.air_mlir_file, "r") as f:
                mlir_module = Module.parse(f.read())

        _, air_mlir_filename = os.path.split(
            opts.air_mlir_file if hasattr(opts, "air_mlir_file") else "input.mlir"
        )
        air_collapse_herd_to_cols_pass = (
            "func.func(air-collapse-herd{" + f"max-col-size={4} " + "})"
        )
        trace_col_offset = 1 if int(opts.trace_size) > 0 else 0
        air_place_pass = (
            "air-place-herds{"
            + f"num-rows={opts.num_rows} "
            + f"num-cols={opts.num_cols} "
            + f"row-anchor={opts.row_offset} "
            + f"col-anchor={int(opts.col_offset) + trace_col_offset}"
            + "}"
        )

        air_placed = opts.tmpdir + "/placed." + air_mlir_filename
        pass_pipeline = ",".join(
            [
                "air-insert-launch-around-herd{insert-segment=true}",
                "func.func(air-lower-herd-parallel)",
                "scf-forall-to-parallel",
            ]
            + (
                get_air_optimization_pass(
                    opts.device,
                    opts.omit_pingpong,
                    opts.lower_linalg_to_func,
                    opts.air_loop_fusion,
                    opts.omit_auto_broadcast,
                    opts.channel_multiplexing,
                )
                if "npu" in opts.device
                else []
            )
            + [
                air_collapse_herd_to_cols_pass,
                "canonicalize",
                "cse",
                air_place_pass,
                "canonicalize",
                "cse",
                "func.func(air-renumber-dma)",
            ]
        )
        air_placed_module = Module.parse(str(mlir_module))
        run_passes(
            "builtin.module(" + pass_pipeline + ")", air_placed_module, opts, air_placed
        )

        # Add checkpoint for placed.air.mlir
        if getattr(opts, "debug_ir", False):
            last_output = _pass_log[-1].get("outputfile") if _pass_log else None
            add_checkpoint("AIR Placement Complete", "placed.air.mlir", last_output)
            if _debug_ir_dir:
                dump_pass_log(os.path.join(_debug_ir_dir, "pass.log"))

        air_to_aie_pass = "air-to-aie{"
        air_to_aie_pass = (
            air_to_aie_pass
            + f"emit-while-loop={str(not opts.omit_while_true_loop).lower()}"
        )
        air_to_aie_pass = air_to_aie_pass + f" row-offset={opts.row_offset}"
        air_to_aie_pass = air_to_aie_pass + f" col-offset={opts.col_offset}"
        air_to_aie_pass = air_to_aie_pass + f" device={opts.device}"
        if int(opts.trace_size) > 0:
            air_to_aie_pass = air_to_aie_pass + " insert-trace-packet-flow=true"
        air_to_aie_pass = (
            air_to_aie_pass
            + f" use-lock-race-condition-fix={opts.use_lock_race_condition_fix}"
        )
        air_to_aie_pass = air_to_aie_pass + "}"
        pass_pipeline = ",".join(
            [
                air_to_aie_pass,
                "air-merge-unrolled-devices",
            ]
        )

        air_to_aie_file = opts.tmpdir + "/aie." + air_mlir_filename
        air_to_aie_module = Module.parse(str(air_placed_module))
        run_passes(
            "builtin.module(" + pass_pipeline + ")",
            air_to_aie_module,
            opts,
            air_to_aie_file,
        )

        # Add checkpoint for aie.air.mlir
        if getattr(opts, "debug_ir", False):
            last_output = _pass_log[-1].get("outputfile") if _pass_log else None
            add_checkpoint(
                "AIR to AIE Conversion Complete", "aie.air.mlir", last_output
            )
            if _debug_ir_dir:
                dump_pass_log(os.path.join(_debug_ir_dir, "pass.log"))

        if "npu" in opts.device:
            air_opt_shim_dma_bds_pass = "func.func(air-opt-shim-dma-bds{device="
            air_opt_shim_dma_bds_pass = air_opt_shim_dma_bds_pass + opts.device
            air_opt_shim_dma_bds_pass = air_opt_shim_dma_bds_pass + (
                " shim-dma-tile-sizes="
                + ",".join(str(s) for s in opts.runtime_loop_tiling_sizes)
                if opts.runtime_loop_tiling_sizes
                else ""
            )
            air_opt_shim_dma_bds_pass = air_opt_shim_dma_bds_pass + "})"

            airrt_to_npu_pass = "airrt-to-npu{"
            airrt_to_npu_pass = airrt_to_npu_pass + f" trace-size={opts.trace_size}"
            airrt_to_npu_pass = airrt_to_npu_pass + f" trace-offset={opts.trace_offset}"
            # Enable output-elf mode when generating ELF format output
            output_elf = opts.output_format == "elf"
            airrt_to_npu_pass = (
                airrt_to_npu_pass + f" output-elf={str(output_elf).lower()}" + "}"
            )

            air_to_npu_file = opts.tmpdir + "/npu." + air_mlir_filename
            air_to_npu_module = Module.parse(str(air_to_aie_module))
            air_to_npu_passes = (
                "builtin.module("
                + ",".join(
                    [
                        air_opt_shim_dma_bds_pass,
                        "canonicalize",
                        "cse",
                        "air-to-std",
                        "symbol-dce",
                        "affine-expand-index-ops",
                        "canonicalize",
                        "cse",
                        airrt_to_npu_pass,
                        "canonicalize",
                        "cse",
                    ]
                )
                + ")"
            )
            run_passes(air_to_npu_passes, air_to_npu_module, opts, air_to_npu_file)

            # Add checkpoint for npu.air.mlir
            if getattr(opts, "debug_ir", False):
                last_output = _pass_log[-1].get("outputfile") if _pass_log else None
                add_checkpoint(
                    "NPU Instruction Generation Complete", "npu.air.mlir", last_output
                )
                if _debug_ir_dir:
                    dump_pass_log(os.path.join(_debug_ir_dir, "pass.log"))

            xclbin_file = "aie.xclbin"
            if opts.output_file:
                xclbin_file = opts.output_file
            if opts.insts_file:
                insts_file = opts.insts_file
            else:
                assert xclbin_file.endswith(".xclbin")
                insts_file = opts.output_file.removesuffix(".xclbin") + ".insts.bin"
            if opts.output_format == "elf":
                # ELF generation mode: generate aie.elf instead of xclbin
                # Automatically enable --expand-load-pdis for optimized PDI loading
                aiecc_output_file_options = [
                    "--generate-full-elf",
                    "--expand-load-pdis",
                    "--full-elf-name=" + opts.elf_name,
                ]
            elif opts.output_format == "xclbin":
                aiecc_output_file_options = ["--aie-generate-xclbin"]
            elif opts.output_format == "txn":
                aiecc_output_file_options = ["--aie-generate-txn"]
            elif opts.output_format == "none":
                aiecc_output_file_options = []
            else:
                print("Error: unknown output-format (valid: elf, xclbin, txn, none)")
                sys.exit(1)

            # Add xclbin-specific options only when not in ELF generation mode
            if opts.output_format != "elf":
                aiecc_output_file_options = aiecc_output_file_options + [
                    (
                        "--xclbin-name=" + xclbin_file
                        if opts.output_format == "xclbin"
                        else ""
                    ),
                    (
                        "--xclbin-kernel-name=" + opts.kernel_name
                        if opts.kernel_name
                        else ""
                    ),
                    (
                        "--xclbin-instance-name=" + opts.instance_name
                        if opts.instance_name
                        else ""
                    ),
                    ("--xclbin-kernel-id=" + opts.kernel_id if opts.kernel_id else ""),
                ]
                aiecc_existing_xclbin_options = [
                    "--xclbin-input=" + opts.xclbin_input if opts.xclbin_input else ""
                ]
            else:
                aiecc_existing_xclbin_options = []
            # Build base aiecc options
            aiecc_base_options = [
                "--no-aiesim",
                "--xchesscc" if opts.xchesscc else "--no-xchesscc",
                "--xbridge" if opts.xbridge else "--no-xbridge",
                "--no-compile-host",
                "--tmpdir=" + opts.tmpdir,
            ]
            # Only add NPU instruction options when not generating ELF
            # (ELF mode embeds instructions in the ELF file)
            if opts.output_format != "elf":
                aiecc_base_options += [
                    "--aie-generate-npu",
                    "--npu-insts-name=" + insts_file,
                ]
            aiecc_options = (
                (["-v"] if opts.verbose else [])
                + aiecc_base_options
                + (
                    ["--peano"] + [opts.peano_install_dir]
                    if opts.peano_install_dir
                    else []
                )
                + (["-O", "3"])
                + aiecc_output_file_options
                + aiecc_existing_xclbin_options
                + [air_to_npu_file]
            )
            aiecc_options = [a for a in aiecc_options if a != ""]
            if opts.verbose:
                print("Running aiecc.py with options:", " ".join(aiecc_options))
            import aie.compiler.aiecc.main as aiecc

            aiecc.run(air_to_npu_module, aiecc_options)

            # Dump pass log to tmpdir for documentation
            if getattr(opts, "debug_ir", False) and _debug_ir_dir:
                debug_pass_log = os.path.join(_debug_ir_dir, "pass.log")
                dump_pass_log(debug_pass_log)
                if opts.verbose:
                    print(f"Pass log written to: {debug_pass_log}")
        else:
            lower_airrt_to_airhost(
                air_to_aie_module,
                air_placed_module,
                air_mlir_filename,
                opts,
                aiecc_path,
            )


def run(mlir_module, args=None):
    """Run the aircc compilation pipeline on an in-memory MLIR module.

    This is the Python API entry point used by XRT backend and other callers.

    Args:
        mlir_module: An MLIR Module object (from Python bindings)
        args: Optional list of command-line argument strings
    """
    reset_pass_log()

    opts = (
        cl_arguments.parse_args(args) if args is not None else cl_arguments.parse_args()
    )

    if opts.tmpdir:
        try:
            os.mkdir(opts.tmpdir)
        except FileExistsError:
            pass
    else:
        opts.tmpdir = tempfile.mkdtemp()

    # Dispatch based on target
    target = getattr(opts, "target", "aie")
    if target == "gpu":
        # GPU pipeline uses subprocess calls, needs file on disk
        input_file = os.path.join(opts.tmpdir, "input.mlir")
        with open(input_file, "w") as f:
            f.write(str(mlir_module))
        opts.air_mlir_file = input_file
        run_gpu_compilation(opts)
    else:
        # AIE pipeline uses Python bindings, pass module directly
        run_aie_compilation(opts, mlir_module=mlir_module)


def main():
    opts = cl_arguments.parse_args()

    # Dispatch based on target
    if opts.target == "gpu":
        run_gpu_compilation(opts)
    else:
        # Parse module and pass it to run_aie_compilation so it reuses
        # this context (matches the original main() behavior on main branch)
        from air.ir import Module, Context, Location
        from air.dialects import air as airdialect

        with Context() as ctx, Location.unknown():
            with open(opts.air_mlir_file, "r") as f:
                mlir_module = Module.parse(f.read())
            run_aie_compilation(opts, mlir_module=mlir_module)


if __name__ == "__main__":
    main()
