
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E280, LENGTH = 0x1D80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf347_unroll_1 = .;
. += 0x80;
. = 0x42400;
buf346_unroll_1 = .;
. += 0x80;
. = 0x40400;
buf345_unroll_1 = .;
. += 0x2000;
. = 0x44000;
buf344_unroll_1 = .;
. += 0x2000;
. = 0x48000;
buf343_unroll_1 = .;
. += 0x2000;
. = 0x4C000;
buf342_unroll_1 = .;
. += 0x2000;
. = 0x46000;
buf341_unroll_1 = .;
. += 0x2000;
. = 0x4E080;
buf340_unroll_1 = .;
. += 0x80;
. = 0x42480;
buf339_unroll_1 = .;
. += 0x80;
. = 0x4A000;
buf338_unroll_1 = .;
. += 0x2000;
. = 0x4E100;
buf337_unroll_1 = .;
. += 0x80;
. = 0x42500;
buf336_unroll_1 = .;
. += 0x80;
. = 0x4E180;
buf335_unroll_1 = .;
. += 0x80;
. = 0x42580;
buf334_unroll_1 = .;
. += 0x80;
. = 0x4E200;
buf333_unroll_1 = .;
. += 0x80;
. = 0x42600;
buf332_unroll_1 = .;
. += 0x80;
. = 0x5E000;
buf395_unroll_1 = .;
. += 0x80;
. = 0x52400;
buf394_unroll_1 = .;
. += 0x80;
. = 0x50400;
buf393_unroll_1 = .;
. += 0x2000;
. = 0x54000;
buf392_unroll_1 = .;
. += 0x2000;
. = 0x58000;
buf391_unroll_1 = .;
. += 0x2000;
. = 0x5C000;
buf390_unroll_1 = .;
. += 0x2000;
. = 0x56000;
buf389_unroll_1 = .;
. += 0x2000;
. = 0x5E080;
buf388_unroll_1 = .;
. += 0x80;
. = 0x52480;
buf387_unroll_1 = .;
. += 0x80;
. = 0x5A000;
buf386_unroll_1 = .;
. += 0x2000;
. = 0x5E100;
buf385_unroll_1 = .;
. += 0x80;
. = 0x52500;
buf384_unroll_1 = .;
. += 0x80;
. = 0x5E180;
buf383_unroll_1 = .;
. += 0x80;
. = 0x52580;
buf382_unroll_1 = .;
. += 0x80;
. = 0x5E200;
buf381_unroll_1 = .;
. += 0x80;
. = 0x52600;
buf380_unroll_1 = .;
. += 0x80;
. = 0x6A000;
buf454_unroll_1 = .;
. += 0x80;
. = 0x6E000;
buf453_unroll_1 = .;
. += 0x80;
. = 0x60400;
buf452_unroll_1 = .;
. += 0x2000;
. = 0x64000;
buf451_unroll_1 = .;
. += 0x2000;
. = 0x68000;
buf450_unroll_1 = .;
. += 0x2000;
. = 0x6C000;
buf449_unroll_1 = .;
. += 0x2000;
. = 0x66000;
buf448_unroll_1 = .;
. += 0x2000;
. = 0x62400;
buf447_unroll_1 = .;
. += 0x80;
. = 0x6A080;
buf446_unroll_1 = .;
. += 0x80;
. = 0x7E000;
buf411_unroll_1 = .;
. += 0x80;
. = 0x72400;
buf410_unroll_1 = .;
. += 0x80;
. = 0x70400;
buf409_unroll_1 = .;
. += 0x2000;
. = 0x74000;
buf408_unroll_1 = .;
. += 0x2000;
. = 0x78000;
buf407_unroll_1 = .;
. += 0x2000;
. = 0x7C000;
buf406_unroll_1 = .;
. += 0x2000;
. = 0x76000;
buf405_unroll_1 = .;
. += 0x2000;
. = 0x7E080;
buf404_unroll_1 = .;
. += 0x80;
. = 0x72480;
buf403_unroll_1 = .;
. += 0x80;
. = 0x7A000;
buf402_unroll_1 = .;
. += 0x2000;
. = 0x7E100;
buf401_unroll_1 = .;
. += 0x80;
. = 0x72500;
buf400_unroll_1 = .;
. += 0x80;
. = 0x7E180;
buf399_unroll_1 = .;
. += 0x80;
. = 0x72580;
buf398_unroll_1 = .;
. += 0x80;
. = 0x7E200;
buf397_unroll_1 = .;
. += 0x80;
. = 0x72600;
buf396_unroll_1 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_2h_ref/attn.o)
PROVIDE(main = core_6_4);
