
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E280, LENGTH = 0x1D80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf315_unroll_1 = .;
. += 0x80;
. = 0x42400;
buf314_unroll_1 = .;
. += 0x80;
. = 0x40400;
buf313_unroll_1 = .;
. += 0x2000;
. = 0x44000;
buf312_unroll_1 = .;
. += 0x2000;
. = 0x48000;
buf311_unroll_1 = .;
. += 0x2000;
. = 0x4C000;
buf310_unroll_1 = .;
. += 0x2000;
. = 0x46000;
buf309_unroll_1 = .;
. += 0x2000;
. = 0x4E080;
buf308_unroll_1 = .;
. += 0x80;
. = 0x42480;
buf307_unroll_1 = .;
. += 0x80;
. = 0x4A000;
buf306_unroll_1 = .;
. += 0x2000;
. = 0x4E100;
buf305_unroll_1 = .;
. += 0x80;
. = 0x42500;
buf304_unroll_1 = .;
. += 0x80;
. = 0x4E180;
buf303_unroll_1 = .;
. += 0x80;
. = 0x42580;
buf302_unroll_1 = .;
. += 0x80;
. = 0x4E200;
buf301_unroll_1 = .;
. += 0x80;
. = 0x42600;
buf300_unroll_1 = .;
. += 0x80;
. = 0x5E000;
buf191_unroll_0 = .;
. += 0x80;
. = 0x52400;
buf190_unroll_0 = .;
. += 0x80;
. = 0x50400;
buf189_unroll_0 = .;
. += 0x2000;
. = 0x54000;
buf188_unroll_0 = .;
. += 0x2000;
. = 0x58000;
buf187_unroll_0 = .;
. += 0x2000;
. = 0x5C000;
buf186_unroll_0 = .;
. += 0x2000;
. = 0x56000;
buf185_unroll_0 = .;
. += 0x2000;
. = 0x5E080;
buf184_unroll_0 = .;
. += 0x80;
. = 0x52480;
buf183_unroll_0 = .;
. += 0x80;
. = 0x5A000;
buf182_unroll_0 = .;
. += 0x2000;
. = 0x5E100;
buf181_unroll_0 = .;
. += 0x80;
. = 0x52500;
buf180_unroll_0 = .;
. += 0x80;
. = 0x5E180;
buf179_unroll_0 = .;
. += 0x80;
. = 0x52580;
buf178_unroll_0 = .;
. += 0x80;
. = 0x5E200;
buf177_unroll_0 = .;
. += 0x80;
. = 0x52600;
buf176_unroll_0 = .;
. += 0x80;
. = 0x6A000;
buf436_unroll_1 = .;
. += 0x80;
. = 0x6E000;
buf435_unroll_1 = .;
. += 0x80;
. = 0x60400;
buf434_unroll_1 = .;
. += 0x2000;
. = 0x64000;
buf433_unroll_1 = .;
. += 0x2000;
. = 0x68000;
buf432_unroll_1 = .;
. += 0x2000;
. = 0x6C000;
buf431_unroll_1 = .;
. += 0x2000;
. = 0x66000;
buf430_unroll_1 = .;
. += 0x2000;
. = 0x62400;
buf429_unroll_1 = .;
. += 0x80;
. = 0x6A080;
buf428_unroll_1 = .;
. += 0x80;
. = 0x7E000;
buf379_unroll_1 = .;
. += 0x80;
. = 0x72400;
buf378_unroll_1 = .;
. += 0x80;
. = 0x70400;
buf377_unroll_1 = .;
. += 0x2000;
. = 0x74000;
buf376_unroll_1 = .;
. += 0x2000;
. = 0x78000;
buf375_unroll_1 = .;
. += 0x2000;
. = 0x7C000;
buf374_unroll_1 = .;
. += 0x2000;
. = 0x76000;
buf373_unroll_1 = .;
. += 0x2000;
. = 0x7E080;
buf372_unroll_1 = .;
. += 0x80;
. = 0x72480;
buf371_unroll_1 = .;
. += 0x80;
. = 0x7A000;
buf370_unroll_1 = .;
. += 0x2000;
. = 0x7E100;
buf369_unroll_1 = .;
. += 0x80;
. = 0x72500;
buf368_unroll_1 = .;
. += 0x80;
. = 0x7E180;
buf367_unroll_1 = .;
. += 0x80;
. = 0x72580;
buf366_unroll_1 = .;
. += 0x80;
. = 0x7E200;
buf365_unroll_1 = .;
. += 0x80;
. = 0x72600;
buf364_unroll_1 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_2h_ref/attn.o)
PROVIDE(main = core_4_4);
