
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7E080, LENGTH = 0x1F80
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4E000;
buf427_unroll_1 = .;
. += 0x80;
. = 0x42400;
buf426_unroll_1 = .;
. += 0x80;
. = 0x40400;
buf425_unroll_1 = .;
. += 0x2000;
. = 0x44000;
buf424_unroll_1 = .;
. += 0x2000;
. = 0x48000;
buf423_unroll_1 = .;
. += 0x2000;
. = 0x4C000;
buf422_unroll_1 = .;
. += 0x2000;
. = 0x46000;
buf421_unroll_1 = .;
. += 0x2000;
. = 0x4E080;
buf420_unroll_1 = .;
. += 0x80;
. = 0x42480;
buf419_unroll_1 = .;
. += 0x80;
. = 0x4A000;
buf418_unroll_1 = .;
. += 0x2000;
. = 0x4E100;
buf417_unroll_1 = .;
. += 0x80;
. = 0x42500;
buf416_unroll_1 = .;
. += 0x80;
. = 0x4E180;
buf415_unroll_1 = .;
. += 0x80;
. = 0x42580;
buf414_unroll_1 = .;
. += 0x80;
. = 0x4E200;
buf413_unroll_1 = .;
. += 0x80;
. = 0x42600;
buf412_unroll_1 = .;
. += 0x80;
. = 0x5A000;
buf454_unroll_1 = .;
. += 0x80;
. = 0x5E000;
buf453_unroll_1 = .;
. += 0x80;
. = 0x50400;
buf452_unroll_1 = .;
. += 0x2000;
. = 0x54000;
buf451_unroll_1 = .;
. += 0x2000;
. = 0x58000;
buf450_unroll_1 = .;
. += 0x2000;
. = 0x5C000;
buf449_unroll_1 = .;
. += 0x2000;
. = 0x56000;
buf448_unroll_1 = .;
. += 0x2000;
. = 0x52400;
buf447_unroll_1 = .;
. += 0x80;
. = 0x5A080;
buf446_unroll_1 = .;
. += 0x80;
/* No tile with memory exists to the north. */
. = 0x60000;
. += 0x10000;
. = 0x7A000;
buf463_unroll_1 = .;
. += 0x80;
. = 0x7E000;
buf462_unroll_1 = .;
. += 0x80;
. = 0x70400;
buf461_unroll_1 = .;
. += 0x2000;
. = 0x74000;
buf460_unroll_1 = .;
. += 0x2000;
. = 0x78000;
buf459_unroll_1 = .;
. += 0x2000;
. = 0x7C000;
buf458_unroll_1 = .;
. += 0x2000;
. = 0x76000;
buf457_unroll_1 = .;
. += 0x2000;
. = 0x72400;
buf456_unroll_1 = .;
. += 0x80;
. = 0x7A080;
buf455_unroll_1 = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(air_project_2h_ref/attn.o)
PROVIDE(main = core_7_5);
