# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Verify adapter for the SmolVLA vision-on-NPU port — the regression gate.

SmolVLA is a continuous-output model (it emits a flow-matching action chunk),
not a token generator, so it does NOT use the shared verify subsystem's
token-set gate -- `compute_topk_set_check` and `verify_runner.py`'s HF harness
are for autoregressive LLMs. Instead this adapter drives the end-to-end pipeline
and applies the continuous-output `regression_gate` from `verify.comparators` to
the (1, 50, 6) action chunk.

The reference is the **unmodified lerobot model running on CPU**, computed live
in this same process from the same policy object, with fixed zero noise. The
only difference between the two runs is where `embed_image` gets its answer, so
the gate measures the full NPU-induced deviation end to end, on the tensor the
robot would actually execute -- not on an intermediate activation, and not
against a reimplementation.

(`smolvla_cpu_baseline.py` / `make cpu-baseline` dumps that same CPU result to
a .npz for inspection. This gate does NOT read it: a saved fixture can go stale
against a checkpoint or lerobot upgrade, and being gitignored it made the
verify lit test fail on a clean checkout.)

Runs in the lerobot venv, which -- with the mlir-air environment sourced -- also
has air/pyxrt, so no subprocess is involved. `make verify` wraps this in the NPU
lock.

Entry points (structural parity with the sibling adapters):
  DEFAULT_MODEL   HF id of the policy checkpoint
  build_config()  config/metadata dict
  run_gate()      run the pipeline, apply the gate, return the gate dict
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))
_LLMS_DIR = _HERE.parent
if str(_LLMS_DIR) not in sys.path:
    sys.path.insert(0, str(_LLMS_DIR))

from smolvla_inference import (  # noqa: E402
    DEFAULT_MODEL,
    build_config as _inference_config,
    build_oracle_batch,
    fixed_noise,
    normalized_mse,
    run_hybrid_forward,
    warmup_npu,
)
from verify.comparators import regression_gate  # noqa: E402

# Thresholds locked from the measured clean run: median per-position
# action-chunk cosine 0.9990 against the pure-CPU baseline, normalized MSE
# 0.0030. Cosine is the primary gate. The MSE criterion is NORMALIZED so the
# gate is magnitude-invariant -- a raw absolute MSE bound would silently drift
# PASS/FAIL as action magnitude changes with the prompt. NMSE_MAX is ~13x the
# observed value: a round number with real margin.
COS_MIN = 0.99
NMSE_MAX = 0.04


def build_config(npu_vision: bool = True) -> dict:
    cfg = _inference_config(npu_vision)
    cfg.update({"gate": "regression", "cos_min": COS_MIN, "nmse_max": NMSE_MAX})
    return cfg


def run_gate(
    cos_min: float = COS_MIN,
    nmse_max: float = NMSE_MAX,
    npu_vision: bool = True,
    n_cameras=None,
) -> dict:
    """Run the pipeline once on synthetic input and return the gate dict.

    Gates on cosine (primary) AND magnitude-invariant normalized MSE; the raw
    MSE is kept in the dict for the report.

    n_cameras : None (default) feeds all three, which is what the gate and the
        lit test run. 1 or 2 is a legal model configuration and needs no
        recompile, but is not the shipping one.
    """
    from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy

    policy = SmolVLAPolicy.from_pretrained(DEFAULT_MODEL).eval()
    batch = build_oracle_batch(policy, n_cameras=n_cameras)
    noise = fixed_noise(policy)

    # The reference is computed HERE, in this process, from the same policy
    # object -- not loaded from a saved fixture. A fixture would have to be
    # regenerated by hand and can silently go stale against a checkpoint or
    # lerobot upgrade; it also made run_npu2_verify.lit fail on a clean
    # checkout, since the .npz is gitignored and the lit test does not build
    # it. The siblings compute their HF reference live for the same reason.
    # Costs one extra CPU forward (~0.9 s) and makes the comparison airtight:
    # same weights, same batch, same noise, one variable.
    ref = run_hybrid_forward(batch, policy=policy, noise=noise, npu_vision=False)

    if npu_vision:
        warmup_npu()
    chunk = run_hybrid_forward(
        batch,
        policy=policy,
        noise=noise,
        npu_vision=npu_vision,
    )
    assert chunk.shape == ref.shape, (chunk.shape, ref.shape)

    g = regression_gate(chunk, ref, cos_min=cos_min, mse_max=float("inf"))
    g["nmse"] = normalized_mse(chunk, ref)
    g["nmse_max"] = nmse_max
    g["max_abs"] = float(np.abs(chunk - ref).max())
    g["passed"] = bool(g["cosine"] >= cos_min and g["nmse"] <= nmse_max)
    return g


def survey_real(n_cameras, dataset, n_frames, prompt, npu_vision=True) -> int:
    """NPU vs CPU over real recorded frames. Reports, does not gate.

    Deliberately not pass/fail. The synthetic gate is a regression detector and
    its exit code means something; this answers a different question -- how much
    headroom the precision has on inputs the model will actually see -- and a
    handful of frames below threshold at 1 or 2 cameras is a finding, not a
    build failure. Always returns 0.
    """
    from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy

    import smolvla_dataset

    policy = SmolVLAPolicy.from_pretrained(DEFAULT_MODEL).eval()
    noise = fixed_noise(policy)
    if npu_vision:
        warmup_npu()

    cs, ns, per_dim, failed = [], [], None, []
    for i, (idx, batch) in enumerate(
        smolvla_dataset.batches(policy, prompt, n_cameras, dataset, n_frames)
    ):
        ref = run_hybrid_forward(batch, policy=policy, noise=noise, npu_vision=False)
        chunk = run_hybrid_forward(
            batch, policy=policy, noise=noise, npu_vision=npu_vision
        )
        g = regression_gate(chunk, ref, cos_min=COS_MIN, mse_max=float("inf"))
        c, m = g["cosine"], normalized_mse(chunk, ref)
        cs.append(c)
        ns.append(m)
        if c < COS_MIN or m > NMSE_MAX:
            failed.append((idx, c, m))
        d = np.abs(chunk - ref).max(axis=(0, 1))
        per_dim = d if per_dim is None else np.maximum(per_dim, d)
        if (i + 1) % 25 == 0:
            print(f"  {i + 1}/{n_frames}", flush=True)

    cs, ns = np.array(cs), np.array(ns)
    worst_dim = int(np.argmax(per_dim))
    print("=" * 60)
    print(f"SmolVLA verify: real frames — {dataset}")
    print(f"  {len(cs)} frames, {n_cameras} camera(s), noise pinned to zero")
    print("=" * 60)
    print(
        f"  within threshold  {len(cs) - len(failed)}/{len(cs)}"
        f"   (cosine >= {COS_MIN}, nMSE <= {NMSE_MAX})"
    )
    print(
        f"  cosine   median {np.median(cs):.6f}  P10 {np.percentile(cs, 10):.6f}"
        f"  worst {cs.min():.6f}"
    )
    print(
        f"  nmse     median {np.median(ns):.6f}  P90 {np.percentile(ns, 90):.6f}"
        f"  worst {ns.max():.6f}"
    )
    print(
        f"  worst action dim {worst_dim}, max abs {per_dim[worst_dim]:.5f}"
        f"   all dims {np.array2string(per_dim, precision=4)}"
    )
    for idx, c, m in failed[:5]:
        print(f"    below threshold: frame {idx}  cosine {c:.6f}  nmse {m:.6f}")
    if len(failed) > 5:
        print(f"    ... and {len(failed) - 5} more")
    print("=" * 60)
    print("  A survey, not a gate — the synthetic run is the pass/fail check.")
    return 0


def main() -> int:
    """The gate: NPU vision + connector, CPU backbone and expert, one process.

    Synthetic input (the default) is the gate: deterministic, one frame,
    pass/fail, and what CI and the lit test run. --input real surveys real
    recorded frames instead and always exits 0; see survey_real.

    --cpu-vision runs the unmodified model against itself, which should score
    exactly 1.0 -- a sanity check that the harness is deterministic and that
    the two forwards differ in nothing but the vision backend.
    """
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--input", choices=("synthetic", "real"), default="synthetic")
    ap.add_argument("--cameras", type=int, default=3)
    ap.add_argument("--dataset", default="lerobot/droid_100")
    ap.add_argument("--frames", type=int, default=100)
    ap.add_argument("--prompt", default="pick up the object")
    ap.add_argument("--cpu-vision", action="store_true")
    args = ap.parse_args()
    npu_vision = not args.cpu_vision

    if args.input == "real":
        return survey_real(
            args.cameras, args.dataset, args.frames, args.prompt, npu_vision
        )

    # n_cameras=None at the default 3 keeps the gate path byte-identical.
    n_cam = None if args.cameras == 3 else args.cameras
    g = run_gate(npu_vision=npu_vision, n_cameras=n_cam)
    cfg = build_config(npu_vision)
    print("=" * 60)
    print("SmolVLA verify: end-to-end action-chunk regression gate")
    print(f"  NPU stages     : {cfg['npu_stages']}")
    print(f"  execution model: {cfg['execution_model']}")
    if n_cam is not None:
        print(f"  cameras        : {n_cam} (not the shipping 3)")
    print("=" * 60)
    for k in ("cosine", "cos_min", "mse", "nmse", "nmse_max", "max_abs", "passed"):
        print(f"  {k:8s} = {g[k]}")
    print("=" * 60)
    print("[verify] PASS" if g["passed"] else "[verify] FAIL")
    return 0 if g["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
