# Copyright (C) 2026, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

"""Verify adapter for the SmolVLA vision-on-NPU port — the regression gate.

SmolVLA is a continuous-output model (it emits a flow-matching action chunk),
not a token generator, so it does NOT use the shared verify subsystem's
token-set gate -- `compute_topk_set_check` and `verify_runner.py`'s HF harness
are for autoregressive LLMs. Instead this adapter drives the end-to-end pipeline
and applies the continuous-output `regression_gate` from `verify.comparators` to
the (1, 50, 6) action chunk.

The reference is the **unmodified lerobot model running on CPU**, computed live
in this same process from the same policy object, with fixed zero noise. The
only difference between the two runs is where `embed_image` gets its answer, so
the gate measures the full NPU-induced deviation end to end, on the tensor the
robot would actually execute -- not on an intermediate activation, and not
against a reimplementation.

(`smolvla_cpu_baseline.py` / `make cpu-baseline` dumps that same CPU result to
a .npz for inspection. This gate does NOT read it: a saved fixture can go stale
against a checkpoint or lerobot upgrade, and being gitignored it made the
verify lit test fail on a clean checkout.)

Runs in the lerobot venv, which -- with the mlir-air environment sourced -- also
has air/pyxrt, so no subprocess is involved. `make verify` wraps this in the NPU
lock.

Entry points (structural parity with the sibling adapters):
  DEFAULT_MODEL   HF id of the policy checkpoint
  build_config()  config/metadata dict
  run_gate()      run the pipeline, apply the gate, return the gate dict
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))
_LLMS_DIR = _HERE.parent
if str(_LLMS_DIR) not in sys.path:
    sys.path.insert(0, str(_LLMS_DIR))

from smolvla_inference import (  # noqa: E402
    DEFAULT_MODEL,
    build_config as _inference_config,
    build_oracle_batch,
    fixed_noise,
    normalized_mse,
    run_hybrid_forward,
    warmup_npu,
)
from verify.comparators import regression_gate  # noqa: E402

# Thresholds locked from the measured clean run: median per-position
# action-chunk cosine 0.9990 against the pure-CPU baseline, normalized MSE
# 0.0030. Cosine is the primary gate. The MSE criterion is NORMALIZED so the
# gate is magnitude-invariant -- a raw absolute MSE bound would silently drift
# PASS/FAIL as action magnitude changes with the prompt. NMSE_MAX is ~13x the
# observed value: a round number with real margin.
COS_MIN = 0.99
NMSE_MAX = 0.04


def build_config(npu_vision: bool = True) -> dict:
    cfg = _inference_config(npu_vision)
    cfg.update({"gate": "regression", "cos_min": COS_MIN, "nmse_max": NMSE_MAX})
    return cfg


def run_gate(
    cos_min: float = COS_MIN,
    nmse_max: float = NMSE_MAX,
    npu_vision: bool = True,
) -> dict:
    """Run the pipeline once and return the gate dict.

    Gates on cosine (primary) AND magnitude-invariant normalized MSE; the raw
    MSE is kept in the dict for the report.
    """
    from lerobot.policies.smolvla.modeling_smolvla import SmolVLAPolicy

    policy = SmolVLAPolicy.from_pretrained(DEFAULT_MODEL).eval()
    batch = build_oracle_batch(policy)
    noise = fixed_noise(policy)

    # The reference is computed HERE, in this process, from the same policy
    # object -- not loaded from a saved fixture. A fixture would have to be
    # regenerated by hand and can silently go stale against a checkpoint or
    # lerobot upgrade; it also made run_npu2_verify.lit fail on a clean
    # checkout, since the .npz is gitignored and the lit test does not build
    # it. The siblings compute their HF reference live for the same reason.
    # Costs one extra CPU forward (~0.9 s) and makes the comparison airtight:
    # same weights, same batch, same noise, one variable.
    ref = run_hybrid_forward(batch, policy=policy, noise=noise, npu_vision=False)

    if npu_vision:
        warmup_npu()
    chunk = run_hybrid_forward(
        batch,
        policy=policy,
        noise=noise,
        npu_vision=npu_vision,
    )
    assert chunk.shape == ref.shape, (chunk.shape, ref.shape)

    g = regression_gate(chunk, ref, cos_min=cos_min, mse_max=float("inf"))
    g["nmse"] = normalized_mse(chunk, ref)
    g["nmse_max"] = nmse_max
    g["max_abs"] = float(np.abs(chunk - ref).max())
    g["passed"] = bool(g["cosine"] >= cos_min and g["nmse"] <= nmse_max)
    return g


def main() -> int:
    """The gate: NPU vision + connector, CPU backbone and expert, one process.

    --cpu-vision runs the unmodified model against itself, which should score
    exactly 1.0 -- a sanity check that the harness is deterministic and that
    the two forwards differ in nothing but the vision backend.
    """
    npu_vision = "--cpu-vision" not in sys.argv
    g = run_gate(npu_vision=npu_vision)
    cfg = build_config(npu_vision)
    print("=" * 60)
    print("SmolVLA verify: end-to-end action-chunk regression gate")
    print(f"  NPU stages     : {cfg['npu_stages']}")
    print(f"  execution model: {cfg['execution_model']}")
    print("=" * 60)
    for k in ("cosine", "cos_min", "mse", "nmse", "nmse_max", "max_abs", "passed"):
        print(f"  {k:8s} = {g[k]}")
    print("=" * 60)
    print("[verify] PASS" if g["passed"] else "[verify] FAIL")
    return 0 if g["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
